// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module ATOZ4SCSICALDGenerateNumber
#======================================================================
#  2016/04/07 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =JS0FM  \
JS0GROUP \
CATDialogEngine \
CATSysTS \
CATMathematics \
DI0PANV2 \
CATAfrFoundation \
CATDraftingGenUseItf \
CATDraftingUseItf    \
DraftingPubIDL       \
CATAfrItf            \
VPMEditorInterfaces \
CATPLMComponentInterfaces \
CATMecModLiveUseItf \
CAT3DPhysicalRepItf \
CATSysTS \
CATMecModUseItf \
DataCommonProtocolUse \
CATVisItf \
ObjectModelerSystem \
SceneGraphManager \
CATObjectModelerNavigator \
KnowledgeItf \
CATPLMIdentificationAccess \
PLMDictionaryNavServices \
CATVisController \
SGInfra \
CATMathematics \
CATGMModelInterfaces \
CATAfrNavigator \
CATIAApplicationFrame \
CATPLMIntegrationAccess \
CATPLMIntegrationUse \
CATProductStructureUseItf \
CATObjectModelerBase \
CATProductStructureInterfaces \
CATAnnotationUseItf \
CATPLMUIInterfaces \
CATSketcherUseItf \
CATFmtToolsInterfaces \
CATPLMUpdateUseItf \
# END WIZARD EDITION ZONE