//===================================================================
// COPYRIGHT atoz 2021/03/12
//===================================================================
// ATOZCenterLinesCrtingCmd.cpp
// Header definition of class ATOZCenterLinesCrtingCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/03/12 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef ATOZCenterLinesCrtingCmd_H
#define ATOZCenterLinesCrtingCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "ATOZCenterLinesCrtingDlg.h"
#include "CATPathElementAgent.h"
//system includes
#include "CATCommand.h"
#include "CATBaseUnknown.h"   
#include "CATGetEnvValue.h"
#include "CATLib.h"   
#include "CATError.h" 
#include "CATListOfDouble.h"
#include "CATAutoConversions.h"
#include "CATUnicodeChar.h"
#include "CATIDftView.h"

//AfrFoundation includes
#include "CATApplicationFrame.h"
#include "CATFrmEditor.h"
#include "CATFrmLayout.h"
#include "CATFrmWindow.h"
//Dialog includes
#include "CATDlgNotify.h"

//AfrNavigator includes
#include "CATFrmNavigGraphicWindow.h"
#include "CATNavigBox.h"

//CATIAApplicationFrame includes
#include "CATCafCenterGraph.h"
//CATPLMComponentInterfaces includes
#include "CATIPLMNavReference.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavRepInstance.h"
#include "CATPLMComponentInterfacesServices.h"
#include "CATListPtrCATIPLMNavOccurrence.h"

//CATPLMIdentificationAccess includes
#include "CATIPLMComponent.h"
#include "CATIAdpType.h"
#include "CATPLMTypeServices.h"
#include "CATListPtrCATIPLMComponent.h"


//CATMecModLiveUseItf includes
#include "CATIMmiPrtContainer.h"
#include "CATIBodyRequest.h"

//CATMecModUseItf inlcudes
#include "CATIMmiUseSetFactory.h"
#include "CATIMmiUseMfBRep.h"
#include "CATIMmiUseGeometricalElement.h"

//DataCommonProtocolUse includes
#include "CATIUseEntity.h"

//VisualizationInterfaces includes
#include "CATPathElement.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATIVisProperties.h"
#include "CATVisPropertiesValues.h"
#include "CATModifyVisProperties.h"
#include "CATI3DGeoVisu.h"
#include "CATNavigation3DViewer.h"
#include "CATViewpoint.h"


//VisualizationController includes
#include "CATViewer.h"
#include "CAT3DViewer.h"
//VisualizationFoundation includes
#include "CAT3DManipulator.h"
//ObjectModelerNavigator includes
#include "CATIRedrawEvent.h"

//SGInfra includes
#include "CAT3DBoundingSphere.h"
#include "CAT3DViewpoint.h"
#include "CATSupport.h"
#include "CAT3DBagRep.h"
#include "CAT3DFixedArrowGP.h"
#include "CAT3DCustomRep.h"
#include "CAT3DPlanRep.h"

//VisualizationCore includes
#include "CATGraphicAttributeSet.h"

//Mathematics includes
#include "CATMathPointf.h"
#include "CATMathDirectionf.h"
#include "CATMathBox.h"
#include "CATMathVector.h"
#include "CATMath3x3Matrix.h"
#include "CAT4x4Matrix.h"
#include "CATLISTV_CATMathPlane.h"

//CATMathStream includes
#include "CATSoftwareConfiguration.h"

//SGManager includes
#include "CATHSO.h"
#include "CATVisManager.h"

//ObjectModelerSystem includes
#include "CATIAlias.h"

//KnowledgeInterfaces includes
#include "CATICkeObject.h"
#include "CATIType.h"
#include "CATAttributeInfos.h"
#include "CATListValCATAttributeInfos.h"
#include "CATICkeParm.h"
#include "CATICkeParmFactory.h"
#include "CATListValCATICkeParm.h"
#include "CATCkeObjectAttrWriteServices.h"
#include "CATCkeObjectAttrReadServices.h"
#include "CATIParmPublisher.h"
#include "CATIKweModelServices.h"
#include "CATCkeGlobalFunctions.h"
#include "CATICkeParameterSet.h"
#include "CATParmPublisherAdapter.h"
#include "CATICkeFunction.h"
#include "CATITypeDictionary.h"
#include "CATICkeInst.h"

//KnowledgeIDLItf includes
#include "CATIAParameterSet.h"
#include "CATIAParameterSets.h"

//GMModelInterfaces includes
#include "CATBody.h"

//GeometricObjects includes

#include "CATPlane.h"

//GMOperatorsInterfaces includes
#include "CATICGMTopSkin.h"
#include "CATCGMCreateTopIntersect.h"
#include "CATICGMHybIntersect.h"
#include "CATICGMHybSplit.h"
#include "CATCGMCreateTopSplit.h"

//CATMecModLiveUseItf includes
#include "CATIMmiMechanicalFeature.h"
#include "CATIMmiUseCreateImport.h"
#include "CATIPartRequest.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"

//CATMecModUseItf includes
#include "CATIMmiUseDatumFactory.h"
#include "CATIMmiUseSolidInsertion.h"
#include "CATIMmiUseBasicInsertion.h"

//CATPartUseItf includes
#include "CATIPdgUsePrtFactory.h"

//MeasureGeometryInterfaces includes
#include "CATIMeasurablePlane.h"

//PLMModelerBaseInterfaces includes
#include "CATIMovable.h"

//CATGSMUseItf includes
#include "CATIGSMUseFactory.h"
#include "CATIGSMUsePlaneOffset.h"

//ProductStructureInterfaces includes
#include "CATIPLMProducts.h"
#include "CATPrdGetOccurrenceMngt.h"
#include "CATIPrdOccurrenceMngt.h"

//-----------------------------------------------------------------------
// CATPLMIntegrationAccess Framework
#include "CATIAdpEnvironment.h"
#include "CATAdpDictionaryServices.h"
#include "CATAdpAttributeSet.h"
#include "CATAdpQueryServices.h"
#include "CATAdpQueryResult.h"
#include "CATAdpIdentificationSet.h"
#include "CATLISTP_CATAdpQueryResult.h"
#include "CATIAdpPLMIdentificator.h"

// CATPLMIntegrationUse Framework
#include "CATAdpPLMQueryFilter.h"
#include "CATAdpPLMComponentsInfos.h"
#include "CATAdpPLMComponentsInfosIter.h"
#include "CATAdpPLMExtendedQueryServices.h"
#include "CATAdpPLMQueryAttributeSet.h"
#include "CATAdpPLMComponentInfos.h"
#include "CATAdpPLMComponentUniqueKey.h"
#include "CATAdpPLMQueryServices.h"
#include "CATAdpOpenParameters.h"
#include "CATAdpOpener.h"


//ProductStructureUseItf includes
#include "CATPrdFactory.h"
#include "CATIPrdReferenceFactory.h"
#include "CATIPrd3DPartReferenceFactory.h"


//PLMDictionaryNavServices Framework
#include "CATCkePLMNavPublicServices.h"
#include "CATCkePLMNavCustoAccessPublicServices.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATCkePLMNavSpecializationAccessPublicServices.h"

// System
#include "CATString.h"
#include "CATListOfCATString.h"
#include "CATListOfCATUnicodeString.h"
#include "CATSysBoolean.h"

//ObjectModelerBase includes
#include "CATOmbLifeCycleRootsBag.h"
#include "CATIDrwDimDimension.h"
#include "CATIDrwDimFakeComponent.h"
#include "CATIDrwDimValue.h"
#include "CATISktUseSketch.h"
#include <iostream>
using namespace std;

#include "CATISktUse2DWFFactory.h"
#include "CATDlgUtility.h"
#include "CATIStrUseSketchBasedDMSMngt.h"
#include "CATIMmiUsePrtPart.h"
#include "CATMmiUseServicesFactory.h"
#include "CATISktUse2DWFGeometry.h"
#include "CATIMfPoint.h"
#include "CATIMfZeroDimResult.h"
#include "CATIMfMonoDimResult.h"
#include "CATIGSMUsePointCoord.h"
#include "CATPoint.h"
#include "CATCGMAttribute.h"
#include "CATICGMUnknown.h"
#include "CATISktUse2DProperties.h"
#include "DataCommonProtocolServices.h"
#include "CATIDftCoordDimension.h"
#include <math.h>
#include<iomanip>
#include<map>
#include "CATIPLMNavRepReference.h"
#include "CATISktUseSketchFactory.h"
#include "CATISktUse2DLine.h"
#include "CATIUdfInstantiate.h"
#include "CATISktUse2DCurve.h"
#include "CATISktUse2DConstraintFactory.h"
#include "CATIPrdPublications.h"
#include "CATIPrdIterator.h"
#include "CATIPrdPublication.h"

//Drw
#include "PLMPSISessionHelpers.h"
#include "CATIDftBaseAnnotationFactory.h"
#include "CATIDftSpecialDressUpFactory.h"
#include "CATIDftText.h"
#include "CATIDftTextProperties.h"
#include "CATIDrwSubString.h"
#include "CATIDftAxisLine.h"
#include "CATIDftCenterLine.h"
#include "IDMCircle2D.h"
#include "CATSO.h"

#include "ClsPLMUtilities.h"
#include "ClsDrawingPubServices.h"
#include "ClsUniversalOperationFunc.h"
#include "CATIDftGenViewFactory.h"

#include "CATIPLMRepInstances.h"
#include "CATITPSView.h"
#include "CATIPLMNavReference.h"
#include "CATITPSServicesContainers.h"
#include "CATTPSInstantiateUseComponent.h"
#include "CATITPSSet.h"
#include "CATTPSComponent.h"

#include "IUnknown.h"
#include "CATIUnknownList.h"
#include "CATIUnknownListImpl.h"
#include "CATBaseUnknown.h"
#include "CATBaseUnknowns.h"
#include "CATUnicodeString.h"
#include "CATBoolean.h"
#include "CATLISTP_Declare.h"
#include "sequence_CATBaseUnknown.h"
#include "CATLISTP_CATBaseUnknown.h"
#include "CATInstantiateComponent.h"

// VisualizationInterface
#include "CATIBuildPath.h"


// Mathematics
#include "CATMathPlane.h"
#include "CATMathPoint2D.h"
#include "CATLISTP_CATMathPoint2D.h"
#include "CATMathDirection.h"

// CATPLMComponentInterfaces
#include "CATPLMCoreType.h"

// CATPLMIntegrationUse
#include "CATAdpSaver.h"

// CAT3DPhysicalRepInterfaces
#include "CATIPsiRepresentationReference.h"
#include "CATIPsiRepresentationLoadMode.h"

// ProductStructureInterfaces
#include "CATIPLMRepInstances.h"
#include "CATIPrdObject.h"

// DraftingUseItf
#include "CATDftDrawingPLMServices.h"
#include "CATIDftDrawing.h"
#include "CATIDftSheet.h"
#include "CATIDftView.h"
#include "CATIDftGenViewFactory.h"
#include "CATDftSectionType.h"
#include "CATOmbObjectInContext.h"
#include "CATIDftGenViewModification.h"
#include "CATIDftGenViewUpdate.h"
#include "CATDftGenViewProperties.h"
#include "CATDimDefinition.h"
#include "CATIDftDimensionReference.h"
#include "CATMathPoint2D.h"
#include "CATIDftDimensionFactory.h"
#include "CATIDrwCalloutAccess.h"
#include "CATPLMOpenServicesFactory.h"
#include "CATIPLMOpenServices.h"
#include "CATIGSMUsePlane2Lines.h"
#include "CATIGSMUseProceduralView.h"
#include "CATIMfInfiniteResult.h"
#include "CATIDrwGenDrawShape.h"
#include "CATCell.h"
#include "CATIGSMUseLinePtPt.h"
#include "CATCGMContainerMngt.h"
#include "CATICGMIntersectionSurSur.h"
#include "CATCGMCreateIntersection.h"
#include "CATICGMIntersectionCrvCrv.h"
#include "CATCartesianPoint.h"
#include "CATGeoFactory.h"
#include "CATIMmiPartModelEventManagement.h"
#include "CATIPLMNavRepOccurrence.h"
#include "CATIPipPipeInstance.h"
#include "CATIPipRigidPipeReference.h"
#include <vector>
#include "CATOtherDocumentAgent.h"
#include "DataCommonProtocolCCPServices.h"
#include "CATIPrdPublications.h"
#include "CATListPtrCATIPLMNavInstance.h"
#include "CATMathTransformation.h"
#include "CATIPrd3DPartReferenceFactory.h"
#include "CATLISTV_CATMathPoint.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class ATOZCenterLinesCrtingCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( ATOZCenterLinesCrtingCmd, CATStateCommand )

public:

ATOZCenterLinesCrtingCmd();
virtual ~ATOZCenterLinesCrtingCmd();

HRESULT InitializeMainDialog();
void OKAction();
void ExitCmd();
void SelectPipeObj();
HRESULT CreatePartUnderRoot(const CATIPLMNavReference_var &ispParentRef, 
							CATIPLMNavInstance_var &ospNewPartInst, 
							CATOmbLifeCycleRootsBag &ibag);
HRESULT BrowseOccurrences(CATIPLMNavOccurrence_var &spPLMNavOccOnCurrentNode, CATListPtrCATIPLMNavOccurrence &ChildrenList);
HRESULT GetAllAbsPts(CATListPtrCATIPLMNavOccurrence &iPipeOccurrenceList, vector<CATLISTV(CATMathPoint)> &ivecpointsAbs);
HRESULT GetContainerAndMechPart(const CATIPLMNavReference_var &ispPLMNavRef, CATIMmiPrtContainer_var &ospContainer, CATIMmiUsePrtPart_var &ospPrtPart);
HRESULT CreateCenterLines(CATIGSMUseFactory_var &ispGSMFactory, vector<CATLISTV(CATMathPoint)> &ivecpointsAbs, CATIMmiMechanicalFeature_var &ispGsmTool);
/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();



private:
	ATOZCenterLinesCrtingDlg* _pATOZCenterLinesCrtingDlg;

	CATPathElementAgent* _pSelProdPathElemAgent;
	CATDialogAgent* _pSelPipeObjDlgAgent;

	CATIPLMNavReference_var _spRootNavRef;

	CATIPLMNavOccurrence_var _spPipeProd;
	CATIPLMNavReference_var _spPipeProdRef;

	CATOmbLifeCycleRootsBag _bag;

	vector<CATLISTV(CATMathPoint)> _vecpointsAbs;
};

//----------------------------------------------------------------------

#endif
