//===================================================================
// COPYRIGHT ATOZ 2020/05/26
//===================================================================
// CallEngineeringTemplateCmd.cpp
// Header definition of class CallEngineeringTemplateCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/05/26 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CallEngineeringTemplateCmd_H
#define CallEngineeringTemplateCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CallEngineeringTemplateDlg.h"
#include "ATOZTestData.h"

#include "ClsConfigXMLServices.h"
#include "CATPathElementAgent.h"
//system includes
#include "CATUnicodeString.h"
#include "CATCommand.h"
#include "CATBaseUnknown.h"   
#include "CATGetEnvValue.h"
#include "CATLib.h"   
#include "CATListOfCATUnicodeString.h"
#include "CATError.h" 
#include "CATListOfDouble.h"
#include "CATString.h"
#include "CATAutoConversions.h"
#include "CATUnicodeChar.h"

//AfrFoundation includes
#include "CATApplicationFrame.h"
#include "CATFrmEditor.h"
#include "CATFrmLayout.h"
#include "CATFrmWindow.h"
//Dialog includes
#include "CATDlgNotify.h"

//AfrNavigator includes
#include "CATFrmNavigGraphicWindow.h"
#include "CATNavigBox.h"

//CATIAApplicationFrame includes
#include "CATCafCenterGraph.h"
//CATPLMComponentInterfaces includes
#include "CATIPLMNavReference.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavRepInstance.h"
#include "CATPLMComponentInterfacesServices.h"
#include "CATListPtrCATIPLMNavOccurrence.h"

//CATPLMIdentificationAccess includes
#include "CATIPLMComponent.h"
#include "CATIAdpType.h"
#include "CATPLMTypeServices.h"
#include "CATListPtrCATIPLMComponent.h"
#include "CATAdpAttributeSet.h"
#include "CATPLMCoreType.h"

//CAT3DPhysicalRepInterfaces includes
#include "CATIPsiRepresentationLoadMode.h"

//CATMecModLiveUseItf includes
#include "CATIMmiUsePrtPart.h"
#include "CATIMmiPrtContainer.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATIPartRequest.h"
#include "CATIBodyRequest.h"

//CATMecModUseItf inlcudes
#include "CATIMmiUseSetFactory.h"
#include "CATIMmiUseMfBRep.h"
#include "CATIMmiUseGeometricalElement.h"

//DataCommonProtocolUse includes
#include "DataCommonProtocolServices.h"
#include "CATIUseEntity.h"

//VisualizationInterfaces includes
#include "CATPathElement.h"
#include "CATIBuildPath.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATIVisProperties.h"
#include "CATVisPropertiesValues.h"
#include "CATModifyVisProperties.h"
#include "CATI3DGeoVisu.h"
#include "CATNavigation3DViewer.h"
#include "CATViewpoint.h"
#include "CAT3DViewpoint.h"

//VisualizationController includes
#include "CATViewer.h"
#include "CAT3DViewer.h"
//VisualizationFoundation includes
#include "CAT3DManipulator.h"
//ObjectModelerNavigator includes
#include "CATIRedrawEvent.h"

//SGInfra includes
#include "CAT3DViewpoint.h"
#include "CAT3DBoundingSphere.h"
#include "CAT3DViewpoint.h"
#include "CATSupport.h"
#include "CAT3DBagRep.h"
#include "CAT4x4Matrix.h"
#include "CAT3DFixedArrowGP.h"
#include "CAT3DCustomRep.h"
#include "CAT3DPlanRep.h"

//VisualizationCore includes
#include "CATGraphicAttributeSet.h"

//Mathematics includes
#include "CATMathPointf.h"
#include "CATMathDirectionf.h"
#include "CATMathBox.h"
#include "CATMathPlane.h"
#include "CATMathVector.h"
#include "CATMath3x3Matrix.h"
#include "CAT4x4Matrix.h"
#include "CATLISTV_CATMathPlane.h"

//CATMathStream includes
#include "CATSoftwareConfiguration.h"

//SGManager includes
#include "CATHSO.h"
#include "CATVisManager.h"

//ObjectModelerSystem includes
#include "CATIAlias.h"

//KnowledgeInterfaces includes
#include "CATICkeObject.h"
#include "CATIType.h"
#include "CATAttributeInfos.h"
#include "CATListValCATAttributeInfos.h"
#include "CATICkeParm.h"
#include "CATICkeParmFactory.h"
#include "CATListValCATICkeParm.h"
#include "CATCkeObjectAttrWriteServices.h"
#include "CATCkeObjectAttrReadServices.h"
#include "CATIParmPublisher.h"
#include "CATIKweModelServices.h"
#include "CATCkeGlobalFunctions.h"
#include "CATICkeParameterSet.h"
#include "CATParmPublisherAdapter.h"
#include "CATICkeFunction.h"
#include "CATITypeDictionary.h"
#include "CATICkeInst.h"

//KnowledgeIDLItf includes
#include "CATIAParameterSet.h"
#include "CATIAParameterSets.h"

//GMModelInterfaces includes
#include "CATBody.h"

//GeometricObjects includes
#include "CATGeoFactory.h"
#include "CATPlane.h"

//GMOperatorsInterfaces includes
#include "CATICGMTopSkin.h"
#include "CATCGMCreateTopIntersect.h"
#include "CATICGMHybIntersect.h"
#include "CATICGMHybSplit.h"
#include "CATCGMCreateTopSplit.h"

//CATMecModLiveUseItf includes
#include "CATIMmiMechanicalFeature.h"
#include "CATIMmiUsePrtPart.h"
#include "CATMmiUseServicesFactory.h"
#include "CATIMmiUseCreateImport.h"
#include "CATIPartRequest.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"

//CATMecModUseItf includes
#include "CATIMmiUseDatumFactory.h"
#include "CATIMmiUseSolidInsertion.h"
#include "CATIMmiUseBasicInsertion.h"

//CATPartUseItf includes
#include "CATIPdgUsePrtFactory.h"

//MeasureGeometryInterfaces includes
#include "CATIMeasurablePlane.h"

//PLMModelerBaseInterfaces includes
#include "CATIMovable.h"

//CATGSMUseItf includes
#include "CATIGSMUseFactory.h"
#include "CATIGSMUsePlaneOffset.h"

//ProductStructureInterfaces includes
#include "CATIPLMProducts.h"
#include "CATPrdGetOccurrenceMngt.h"
#include "CATIPrdOccurrenceMngt.h"

//-----------------------------------------------------------------------
// CATPLMIntegrationAccess Framework
#include "CATIAdpEnvironment.h"
#include "CATAdpDictionaryServices.h"
#include "CATAdpAttributeSet.h"
#include "CATAdpQueryServices.h"
#include "CATAdpQueryResult.h"
#include "CATAdpIdentificationSet.h"
#include "CATLISTP_CATAdpQueryResult.h"
#include "CATIAdpPLMIdentificator.h"

// CATPLMIntegrationUse Framework
#include "CATAdpPLMQueryFilter.h"
#include "CATAdpPLMComponentsInfos.h"
#include "CATAdpPLMComponentsInfosIter.h"
#include "CATAdpPLMExtendedQueryServices.h"
#include "CATAdpPLMQueryAttributeSet.h"
#include "CATAdpPLMComponentInfos.h"
#include "CATAdpPLMComponentUniqueKey.h"
#include "CATAdpPLMQueryServices.h"
#include "CATAdpOpenParameters.h"
#include "CATAdpOpener.h"


//ProductStructureUseItf includes
#include "CATPrdFactory.h"
#include "CATIPrdReferenceFactory.h"
#include "CATIPrd3DPartReferenceFactory.h"


//PLMDictionaryNavServices Framework
#include "CATCkePLMNavPublicServices.h"
#include "CATCkePLMNavCustoAccessPublicServices.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATCkePLMNavSpecializationAccessPublicServices.h"

// System
#include "CATString.h"
#include "CATListOfCATString.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"
#include "CATSysBoolean.h"
#include "CATBaseUnknown.h"
#include "CATLISTP_CATBaseUnknown.h"

//ObjectModelerBase includes
#include "CATOmbLifeCycleRootsBag.h"

#include <iostream>
using namespace std;

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class CallEngineeringTemplateCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( CallEngineeringTemplateCmd, CATStateCommand )

public:

CallEngineeringTemplateCmd();
virtual ~CallEngineeringTemplateCmd();

/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();

HRESULT InitializeMainDialog();

//获取当前工作视图
void Get_current_viewer(CATViewer *& pCurrentViewer);

//-------------------------------------------------------------------------
// RetrievePLMType (for DS Types and Specialization Types)
//-------------------------------------------------------------------------
HRESULT RetrievePLMType(const CATUnicodeString & isPLMType, CATIType_var & ospType);

HRESULT GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	                                     const CATListOfCATUnicodeString &listOfValues,
	                                     const CATUnicodeString &iStrPLMType,
	                                     CATListPtrCATAdpQueryResult & opQueryResults);

HRESULT OpenUniquePLMComponent(const CATUnicodeString &istrPLMType,
	                           const CATUnicodeString& iPLM_ExternalIDValue,
	                           const CATUnicodeString& iV_versionValue,
	                           const IID& iIID,
	                           void **opiPLMComp,
	                           CATOmbLifeCycleRootsBag &iBag,
	                           CATBoolean iExpandAll);

HRESULT OpenPLMComponent(const CATUnicodeString &istrPLMType,
	                     const CATListOfCATString &listAttrName,
	                     const CATLISTV(CATUnicodeString) &ListAttrValue,
	                     const IID& iIID,
	                     void **opiPLMComp,
	                     CATOmbLifeCycleRootsBag &iBag,
	                     CATBoolean iExpandAll);

//显示视图
HRESULT DisplayTemplateView();

//打印属性信息
HRESULT PrintComponentAttrs(const CATIPLMComponent_var &ispPLMComponent);

//修改零件参数
HRESULT ModifyPartParams(const CATIPLMNavReference_var &ispProdRef);

//返回Part节点
HRESULT CAAMmrGetPartFromProduct(const CATIPLMNavReference_var &ispPLMNavRef,
	                             CATIPLMNavRepReference_var &ospPLMRepRef,
	                             CATIMmiMechanicalFeature_var &ospPartFeature);

HRESULT GetDirectionParamSets(const CATICkeParameterSet_var &ispParentSet, 
	                          CATLISTV(CATBaseUnknown_var) &olistParamSetObj);

//清除对话框代理
void CleanDialogAgent();

//清空所有高亮
void ClearSO();

//高亮CATPathElement对象
void HighlightPathElemObj(CATBaseUnknown* pObject);

//printf object fullpath
void PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName);

//选择机头点
void SelectHeadPointObj();

//选择机尾点
void SelectTailPointObj();

//获取当前part节点和上下文product节点
HRESULT GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart,
	                   CATIPLMNavOccurrence_var &ospParentOccurr);

//消息类型：Error、Information、Warning
int DisplayMessage(const CATString &istrMsgType,
	               const CATUnicodeString &iusMsgToDisplay,
	               const CATUnicodeString &iusDlgTitle);

//exti command
void ExitCmd();

//OK Action
void OKAction();

//获取EKL中的Action
HRESULT GetKnowledgeAction(const CATIPLMNavReference_var &ispParentNavRef,
	                       const CATUnicodeString &istrActionName,
	                       CATBaseUnknown_var &ospActionBUObj);

//get PLMComponent type
HRESULT RetrieveComponentType(const CATBaseUnknown_var &ispPLMObject,
	                          CATUnicodeString &ostrType);

HRESULT InitializeConfigData();

//获取正确的参数名称
CATUnicodeString GetRightParamName(const CATUnicodeString &istrfullParamName);

//更新特征
HRESULT CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU);

private:

	CallEngineeringTemplateDlg*   _pCallTempalteDlg;

	CATOmbLifeCycleRootsBag     _ModelBag;


	CATPathElementAgent*      _pSelPointPathElemAgent;//选择点代理
	CATDialogAgent*        _pSelHeadPointDlgAgent;//选择机头点对话框代理
	CATDialogAgent*        _pSelTailPointDlgAgent;//选择机尾点对话框代理

	CATIMmiMechanicalFeature_var   _spHeadPointObject;
	CATIMmiMechanicalFeature_var   _spTailPointObject;
	CATIPLMNavOccurrence_var       _spParentOcurr;//当前上下文的product节点

	CATUnicodeString     _strTemplateID;//模板文件product的ID
	CATUnicodeString     _strActionName;//action的名称

	CATUnicodeString     _strModelViewID;//模型显示ID
	CATUnicodeString     _strModelViewVersion;//显示模型的版本

	CATLISTV(CATUnicodeString) _listTemplateInstruction;//模板说明内容
};

//----------------------------------------------------------------------

#endif
