//===================================================================
// COPYRIGHT atoz 2020/11/09
//===================================================================
// CallUDFTool1Cmd.cpp
// Header definition of class CallUDFTool1Cmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/11/09 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CallUDFTool1Cmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
CATCreateClass( CallUDFTool1Cmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CallUDFTool1Cmd::CallUDFTool1Cmd() :
CATStateCommand ("CallUDFTool1Cmd", CATDlgEngOneShot, CATCommandModeExclusive)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, _strFeatID("")
, _strFeatVersion("")
, _pCallUDFTool1Dlg(NULL)
, _spCurrentPart(NULL_var)
, _ModelBag()
, _spFeatNavRef(NULL_var)
, _pSelPlanePathElemAgent(NULL)
, _pSelSurPathElemAgent(NULL)
, _pSelBTPlaneMDlgAgent(NULL)
, _pSelSurDlgAgent(NULL)
, _pSelBTPlaneFDlgAgent(NULL)
, _pSelXYPlaneMDlgAgent(NULL)
, _pSurObj(NULL)
, _spBUBTPlaneMObj(NULL_var)
, _spBUBTPlaneFObj(NULL_var)
, _spBUXYPlaneObj(NULL_var)
, _spXYPlane(NULL_var)
, _pSelXYPlanePathElemAgent(NULL)
, _pPathXYPlane(NULL)
, instantiated(false)
, hIUdfInstantiate(NULL_var)
{
	HRESULT rc = InitializeConfigData();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}

	rc = InitializeMainDialog();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}

	GetCurrentPart(_spCurrentPart);
	GetXY(_spCurrentPart, _spXYPlane);
	_pPathXYPlane = new CATPathElement(_spXYPlane);

	_spBUXYPlaneObj = _spXYPlane;

	CATUnicodeString strFullPath("");
	PathElementString(_pPathXYPlane, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallUDFTool1Dlg->_SelectorListXY;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	DisplayTemplateView();

	GetUDFfeat(hIUdfInstantiate);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "获取UDF模板失败!", "ERROR");
		this->RequestDelayedDestruction();
		return;
	}
	PrintOldUDFParams(hIUdfInstantiate);
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CallUDFTool1Cmd::~CallUDFTool1Cmd()
{
	_pPathXYPlane = nullptr;

	if (NULL != _pSelXYPlaneMDlgAgent)
	{
		_pSelXYPlaneMDlgAgent->RequestDelayedDestruction();
		_pSelXYPlaneMDlgAgent = NULL;
	}

	if (NULL != _pSelBTPlaneFDlgAgent)
	{
		_pSelBTPlaneFDlgAgent->RequestDelayedDestruction();
		_pSelBTPlaneFDlgAgent = NULL;
	}

	if (NULL != _pSelSurDlgAgent)
	{
		_pSelSurDlgAgent->RequestDelayedDestruction();
		_pSelSurDlgAgent = NULL;
	}

	if (NULL != _pSelBTPlaneMDlgAgent)
	{
		_pSelBTPlaneMDlgAgent->RequestDelayedDestruction();
		_pSelBTPlaneMDlgAgent = NULL;
	}

	if (NULL != _pSelXYPlanePathElemAgent)
	{
		_pSelXYPlanePathElemAgent->RequestDelayedDestruction();
		_pSelXYPlanePathElemAgent = NULL;
	}


	if (NULL != _pSelSurPathElemAgent)
	{
		_pSelSurPathElemAgent->RequestDelayedDestruction();
		_pSelSurPathElemAgent = NULL;
	}

	if (NULL != _pSelPlanePathElemAgent)
	{
		_pSelPlanePathElemAgent->RequestDelayedDestruction();
		_pSelPlanePathElemAgent = NULL;
	}

	if (NULL != _pCallUDFTool1Dlg)
	{
		_pCallUDFTool1Dlg->RequestDelayedDestruction();
		_pCallUDFTool1Dlg = NULL;
	}


}

HRESULT CallUDFTool1Cmd::InitializeConfigData()
{
	CATUnicodeString strInstallPath("");
	ClsConfigXMLServices::Get_ComputeDataExePath(strInstallPath);
	if (CATUnicodeString("") == strInstallPath) return E_FAIL;

	CATUnicodeString strProjectConfigPath = strInstallPath + "bin\\\ATOZ\\CAAEKLConfig";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		cout << "找不到CAAEKLConfig配置文件夹!" << endl;
		return E_FAIL;
	}

	const char* pxmlfilePath = CATFindPath("CAAPCConfig.xml", strProjectConfigPath);
	if (NULL == pxmlfilePath)
	{
		cout << "找不到CAAPCConfig.xml配置文件!" << endl;
		return E_FAIL;
	}

	CATUnicodeString strXMLFilePath = pxmlfilePath;
	HRESULT rc = ClsConfigXMLServices::GetCUPSConfigData(strXMLFilePath, "NWH", _strFeatID, _strFeatVersion);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "读取CAAEKLConfig.xml配置文件失败!", "ERROR");
		cout << "读取CAAEKLConfig.xml配置文件失败!" << endl;
		return E_FAIL;
	}

	return S_OK;
}

//消息类型：Error、Information、Warning
int CallUDFTool1Cmd::DisplayMessage(const CATString &istrMsgType,
	const CATUnicodeString &iusMsgToDisplay,
	const CATUnicodeString &iusDlgTitle)
{

	int RetUserReply = 0;

	CATDlgStyle Dlgstyle;
	CATUnicodeString usDlgTitle = "";

	if (istrMsgType == "Error")
	{
		Dlgstyle = CATDlgNfyError | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Error";
	}
	else if (istrMsgType == "Information")
	{
		Dlgstyle = CATDlgNfyInformation | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Information";
	}
	else if (istrMsgType == "Warning")
	{
		Dlgstyle = CATDlgNfyWarning | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Warning";
	}

	if (iusDlgTitle != "")usDlgTitle = iusDlgTitle;

	CATDlgNotify* pDlgNotify = new CATDlgNotify((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(), istrMsgType, Dlgstyle);
	if (!pDlgNotify) return 0;

	RetUserReply = pDlgNotify->DisplayBlocked(iusMsgToDisplay, usDlgTitle); // Get the User selected button
	return RetUserReply;
}

HRESULT CallUDFTool1Cmd::InitializeMainDialog()
{
	_pCallUDFTool1Dlg = new CallUDFTool1Dlg((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
		"CallUDFDlg");
	_pCallUDFTool1Dlg->Build();


	CATNavigation3DViewer* p3DViewer = _pCallUDFTool1Dlg->_Nav3DViewerModel;
	if (NULL != p3DViewer)
	{
		p3DViewer->SetBackgroundColor(0.235294f, 0.4f, 0.501961f);
	}

	_pCallUDFTool1Dlg->_SelectorListBtPlaneM->SetLine("No Selection");
	int ArraySel[1] = { 0 };
	_pCallUDFTool1Dlg->_SelectorListBtPlaneM->SetSelect(ArraySel, 1);

	_pCallUDFTool1Dlg->_SelectorListSur->SetLine("No Selection");
	_pCallUDFTool1Dlg->_SelectorListBtPlaneF->SetLine("No Selection");
	_pCallUDFTool1Dlg->_SelectorListXY->SetLine("No Selection");


	/*_pCallUDFTool1Dlg->_SpinnerPlane1->SetValue(3.85e+006 / 1000.0);
	_pCallUDFTool1Dlg->_SpinnerPlane2->SetValue(3.8e+006 / 1000.0);
	_pCallUDFTool1Dlg->_SpinnerPlane3->SetValue(3.75e+006 / 1000.0);
	_pCallUDFTool1Dlg->_SpinnerPlane4->SetValue(3.7e+006 / 1000.0);*/
	
	_pCallUDFTool1Dlg->_LabelLog->SetIconName("I_NWHLog");
	_pCallUDFTool1Dlg->SetVisibility(CATDlgShow);
	return S_OK;
}

HRESULT CallUDFTool1Cmd::GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart)
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL == pFrmEditor) return E_FAIL;

	CATPathElement& CurrentElemPath = pFrmEditor->GetUIActiveObject();
	CATBaseUnknown* pCurrentObject = CurrentElemPath.FindElement(IID_CATIMmiUsePrtPart);
	if (NULL != pCurrentObject)
	{
		ospPrtPart = pCurrentObject;

	}

	return S_OK;
}

HRESULT CallUDFTool1Cmd::DisplayTemplateView()
{
	//判断项目中是否存在物料
	CATLISTV(CATString)        listAttrName;
	CATLISTV(CATUnicodeString) listAttrValue;
	listAttrName.Append("PLM_ExternalID");
	listAttrName.Append("revision");
	listAttrName.Append("V_usage");

	listAttrValue.Append(_strFeatID);
	listAttrValue.Append(_strFeatVersion);
	listAttrValue.Append("3DPart");
	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	GetPLMObjectsFromAttrAndFromType(listAttrName, listAttrValue, "VPMReference", listQueryResult);
	if (listQueryResult.Size() > 0)
	{
		CATBoolean authoringMode = TRUE;
		CATIPLMNavReference* piProductRef = NULL;
		OpenPLMComponent("VPMReference", listAttrName, listAttrValue,
			IID_CATIPLMNavReference, (void**)&piProductRef, _ModelBag, authoringMode);
		if (NULL != piProductRef)
		{
			//CATIPLMComponent_var spPLMComponent = piProductRef;
			//if (NULL_var != spPLMComponent)
			//{
			//	PrintComponentAttrs(spPLMComponent);
			//}

			CATIPrdOccurrenceMngt* piOccurrMngt = NULL;
			if (SUCCEEDED(CATPrdGetOccurrenceMngt(piOccurrMngt)) && piOccurrMngt)
			{
				CATIPLMNavOccurrence_var spPrdOccurr = NULL_var;
				piOccurrMngt->GetOrCreateRootOccurrence(piProductRef, spPrdOccurr);
				if (NULL_var != spPrdOccurr)
				{
					CATFrmEditor * pEditor = CATFrmEditor::GetCurrentEditor();
					CATVisManager * pVisuManager = CATVisManager::GetVisManager();
					CATCommand * pCommandSelector = (CATCommand*)pEditor->GetCommandSelector();
					list<IID> ListIVisu3d;
					IID visu3d = IID_CATI3DGeoVisu;
					ListIVisu3d.fastadd(&visu3d);
					CATPathElement*  pRootObjectPath = new CATPathElement(spPrdOccurr);
					CATViewpoint*  pModelViewPoint = (CATViewpoint*)&(_pCallUDFTool1Dlg->_Nav3DViewerModel->GetMain3DViewpoint());
					HRESULT rc = pVisuManager->AttachTo(pRootObjectPath, pModelViewPoint, ListIVisu3d, pCommandSelector);

					_pCallUDFTool1Dlg->_Nav3DViewerModel->Draw();
					_pCallUDFTool1Dlg->_Nav3DViewerModel->Reframe();
				}

				piOccurrMngt->Release(); piOccurrMngt = NULL;
			}
			_spFeatNavRef = piProductRef;
			piProductRef->Release(); piProductRef = NULL;
		}
	}

	return S_OK;
}

HRESULT CallUDFTool1Cmd::GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	const CATListOfCATUnicodeString &listOfValues,
	const CATUnicodeString &iStrPLMType,
	CATListPtrCATAdpQueryResult & opQueryResults)
{
	HRESULT hr = S_OK;
	//cout << "   GetPLMObjectsFromAttrAndFromType " << endl;

	if ((0 == listOfAttribute.Size()) || (0 == listOfValues.Size())) return E_INVALIDARG;
	if (listOfAttribute.Size() != listOfValues.Size()) return E_INVALIDARG;
	if (0 < opQueryResults.Size())return E_INVALIDARG;


	int iListSize = listOfAttribute.Size();

	CATAdpAttributeSet iAttributeSet;
	//cout << "   Build an Attribute set with inputs from user, for query into db" << endl;
	int i = 1;
	while ((i <= iListSize) && (SUCCEEDED(hr)))
	{
		CATUnicodeString Name = listOfAttribute[i].CastToCharPtr();
		const CATString AttributeINPUT = CATCkePLMNavPublicServices::RetrieveBasicAttributeNameFromPreviousOne(NULL_var, Name).CastToCharPtr();
		CATUnicodeString AttrValue = listOfValues[i];

		hr = iAttributeSet.AddAttribute(AttributeINPUT, AttrValue);
		i++;
	}

	CATIType_var spTypeObj = NULL_var;
	hr = RetrievePLMType(iStrPLMType, spTypeObj);
	if (FAILED(hr) || (NULL_var == spTypeObj))
	{
		cout << "ERROR:ClsPLMUtilities::GetPLMObjectsFromAttrAndFromType()-NULL_var == spTypeObj" << endl;
		return E_FAIL;
	}


	hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spTypeObj,
		iAttributeSet,
		opQueryResults);

	return hr;
}

HRESULT CallUDFTool1Cmd::OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATListOfCATString &listAttrName,
	const CATLISTV(CATUnicodeString) &ListAttrValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll)
{
	HRESULT hr = S_OK;
	if (CATUnicodeString("") == istrPLMType) return E_FAIL;
	if (0 == listAttrName.Size()) return E_FAIL;
	if (0 == ListAttrValue.Size()) return E_FAIL;

	int iListSize = listAttrName.Size();

	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	hr = GetPLMObjectsFromAttrAndFromType(listAttrName, ListAttrValue, istrPLMType, listQueryResult);
	if (FAILED(hr) || (0 == listQueryResult.Size()))
	{

		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-0 == listQueryResult.Size()" << endl;
		return hr;
	}

	CATIAdpPLMIdentificator* piAdpPLMIdentificator = NULL;
	listQueryResult[1]->GetIdentifier(piAdpPLMIdentificator);
	if (NULL == piAdpPLMIdentificator)
	{
		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-NULL == piAdpPLMIdentificator" << endl;
		return E_FAIL;
	}


	if (TRUE == iExpandAll)
	{
		CATAdpOpenParameters params_Auth(CATAdpExpandParameters::Authoring);
		CATAdpOpener opener_Auth(iBag, params_Auth);
		// 5.2. Open the Retrieved Component by using CATAdpOpener
		hr = opener_Auth.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	else
	{
		CATAdpOpenParameters params_Nav(CATAdpExpandParameters::OneLevelRepresentations);
		CATAdpOpener opener_Nav(iBag, params_Nav);
		hr = opener_Nav.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	piAdpPLMIdentificator->Release();
	piAdpPLMIdentificator = NULL;

	return S_OK;
}

HRESULT CallUDFTool1Cmd::RetrievePLMType(const CATUnicodeString & isPLMType,
	CATIType_var & ospType)
{
	HRESULT rc = E_INVALIDARG;
	if (isPLMType != "")
	{
		// For DS type
		rc = CATCkePLMNavPublicServices::RetrieveKnowledgeType(isPLMType, ospType);
		// For Specialization Type
		if (FAILED(rc))  rc = CATCkePLMNavSpecializationAccessPublicServices::RetrieveSpecializationType(isPLMType, ospType);
	}
	return rc;
}

void CallUDFTool1Cmd::ClearSO()
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL != pFrmEditor)
	{
		CATHSO* pHSO = pFrmEditor->GetHSO();
		pHSO->Empty();
	}
}
//高亮CATPathElement对象
void CallUDFTool1Cmd::HighlightPathElemObj(CATBaseUnknown* pObject)
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL != pFrmEditor)
	{
		CATHSO* pHSO = pFrmEditor->GetHSO();
		pHSO->AddElements(pObject);
		pHSO->EndAddElements();
	}
}

//void CallUDFTool1Cmd::PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName)
//{
//
//	oPathName = "";
//	if (NULL != ipPath)
//	{
//		int sizeOfThePath = ipPath->GetSize();
//
//		for (int i = sizeOfThePath - 1; i >= 0; i--)
//		{
//			CATBaseUnknown * pElt = (*ipPath)[i];
//			if (NULL != pElt)
//			{
//				CATIAlias * pIAliasOnElt = NULL;
//				HRESULT rc = pElt->QueryInterface(IID_CATIAlias, (void**)&pIAliasOnElt);
//				if (SUCCEEDED(rc))
//				{
//					CATUnicodeString Name = pIAliasOnElt->GetAlias();
//					oPathName.Append(Name);
//
//					if (i > 0)
//					{
//						oPathName.Append("/"); ;
//					}
//
//					pIAliasOnElt->Release();
//					pIAliasOnElt = NULL;
//				}
//			}
//		}
//	}
//}

//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void CallUDFTool1Cmd::BuildGraph()
{
	_pSelPlanePathElemAgent = new CATPathElementAgent("SelectPlane");
	_pSelPlanePathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelPlanePathElemAgent->AddElementType("CATIMfPlane");

	_pSelSurPathElemAgent = new CATPathElementAgent("SelectSur");
	_pSelSurPathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngMultiAcquisitionSelModes | CATDlgEngMultiAcquisitionSelModes | CATDlgEngMultiAcquisitionCtrl | CATDlgEngMultiAcquisitionUserCtrl);
	_pSelSurPathElemAgent->AddElementType(IID_CATICldBody);

	_pSelXYPlanePathElemAgent = new CATPathElementAgent("SelectXY");
	_pSelXYPlanePathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelXYPlanePathElemAgent->AddElementType("CATIMfPlane");
	
	

	_pSelBTPlaneMDlgAgent = new CATDialogAgent("Bottom Plane M");
	_pSelBTPlaneMDlgAgent->AcceptOnNotify(_pCallUDFTool1Dlg->_SelectorListBtPlaneM,
		_pCallUDFTool1Dlg->_SelectorListBtPlaneM->GetListSelectNotification());

	_pSelSurDlgAgent = new CATDialogAgent("Di Xing S");
	_pSelSurDlgAgent->AcceptOnNotify(_pCallUDFTool1Dlg->_SelectorListSur,
		_pCallUDFTool1Dlg->_SelectorListSur->GetListSelectNotification());

	_pSelBTPlaneFDlgAgent = new CATDialogAgent("Bottom Plane F");
	_pSelBTPlaneFDlgAgent->AcceptOnNotify(_pCallUDFTool1Dlg->_SelectorListBtPlaneF,
		_pCallUDFTool1Dlg->_SelectorListBtPlaneF->GetListSelectNotification());

	_pSelXYPlaneMDlgAgent = new CATDialogAgent("CenterLineDlg");
	_pSelXYPlaneMDlgAgent->AcceptOnNotify(_pCallUDFTool1Dlg->_SelectorListXY,
		_pCallUDFTool1Dlg->_SelectorListXY->GetListSelectNotification());

	CATDialogState * SelBTPlaneMState = GetInitialState("请选择面板底平面");
	SelBTPlaneMState->AddDialogAgent(_pSelPlanePathElemAgent);
	SelBTPlaneMState->AddDialogAgent(_pSelSurDlgAgent);
	SelBTPlaneMState->AddDialogAgent(_pSelBTPlaneFDlgAgent);
	SelBTPlaneMState->AddDialogAgent(_pSelXYPlaneMDlgAgent);

	CATDialogState * SelSurState = AddDialogState("请选择地形面");
	SelSurState->AddDialogAgent(_pSelSurPathElemAgent);
	SelSurState->AddDialogAgent(_pSelBTPlaneMDlgAgent);
	SelSurState->AddDialogAgent(_pSelBTPlaneFDlgAgent);
	SelSurState->AddDialogAgent(_pSelXYPlaneMDlgAgent);

	CATDialogState * SelBTPlaneFState = AddDialogState("请选择防浪墙底平面");
	SelBTPlaneFState->AddDialogAgent(_pSelPlanePathElemAgent);
	SelBTPlaneFState->AddDialogAgent(_pSelBTPlaneMDlgAgent);
	SelBTPlaneFState->AddDialogAgent(_pSelSurDlgAgent);
	SelBTPlaneFState->AddDialogAgent(_pSelXYPlaneMDlgAgent);

	CATDialogState * SelXYPlaneState = AddDialogState("请选择XY平面");
	SelXYPlaneState->AddDialogAgent(_pSelXYPlanePathElemAgent);
	SelXYPlaneState->AddDialogAgent(_pSelBTPlaneMDlgAgent);
	SelXYPlaneState->AddDialogAgent(_pSelSurDlgAgent);
	SelXYPlaneState->AddDialogAgent(_pSelBTPlaneFDlgAgent);


	//SelBTPlaneMState
	AddTransition(SelBTPlaneMState, SelBTPlaneMState,
		IsOutputSetCondition(_pSelPlanePathElemAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::SelectBTPlaneMObj));

	AddTransition(SelBTPlaneMState, SelSurState,
		IsOutputSetCondition(_pSelSurDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	AddTransition(SelBTPlaneMState, SelBTPlaneFState,
		IsOutputSetCondition(_pSelBTPlaneFDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	AddTransition(SelBTPlaneMState, SelXYPlaneState,
		IsOutputSetCondition(_pSelXYPlaneMDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));


	//SelSurState
	AddTransition(SelSurState, SelSurState,
		IsOutputSetCondition(_pSelSurPathElemAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::SelectSurObjs));

	AddTransition(SelSurState, SelBTPlaneMState,
		IsOutputSetCondition(_pSelBTPlaneMDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	AddTransition(SelSurState, SelBTPlaneFState,
		IsOutputSetCondition(_pSelBTPlaneFDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	AddTransition(SelSurState, SelXYPlaneState,
		IsOutputSetCondition(_pSelXYPlaneMDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	//SelBTPlaneFState
	AddTransition(SelBTPlaneFState, SelBTPlaneFState,
		IsOutputSetCondition(_pSelPlanePathElemAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::SelectBTPlaneFObj));

	AddTransition(SelBTPlaneFState, SelBTPlaneMState,
		IsOutputSetCondition(_pSelBTPlaneMDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	AddTransition(SelBTPlaneFState, SelSurState,
		IsOutputSetCondition(_pSelSurDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	AddTransition(SelBTPlaneFState, SelXYPlaneState,
		IsOutputSetCondition(_pSelXYPlaneMDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));
	
	//SelXYPlaneState
	AddTransition(SelXYPlaneState, SelXYPlaneState,
		IsOutputSetCondition(_pSelXYPlanePathElemAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::SelectXYObj));

	AddTransition(SelXYPlaneState, SelBTPlaneMState,
		IsOutputSetCondition(_pSelBTPlaneMDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	AddTransition(SelXYPlaneState, SelSurState,
		IsOutputSetCondition(_pSelSurDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));

	AddTransition(SelXYPlaneState, SelBTPlaneFState,
		IsOutputSetCondition(_pSelBTPlaneFDlgAgent),
		Action((ActionMethod)&CallUDFTool1Cmd::CleanDialogAgent));


	//click Wndclose buttion
	AddAnalyseNotificationCB(_pCallUDFTool1Dlg,
		_pCallUDFTool1Dlg->GetWindCloseNotification(),
		(CATCommandMethod)&CallUDFTool1Cmd::ExitCmd, NULL);
	//click cancel button
	AddAnalyseNotificationCB(_pCallUDFTool1Dlg,
		_pCallUDFTool1Dlg->GetDiaCANCELNotification(),
		(CATCommandMethod)&CallUDFTool1Cmd::ExitCmd, NULL);

	//click OK button
	AddAnalyseNotificationCB(_pCallUDFTool1Dlg,
		_pCallUDFTool1Dlg->GetDiaOKNotification(),
		(CATCommandMethod)&CallUDFTool1Cmd::ClickOK, NULL);


	//click preview button
	AddAnalyseNotificationCB(_pCallUDFTool1Dlg,
		_pCallUDFTool1Dlg->GetDiaPREVIEWNotification(),
		(CATCommandMethod)&CallUDFTool1Cmd::PreView, NULL);
}

void CallUDFTool1Cmd::SelectBTPlaneMObj(void* idata)
{
	CATPathElement* pPathElem = _pSelPlanePathElemAgent->GetValue();
	CATBaseUnknown* pBaseUnknown = _pSelPlanePathElemAgent->GetElementValue();
	_pSelPlanePathElemAgent->InitializeAcquisition();

	_spBUBTPlaneMObj = pBaseUnknown;

	CATUnicodeString strFullPath("");
	PathElementString(pPathElem, strFullPath);
	//GetElementName(pPathElem, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallUDFTool1Dlg->_SelectorListBtPlaneM;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL == _pSurObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListSur->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spBUBTPlaneFObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListBtPlaneF->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spBUXYPlaneObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListXY->SetSelect(ArraySel, 1);
	}
}

void CallUDFTool1Cmd::SelectSurObjs(void* idata)
{
	//CATPathElement* pPathElem = _pSelPlanePathElemAgent->GetValue();
	_pSurObj = _pSelSurPathElemAgent->GetListOfValues();
	_pSelSurPathElemAgent->InitializeAcquisition();

	CATUnicodeString strFullPath("");
	const int SIZE = _pSurObj->GetSize();
	if (0 == SIZE)
	{
		cout << "地形面 0 == SIZE" << endl;
	}
	
	CATDlgSelectorList* pDlgSelList = _pCallUDFTool1Dlg->_SelectorListSur;	
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		
		for (int i = 0; i < SIZE; i++)
		{
			CATPathElement * pPath = (CATPathElement*)(*_pSurObj)[i];
			PathElementString(pPath, strFullPath);
			//GetElementName(pPath, strFullPath);
			pDlgSelList->SetLine(strFullPath);
		}
	}

	

	if (NULL_var == _spBUBTPlaneMObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListBtPlaneM->SetSelect(ArraySel, 1);
	}
	else if (NULL == _spBUBTPlaneFObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListBtPlaneF->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spBUXYPlaneObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListXY->SetSelect(ArraySel, 1);
	}
}

void CallUDFTool1Cmd::SelectBTPlaneFObj(void* idata)
{
	CATPathElement* pPathElem = _pSelPlanePathElemAgent->GetValue();
	CATBaseUnknown* pBaseUnknown = _pSelPlanePathElemAgent->GetElementValue();
	_pSelPlanePathElemAgent->InitializeAcquisition();

	_spBUBTPlaneFObj = pBaseUnknown;

	CATUnicodeString strFullPath("");
	PathElementString(pPathElem, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallUDFTool1Dlg->_SelectorListBtPlaneF;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL_var == _spBUBTPlaneMObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListBtPlaneM->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pSurObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListSur->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spBUXYPlaneObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListXY->SetSelect(ArraySel, 1);
	}
}

void CallUDFTool1Cmd::SelectXYObj(void* idata)
{
	CATPathElement* pPathElem = _pSelXYPlanePathElemAgent->GetValue();
	CATBaseUnknown* pBaseUnknown = _pSelXYPlanePathElemAgent->GetElementValue();
	_pSelXYPlanePathElemAgent->InitializeAcquisition();

	if(NULL_var)
	_spBUXYPlaneObj = pBaseUnknown;

	CATUnicodeString strFullPath("");
	PathElementString(pPathElem, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallUDFTool1Dlg->_SelectorListXY;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL_var == _spBUBTPlaneMObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListBtPlaneM->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pSurObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListSur->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spBUBTPlaneFObj)
	{
		int ArraySel[1] = { 0 };
		_pCallUDFTool1Dlg->_SelectorListBtPlaneF->SetSelect(ArraySel, 1);
	}
}

void GetXY(CATIMmiUsePrtPart_var &spCurrentPart, CATIMmiMechanicalFeature_var &ospXYPlane)
{

	CATListValCATIMmiMechanicalFeature_var ListOfPlanes;
	spCurrentPart->RetrieveReferencePlanes(ListOfPlanes);
	ospXYPlane = ListOfPlanes[1];

}

void CallUDFTool1Cmd::CleanDialogAgent()
{
	if (_pSelBTPlaneMDlgAgent->IsOutputSet())
	{
		_pSelBTPlaneMDlgAgent->InitializeAcquisition();
		_pCallUDFTool1Dlg->_SelectorListSur->ClearSelect();
		_pCallUDFTool1Dlg->_SelectorListBtPlaneF->ClearSelect();
		_pCallUDFTool1Dlg->_SelectorListXY->ClearSelect();
	}
	if (_pSelSurDlgAgent->IsOutputSet())
	{
		_pSelSurDlgAgent->InitializeAcquisition();
		_pCallUDFTool1Dlg->_SelectorListBtPlaneM->ClearSelect();
		_pCallUDFTool1Dlg->_SelectorListBtPlaneF->ClearSelect();
		_pCallUDFTool1Dlg->_SelectorListXY->ClearSelect();
	}
	if (_pSelBTPlaneFDlgAgent->IsOutputSet())
	{
		_pSelBTPlaneFDlgAgent->InitializeAcquisition();
		_pCallUDFTool1Dlg->_SelectorListBtPlaneM->ClearSelect();
		_pCallUDFTool1Dlg->_SelectorListSur->ClearSelect();
		_pCallUDFTool1Dlg->_SelectorListXY->ClearSelect();
	}
	if (_pSelXYPlaneMDlgAgent->IsOutputSet())
	{
		_pSelXYPlaneMDlgAgent->InitializeAcquisition();
		_pCallUDFTool1Dlg->_SelectorListBtPlaneM->ClearSelect();
		_pCallUDFTool1Dlg->_SelectorListSur->ClearSelect();
		_pCallUDFTool1Dlg->_SelectorListBtPlaneF->ClearSelect();
	}
}

void CallUDFTool1Cmd::ExitCmd(void* idata)
{
	ExecuteUndoAtEnd();
	this->RequestDelayedDestruction();
	return;
}


HRESULT CallUDFTool1Cmd::GetUDFContainerFromDB(CATOmbLifeCycleRootsBag &iobag,
	CATIPLMNavReference_var &ispFeatNavRef,
	CATIPLMComponent *&opiPLMCompOnFeatRef,
	CATIMmiPrtContainer *&opIPrtContOnCAAUdfLoft)
{
	HRESULT rc = S_OK;

	//QI
	CATIPLMComponent_var spiPLMCompOnFeatRef = NULL_var;
	CATIPLMNavReference* pFeatNavRef = NULL;
	pFeatNavRef = (CATIPLMNavReference*)ispFeatNavRef;
	if (NULL == pFeatNavRef)
	{
		cout << "NULL == pFeatNavRef" << endl;
		return E_FAIL;
	}

	CATIPLMComponent* piPLMCompOnFeatRef = NULL;
	rc = pFeatNavRef->QueryInterface(IID_CATIPLMComponent, (void**)&piPLMCompOnFeatRef);
	if (FAILED(rc) || NULL == piPLMCompOnFeatRef)
	{
		cout << "NULL == opiPLMCompOnFeatRef" << endl;
		return E_FAIL;
	}


	opiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	opiPLMCompOnFeatRef->AddRef();

	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;

	/////////////////////////////////////////////////////////////////////////////////////

	//3DShape

	CATPLMCoreType coreType = CATPLMCoreType::PLMCoreRepInstance;
	CATListPtrCATIPLMNavEntity ChildrenList;

	rc = pFeatNavRef->ListChildren(ChildrenList, 1, &coreType);
	if (ChildrenList.Size() == 0)
	{
		DisplayMessage("Warning", "ChildrenList.Size() == 0", "警告");
		return E_FAIL;
	}


	CATIPLMNavEntity *piNavEntity = ChildrenList[1];
	if (NULL == piNavEntity)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piNavEntity is NULL!" << endl;
		return E_FAIL;
	}

	CATIPLMNavRepInstance * piPrdObjOnRepInst = NULL;
	rc = piNavEntity->QueryInterface(IID_CATIPLMNavRepInstance, (void**)&piPrdObjOnRepInst);
	if (FAILED(rc) || NULL == piPrdObjOnRepInst)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piPrdObjOnRepInst is NULL!" << endl;
		return E_FAIL;
	}


	CATIPLMNavRepReference* pi3DShapeRepRefer = NULL;
	rc = piPrdObjOnRepInst->GetRepReferenceInstanceOf(pi3DShapeRepRefer);
	if (FAILED(rc) || NULL == pi3DShapeRepRefer)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - pi3DShapeRepRefer is NULL!" << endl;
		return E_FAIL;
	}
	piPrdObjOnRepInst->Release();
	piPrdObjOnRepInst = NULL;


	CATIPLMNavRepReference_var spi3DShapeRepRefer(pi3DShapeRepRefer);
	pi3DShapeRepRefer->Release();
	pi3DShapeRepRefer = NULL;

	// edit mode is no longer default
	CATIPsiRepresentationLoadMode_var spRepLoadMode = spi3DShapeRepRefer;
	if (NULL_var == spRepLoadMode)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - spRepLoadMode is NULL!" << endl;
		return E_FAIL;
	}
	rc = spRepLoadMode->ChangeLoadingMode(CATIPsiRepresentationLoadMode::EditMode);
	if (FAILED(rc))
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ChangeLoadingMode is failed!" << endl;
	}

	//container
	CATIMmiPrtContainer *pIPrtContOnCAAUdfLoft = NULL;
	rc = spi3DShapeRepRefer->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pIPrtContOnCAAUdfLoft);
	if (FAILED(rc) || (NULL_var == pIPrtContOnCAAUdfLoft))
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - RetrieveApplicativeContainer is failed!" << endl;
		return E_FAIL;
	}
	opIPrtContOnCAAUdfLoft = pIPrtContOnCAAUdfLoft;
	opIPrtContOnCAAUdfLoft->AddRef();

	// 3-bis Lock the Representation Reference containing the reference to instantiate
	//CATOmbLifeCycleRootsBag Bag ;
	rc = iobag.InsertRoot(opiPLMCompOnFeatRef);
	if (FAILED(rc))
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ibag.InsertRoot is failed!" << endl;
	}

	ULONG iL = pIPrtContOnCAAUdfLoft->Release();
	pIPrtContOnCAAUdfLoft = NULL;

	piNavEntity->Release();
	piNavEntity = NULL;

	return S_OK;
}



HRESULT CallUDFTool1Cmd::OKAction()
{
	if (NULL_var == _spBUBTPlaneMObj)
	{
		DisplayMessage("Warning", "请选择面板底面平面!", "警告");

		return E_FAIL;
	}
	if (NULL == _pSurObj)
	{
		DisplayMessage("Warning", "请选择地形面!", "警告");
		return E_FAIL;
	}
	if (NULL_var == _spBUBTPlaneFObj)
	{
		DisplayMessage("Warning", "请选择防浪墙底平面!", "警告");
		return E_FAIL;
	}
	if (NULL_var == _spBUXYPlaneObj)
	{
		DisplayMessage("Warning", "请选择xy平面!", "警告");
		return E_FAIL;
	}
	HRESULT rc = E_FAIL;
	double para[] = {0, 0, 0, 0};
	rc = GetParams(para);
	if (FAILED(rc))
	{
		cout << "Error:GetParams failed!" << endl;
		return E_FAIL;
	}


	if (NULL_var == _spFeatNavRef)
	{
		cout << "Error:NULL_var == _spFeatNavRef" << endl;
		return E_FAIL;
	}

	
	rc = UDFImpInstantiating2(_spCurrentPart, hIUdfInstantiate, para);


	//更新模型
	

	if (FAILED(_ModelBag.RemoveAll()))
	{
		cout << "_ModelBag" << endl;
	}

	return rc;

}

HRESULT CallUDFTool1Cmd::UDFImpInstantiating2(CATBaseUnknown_var &ispBUCurrentPartRef, CATIUdfInstantiate_var &hIUdfInstantiate, double para[])
{
	CATIMmiMechanicalFeature_var spGsmTool(NULL_var);
	CAAGsiCreateGeometricFeatureSets(_spCurrentPart, "趾板定线", spGsmTool);

	CATListValCATBaseUnknown_var spEntitiesToCopy;

	HRESULT rc = E_FAIL;
	CATBaseUnknown* pBUBTPlaneMObj = (CATBaseUnknown*)_spBUBTPlaneMObj;
	CATBaseUnknown* pBUBTPlanefObj = (CATBaseUnknown*)_spBUBTPlaneFObj;
	CATBaseUnknown* pBUXYPlaneMObj = (CATBaseUnknown*)_spBUXYPlaneObj;
	if (NULL == pBUBTPlaneMObj || NULL == pBUBTPlanefObj || NULL == pBUXYPlaneMObj)
	{
		DisplayMessage("Warning", "Cast failed", "警告");
		return E_FAIL;
	}

	CATPathElement * pPathInput1 = new CATPathElement(pBUBTPlaneMObj);
	CATPathElement * pPathInput3 = new CATPathElement(pBUBTPlanefObj);
	CATPathElement * pPathInput4 = new CATPathElement(pBUXYPlaneMObj);

	const int SIZE = _pSurObj->GetSize();
	if (0 == SIZE)
	{
		DisplayMessage("Warning", "地形面 0 == SIZE", "警告");
	}

	//CATDlgProgress * pDlgProgress = _pCallUDFTool1Dlg->_pDlgProgress;
	//CATDlgProgress * pDlgProgress = new CATDlgProgress((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(), "Progress");
	_pCallUDFTool1Dlg->_pDlgProgress->SetRange(0, SIZE);
	_pCallUDFTool1Dlg->_pDlgProgress->SetStep(1);
	_pCallUDFTool1Dlg->_pDlgProgress->SetPos(0);

	for (int i = 0; i < SIZE; i++)
	{
		CATUnicodeString NewName("");
		CATPathElement * pPathInput2 = (CATPathElement*)(*_pSurObj)[i];

		/*PathElementString(pPathInput2,NewName);
		NewName = GetRightParamName2(NewName);*/

		//GetElementName(pPathInput2, NewName); //no result
		PathElementString(pPathInput2, NewName, TRUE);
		
		//cout << "PathElementString" << endl;
		cout << NewName << endl;
		
		//setDestination
		CATBaseUnknown_var spPartRequestBU = ispBUCurrentPartRef;
		if (NULL_var == spPartRequestBU)
		{
			cout << "Error:NULL_var == spPartRequestBU" << endl;
			return E_FAIL;
		}
		CATBaseUnknown* pPartRequestBU = (CATBaseUnknown*)spPartRequestBU;
		if (NULL == pPartRequestBU)
		{
			cout << "Error:ATOZRDCSICITUDFImportCmd::OutRibUDFImp() - pPartRequestBU is NULL!" << endl;
			return E_FAIL;
		}
		CATPathElement PartRequestPath(pPartRequestBU);

		CATPathElement *pUIactivePath(NULL);
		CATBaseUnknown_var spDestBU(NULL_var);
		rc = hIUdfInstantiate->SetDestinationPath(&PartRequestPath, pUIactivePath, spDestBU);
		if (FAILED(rc))
		{
			cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - SetDestinationPath() is failed!" << endl;
			return E_FAIL;
		}

		if (NULL != pUIactivePath)
		{
			pUIactivePath->Release();
			pUIactivePath = NULL;
		}


		rc = hIUdfInstantiate->SetNewInput(1, pPathInput1);
		if (FAILED(rc))
		{
			cout << "ERROR:SetNewInput1" << endl;
			return E_FAIL;
		}
		rc = hIUdfInstantiate->SetNewInput(2, pPathInput2);
		if (FAILED(rc))
		{
			cout << "ERROR:SetNewInput2" << endl;
			return E_FAIL;
		}
		rc = hIUdfInstantiate->SetNewInput(3, pPathInput3);
		if (FAILED(rc))
		{
			cout << "ERROR:SetNewInput3" << endl;
			return E_FAIL;
		}
		rc = hIUdfInstantiate->SetNewInput(4, pPathInput4);
		if (FAILED(rc))
		{
			cout << "ERROR:SetNewInput4" << endl;
			return E_FAIL;
		}
		rc = ModifyPartParams2(hIUdfInstantiate, para);
		if (FAILED(rc))
		{
			cout << "ERROR:ModifyPartParams2" << endl;
			return E_FAIL;
		}

		rc = hIUdfInstantiate->Instantiate(NULL_var);
		if (FAILED(rc))
		{
			cout << "ERROR:Instantiate" << endl;
			return E_FAIL;
		}

		CATBaseUnknown_var spSecondInstance = NULL_var;
		
		spSecondInstance = hIUdfInstantiate->GetInstantiated(hIUdfInstantiate);
		if (NULL_var == spSecondInstance)
		{
			cout << "NULL_var == spSecondInstance" << endl;
		}
		//cout << "获取到的地形线类型为" << spSecondInstance->GetImpl()->IsA() << endl; UdfFeature

		rc = hIUdfInstantiate->EndInstantiate();
		if (FAILED(rc))
		{
			cout << "ERROR:EndInstantiate" << endl;
			return E_FAIL;
		}

		CATIAlias_var spAliasOnInstance = spSecondInstance;
		if (NULL_var != spSecondInstance)
		{
			spAliasOnInstance->SetAlias(NewName);
		}

		CAAUpdateObject(spSecondInstance);
		
		//set color
		CATIUdfInstantiate_var spUdfObject = spSecondInstance;
		if (NULL_var != spUdfObject)
			SetSpecLineObjColor(spUdfObject, i);
		

		spEntitiesToCopy.Append(spUdfObject); 

		_pCallUDFTool1Dlg->_pDlgProgress->StepIt();

	}
	/*delete pDlgProgress;
	pDlgProgress = nullptr;*/

	CATPathElement* pPathOnTarget = new CATPathElement(spGsmTool);

	CATListValCATBaseUnknown_var spEntitiesCopied;
	DataCommonProtocolCCPServices::CopyAndPasteTo(spEntitiesToCopy, pPathOnTarget, spEntitiesCopied);

	for (int i = 1; i <= spEntitiesToCopy.Size(); i++)
		DeleteAnything(spEntitiesToCopy[i]);
	
	CAAUpdateObject(_spCurrentPart);

	delete pPathOnTarget;

	if (NULL != pPathInput4)
	{
		pPathInput4->Release();
		pPathInput4 = NULL;
	}
	if (NULL != pPathInput3)
	{
		pPathInput3->Release();
		pPathInput3 = NULL;
	}
	if (NULL != pPathInput1)
	{
		pPathInput1->Release();
		pPathInput1 = NULL;
	}


	pBUXYPlaneMObj = NULL;
	pBUBTPlanefObj = NULL;
	pBUBTPlaneMObj = NULL;

	return rc;
}

HRESULT CallUDFTool1Cmd::PrintOldInputs(CATIUdfInstantiate_var &hIUdfInstantiate)
{
	CATListOfCATUnicodeString * pListOfInputRole = NULL;
	CATListValCATBaseUnknown_var * pListOfInput = NULL;

	HRESULT rc = E_FAIL;
	rc = hIUdfInstantiate->GetOldInputs(pListOfInput, pListOfInputRole);
	if (FAILED(rc) || (NULL == pListOfInput) || (NULL == pListOfInputRole))
	{
		cout << "输入元素未获取 " << endl;
		return E_FAIL;
	}

	for (int j = 1; j <= (*pListOfInput).Size(); j++)
	{
		CATIAlias_var spAlias = (*pListOfInput)[j];
		CATUnicodeString strAlias = spAlias->GetAlias();
		cout << "OldInput Name == " << strAlias << endl;
		DisplayMessage("Error", strAlias, "ERROR");

		CATUnicodeString strRoleAlias = (*pListOfInputRole)[j];
		cout << "OldInputRole Name == " << strRoleAlias << endl;
		DisplayMessage("Error", strRoleAlias, "ERROR");
	}

	delete pListOfInputRole;
	pListOfInputRole = NULL;

	delete pListOfInput;
	pListOfInput = NULL;

	return rc;
}


//获取正确的参数名称
CATUnicodeString CallUDFTool1Cmd::GetRightParamName(const CATUnicodeString &istrfullParamName)
{
	int iLength = istrfullParamName.GetLengthInChar();
	if (0 == iLength) return "";

	int iStartPos = 0;
	for (int i = iLength - 1; i >= 0; i--)
	{
		CATUnicodeChar iCurrentChar = istrfullParamName[i];
		if (iCurrentChar == CATUnicodeChar('\\'))
		{
			iStartPos = i + 1;
			break;
		}
	}

	CATUnicodeString strValue("");
	strValue = istrfullParamName.SubString(iStartPos, iLength - iStartPos);
	return strValue;
}

HRESULT CallUDFTool1Cmd::CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU)
{
	if (NULL_var == spUpdateObjectBU)
	{
		cout << "ERROR:CAAUpdateObject() - spUpdateObjectBU is NULL!" << endl;
		return E_FAIL;
	}

	CATIUseEntity *piUseEntity = NULL;
	HRESULT rc = spUpdateObjectBU->QueryInterface(IID_CATIUseEntity, (void**)&piUseEntity);
	if (SUCCEEDED(rc))
	{
		rc = DataCommonProtocolServices::Update(piUseEntity);
		if (FAILED(rc))
		{
			CATError * pError = CATError::CATGetLastError(rc);
			if (NULL != pError)
			{
				cerr << "Error message is " << pError->GetNLSMessage() << endl;
				pError->Release();
				pError = NULL;
			}
		}
		piUseEntity->Release();
		piUseEntity = NULL;
	}

	return rc;
}

HRESULT CallUDFTool1Cmd::GetParams(double para[])
{
	double iValue1 = _pCallUDFTool1Dlg->_SpinnerPlane1->GetValue();
	double iValue2 = _pCallUDFTool1Dlg->_SpinnerPlane2->GetValue();
	double iValue3 = _pCallUDFTool1Dlg->_SpinnerPlane3->GetValue();
	double iValue4 = _pCallUDFTool1Dlg->_SpinnerPlane4->GetValue();

	para[0] = iValue1;
	para[1] = iValue2;
	para[2] = iValue3;
	para[3] = iValue4;

	return S_OK;
}

HRESULT CallUDFTool1Cmd::ModifyPartParams2(const CATIUdfInstantiate_var &hIUdfInstantiate, double para[])
{
	HRESULT rc = E_FAIL;
	CATListValCATBaseUnknown_var * plistParamObj = NULL;
	CATListOfCATUnicodeString    * plistParamName = NULL;
	rc = hIUdfInstantiate->GetParameters(plistParamObj, plistParamName);
	if (FAILED(rc) || NULL == plistParamObj)
	{
		cout << "ERROR:GetParameters Failed" << endl;
		return rc;
	}

	for (int i = 1; i <= plistParamObj->Size(); i++)
	{
		CATICkeParm_var spCkeParm = (*plistParamObj)[i];

		CATUnicodeString strParamName = spCkeParm->Name();
		strParamName = GetRightParamName(strParamName);
		//cout << "spCkeParam == " << spCkeParm->Content() << endl;

		if (CATUnicodeString("高程面1") == strParamName)
		{
			spCkeParm->Valuate(para[0]);
		}
		else if (CATUnicodeString("高程面2") == strParamName)
		{
			spCkeParm->Valuate(para[1]);
		}
		else if (CATUnicodeString("高程面3") == strParamName)
		{
			spCkeParm->Valuate(para[2]);
		}
		else if (CATUnicodeString("高程面4") == strParamName)
		{
			spCkeParm->Valuate(para[3]);
		}
		else {
			cout << "ERROR:参数错误" << endl;

		}

	}


	delete plistParamObj;
	plistParamObj = NULL;

	delete plistParamName;
	plistParamName = NULL;

	return rc;
}



HRESULT CallUDFTool1Cmd::SetSpecLineObjColor(const CATIMmiMechanicalFeature_var &ispFeature, int iColor)
{
	if (NULL_var == ispFeature) return E_FAIL;

	CATIVisProperties *piGraphProp = NULL;
	HRESULT rc = ispFeature->QueryInterface(IID_CATIVisProperties, (void**)&piGraphProp);
	if (FAILED(rc) || piGraphProp == NULL) return rc;

	CATVisPropertiesValues Attribut;
	switch (iColor)
	{
	case 0: {Attribut.SetColor(255, 0, 0); break; }    //红
	case 1: {Attribut.SetColor(0, 255, 0); break; }    //绿
	case 2: {Attribut.SetColor(0, 0, 255); break; }    //蓝
	case 3: {Attribut.SetColor(255, 255, 0); break; }  //黄
	case 4: {Attribut.SetColor(255, 0, 255); break; }   //紫
	case 5: {Attribut.SetColor(0, 255, 255); break; }   //青
	case 6: {Attribut.SetColor(100, 100, 255); break; }//
	case 7: {Attribut.SetColor(0, 0, 0); break; }      //黑
	case 8: {Attribut.SetColor(255, 255, 255); break; }//白
	default: {Attribut.SetColor(255, 255, 0); break; }  //黄
	}

	piGraphProp->SetPropertiesAtt(Attribut, CATVPColor, CATVPLine, 0, 0);
	piGraphProp->Release();
	piGraphProp = NULL;

	CATIModelEvents *piME = NULL;
	rc = ispFeature->QueryInterface(IID_CATIModelEvents, (void **)&piME);
	if (FAILED(rc) || piME == NULL) return rc;
	CATModifyVisProperties notif(ispFeature, CATPathElement(ispFeature), CATVPLine, CATVPColor, Attribut);
	piME->Dispatch(notif);
	piME->Release();
	piME = NULL;

	return rc;
}



CATUnicodeString CallUDFTool1Cmd::GetRightParamName2(const CATUnicodeString &istrfullParamName)
{
	int iLength = istrfullParamName.GetLengthInChar();
	if (0 == iLength) return "";

	int iStartPos = 0;
	for (int i = 0; i <= iLength - 1; i++)
	{
		CATUnicodeChar iCurrentChar = istrfullParamName[i];
		if (iCurrentChar == CATUnicodeChar('/'))
		{
			iStartPos = i;
			break;
		}
	}

	CATUnicodeString strValue("");
	strValue = istrfullParamName.SubString(0, iStartPos);
	return strValue;
}

void CallUDFTool1Cmd::GetElementName(CATPathElement*ipPath, CATUnicodeString & ioElementName)
{
	ioElementName = "";
	if (NULL != ipPath)
	{
		int sizeOfThePath = ipPath->GetSize();

		int i = sizeOfThePath - 1;
		
		CATBaseUnknown * pElt = (*ipPath)[i];
		if (NULL != pElt)
		{
			CATIAlias * pIAliasOnElt = NULL;
			HRESULT rc = pElt->QueryInterface(IID_CATIAlias, (void**)&pIAliasOnElt);
			if (SUCCEEDED(rc))
			{
				CATUnicodeString Name = pIAliasOnElt->GetAlias();
				ioElementName.Append(Name);

				pIAliasOnElt->Release();
				pIAliasOnElt = NULL;
			}
		}
		
	}
}

void CallUDFTool1Cmd::PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName, CATBoolean Leaf)
{
	oPathName = "";
	if (NULL != ipPath)
	{
		int sizeOfThePath = ipPath->GetSize();

		for (int i = sizeOfThePath - 1; i >= 0; i--)
		{
			CATBaseUnknown * pElt = (*ipPath)[i];
			if (NULL != pElt)
			{
				CATIAlias * pIAliasOnElt = NULL;
				HRESULT rc = pElt->QueryInterface(IID_CATIAlias, (void**)&pIAliasOnElt);
				if (SUCCEEDED(rc))
				{
					CATUnicodeString Name = pIAliasOnElt->GetAlias();
					oPathName.Append(Name);

					if (TRUE == Leaf)
					{
						pIAliasOnElt->Release();
						pIAliasOnElt = NULL;
						break;
					}

					if (i > 0)
					{
						oPathName.Append("/"); ;
					}

					pIAliasOnElt->Release();
					pIAliasOnElt = NULL;
				}
			}
		}
	}
}

void CallUDFTool1Cmd::GetXY(CATIMmiUsePrtPart_var &spCurrentPart, CATIMmiMechanicalFeature_var &ospXYPlane)
{
	CATListValCATIMmiMechanicalFeature_var ListOfPlanes;
	spCurrentPart->RetrieveReferencePlanes(ListOfPlanes);

	ospXYPlane = ListOfPlanes[1];
}



void CallUDFTool1Cmd::PreView()
{
	instantiated = true;
	OKAction();
	return;

}

void CallUDFTool1Cmd::ClickOK()
{
	HRESULT rc = S_OK;
	if (!instantiated)
	{
		rc = OKAction();
	}

	CATULong state(0);
	state = _pCallUDFTool1Dlg->_CheckButton->GetState();
	if (CATULong(CATDlgCheck) == state)
		_pCallUDFTool1Dlg->Refresh();
	else {
		if(SUCCEEDED(rc))
			this->RequestDelayedDestruction();
		return;
	}
}

HRESULT CallUDFTool1Cmd::GetUDFfeat(CATIUdfInstantiate_var& hIUdfInstantiate)
{

	if (NULL_var == _spFeatNavRef)
	{
		cout << "Error:NULL_var == _spFeatNavRef" << endl;
		return E_FAIL;
	}


	//获取container
	CATIMmiPrtContainer *pIPrtContOnPC(NULL);
	CATIPLMComponent *piPLMCompOnFeatRef(NULL);
	HRESULT rc = GetUDFContainerFromDB(_ModelBag, _spFeatNavRef, piPLMCompOnFeatRef, pIPrtContOnPC);
	if (FAILED(rc) || NULL == pIPrtContOnPC || NULL == piPLMCompOnFeatRef)
	{

		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - GetUDFContainerFormDB is failed!" << endl;
		return E_FAIL;
	}

	CATIPLMComponent_var spiPLMCompOnFeatRef(NULL_var);
	spiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;

	//获取结构树上超级副本
	CATLISTV(CATIUdfInstantiate_var) iListOfPCReferences;
	rc = CATTemplatesAccessServices::GetUserFeatureList(pIPrtContOnPC, iListOfPCReferences);

	pIPrtContOnPC->Release();
	pIPrtContOnPC = NULL;

	if (0 == iListOfPCReferences.Size())
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - UDF Number is 0!" << endl;
		return E_FAIL;
	}

	//CATIUdfInstantiate_var hIUdfInstantiate(NULL_var);
	hIUdfInstantiate = iListOfPCReferences[1];

	if (NULL_var == spiPLMCompOnFeatRef)
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - spiPLMCompOnFeatRef is NULL!" << endl;
		return E_FAIL;
	}
	if (NULL_var == hIUdfInstantiate)
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - hIUdfInstantiate is NULL!" << endl;
		return E_FAIL;
	}
	return rc;
}

HRESULT CallUDFTool1Cmd::PrintOldUDFParams(CATIUdfInstantiate_var& hIUdfInstantiate)
{
	CATIAlias_var spOnUDF = hIUdfInstantiate;
	if (NULL_var != spOnUDF)
		cout << "UDF： " << spOnUDF->GetAlias() << endl;

	HRESULT rc = S_OK;
	CATIUdfFeatureInstance_var spInstance = hIUdfInstantiate;
	CATListValCATBaseUnknown_var * plistParamObj = NULL;
	CATListOfCATUnicodeString    * plistParamName = NULL;
	rc = spInstance->GetParameters(plistParamObj);
	if (FAILED(rc) || plistParamObj == NULL)
	{
		cout << "GetParameters Failed" << endl;
		return rc;
	}

	for (int i = 1; i <= plistParamObj->Size(); i++)
	{
		CATICkeParm_var spCkeParm = (*plistParamObj)[i];

		CATUnicodeString strParamName = spCkeParm->Name();
		strParamName = GetRightParamName(strParamName);
		//DisplayMessage("Error", strParamName, "ERROR");
		//cout << "ParamName: " << strParamName << endl;
		//cout << "spCkeParam == " << spCkeParm->Content() << endl;

		CATUnicodeString strParamValue = spCkeParm->Content();
		int pValue(0);
		strParamValue.ConvertToNum(&pValue);
		//double currentValue{ *pValue };

		if (CATUnicodeString("高程面1") == strParamName)
		{
			_pCallUDFTool1Dlg->_SpinnerPlane1->SetValue(pValue);
		}
		else if (CATUnicodeString("高程面2") == strParamName)
		{
			_pCallUDFTool1Dlg->_SpinnerPlane2->SetValue(pValue);
		}
		else if (CATUnicodeString("高程面3") == strParamName)
		{
			_pCallUDFTool1Dlg->_SpinnerPlane3->SetValue(pValue);
		}
		else if (CATUnicodeString("高程面4") == strParamName)
		{
			_pCallUDFTool1Dlg->_SpinnerPlane4->SetValue(pValue);

		}
	}

	delete plistParamObj;
	plistParamObj = NULL;

	delete plistParamName;
	plistParamName = NULL;

	return rc;
}


//复制实例化结果到 “趾板定线”几何图形集下

HRESULT CallUDFTool1Cmd::CopyObjectIntoSpecGeoTool(CATIMmiMechanicalFeature_var  spGeometryTool, CATBaseUnknown_var ispSelSketchReferPlaneBU, CATIMmiMechanicalFeature_var &ospResult)
{
	HRESULT rc(E_FAIL);
	CATIMmiUseCreateImport* pCreateImport = NULL;
	CATMmiUseServicesFactory::CreateMmiUseCreateImport(pCreateImport);

	pCreateImport->SetObject(ispSelSketchReferPlaneBU);
	pCreateImport->SetTarget(spGeometryTool);//a mechanical part, solid or surfacic feature set 

	CATIMmiMechanicalFeature_var spResult(NULL_var);
	pCreateImport->SetLinkMode(FALSE);
	pCreateImport->Run(spResult);
	if (NULL_var == spResult)
	{
		return E_FAIL;
	}
	ospResult = spResult;

	return S_OK;
}

//Create geoSet under the part
HRESULT CallUDFTool1Cmd::CAAGsiCreateGeometricFeatureSets(CATIMmiUsePrtPart_var spPrtPart,
	CATUnicodeString strGSMName,
	CATIMmiMechanicalFeature_var &ospGsmTool)
{
	if (NULL_var == spPrtPart)
		return E_FAIL;

	HRESULT rc = E_FAIL;

	CATIMmiMechanicalFeature_var spMechFeatOnMainTool = spPrtPart;
	if (NULL_var != spMechFeatOnMainTool)
	{
		//Get container
		CATIMmiPrtContainer_var spPrtCont = NULL_var;
		rc = spMechFeatOnMainTool->GetPrtContainer(spPrtCont);
		if (SUCCEEDED(rc) && spPrtCont != NULL_var)
		{
			CATIMmiUseSetFactory_var spMechanicalRootFactory = spPrtCont;
			if (spPrtCont != NULL_var)
			{
				CATIMmiMechanicalFeature_var spGSMTool;
				rc = spMechanicalRootFactory->CreateGeometricalSet(strGSMName, spMechFeatOnMainTool, spGSMTool);

				ospGsmTool = spGSMTool;
			}
		}
	}

	return rc;
}


HRESULT CallUDFTool1Cmd::DeleteAnything(CATBaseUnknown_var spDeleteObjectBU)
{
	if (NULL_var == spDeleteObjectBU)
	{
		cout << "ERROR:DeleteAnything() - spDeleteObjectBU is NULL!" << endl;
		return E_FAIL;
	}

	CATIUseEntity *piUseEntity = NULL;
	HRESULT rc = spDeleteObjectBU->QueryInterface(IID_CATIUseEntity, (void**)&piUseEntity);
	if (SUCCEEDED(rc))
	{
		rc = DataCommonProtocolServices::Delete(piUseEntity);
		if (FAILED(rc))
		{
			CATError * pError = CATError::CATGetLastError(rc);
			if (pError != NULL)
			{
				cerr << "Error message is " << pError->GetNLSMessage() << endl;
				pError->Release();
				pError = NULL;
			}
		}

		piUseEntity->Release();
		piUseEntity = NULL;

	}

	return rc;
}