//===================================================================
// COPYRIGHT atoz 2020/11/04
//===================================================================
// CallPowerCopyLanGanCmd.cpp
// Header definition of class CallPowerCopyLanGanCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/11/04 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CallPowerCopyLanGanCmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
CATCreateClass( CallPowerCopyLanGanCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CallPowerCopyLanGanCmd::CallPowerCopyLanGanCmd() :
CATStateCommand ("CallPowerCopyLanGanCmd", CATDlgEngOneShot, CATCommandModeExclusive)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, _strFeatID("")
, _strFeatVersion("")
, _listTemplateInstruction(NULL)
, _pCallPowerCopyLanGanDlg(NULL)
, _spCurrentPart(NULL_var)
, _spFeatNavRef(NULL_var)
, _ModelBag()
, _pSelCurvePathElemAgent(NULL)
, _pSelCurveDlgAgent(NULL)
, _pCurveElemLine(NULL)
{
	HRESULT rc = InitializeConfigData();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}

	rc = InitializeMainDialog();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}
	for (int i = 1; i <= _listTemplateInstruction.Size(); i++)
	{
		_pCallPowerCopyLanGanDlg->_EditorInstructions->SetLine(_listTemplateInstruction[i]);
	}

	GetCurrentPart(_spCurrentPart);
	
	DisplayTemplateView();
}

HRESULT CallPowerCopyLanGanCmd::InitializeConfigData()
{
	CATUnicodeString strInstallPath("");
	ClsConfigXMLServices::Get_ComputeDataExePath(strInstallPath);
	if (CATUnicodeString("") == strInstallPath) return E_FAIL;

	CATUnicodeString strProjectConfigPath = strInstallPath + "bin\\\ATOZ\\CAAEKLConfig";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		DisplayMessage("Error", "找不到CAAEKLConfig配置文件夹!", "ERROR");
		return E_FAIL;
	}

	const char* pxmlfilePath = CATFindPath("CAAPCConfig.xml", strProjectConfigPath);
	if (NULL == pxmlfilePath)
	{
		DisplayMessage("Error", "找不到CAAPCConfig.xml配置文件!", "ERROR");
		return E_FAIL;
	}

	CATUnicodeString strXMLFilePath = pxmlfilePath;
	HRESULT rc = ClsConfigXMLServices::GetCUPSConfigData(strXMLFilePath, "栏杆", _strFeatID, _strFeatVersion);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "读取CAAEKLConfig.xml配置文件失败!", "ERROR");
		return E_FAIL;
	}

	strProjectConfigPath = strInstallPath + "bin\\\ATOZ";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		DisplayMessage("Error", "找不到ATOZ配置文件夹!", "ERROR");
		return E_FAIL;
	}
	else
	{
		const char* pfilePath = CATFindPath("TemplateInstruction_6.ini", strProjectConfigPath);
		if (NULL != pfilePath)
		{
			ClsConfigXMLServices::ReadTemplateText(pfilePath, _listTemplateInstruction);
			//for (int i = 1; i <= _listTemplateInstruction.Size(); i++)
			//{
			//	cout << "_listTemplateInstruction["<<i<<"] == "<< _listTemplateInstruction[i] << endl;
			//}
		}
	}

	return S_OK;
}

//消息类型：Error、Information、Warning
int CallPowerCopyLanGanCmd::DisplayMessage(const CATString &istrMsgType,
	const CATUnicodeString &iusMsgToDisplay,
	const CATUnicodeString &iusDlgTitle)
{

	int RetUserReply = 0;

	CATDlgStyle Dlgstyle;
	CATUnicodeString usDlgTitle = "";

	if (istrMsgType == "Error")
	{
		Dlgstyle = CATDlgNfyError | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Error";
	}
	else if (istrMsgType == "Information")
	{
		Dlgstyle = CATDlgNfyInformation | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Information";
	}
	else if (istrMsgType == "Warning")
	{
		Dlgstyle = CATDlgNfyWarning | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Warning";
	}

	if (iusDlgTitle != "")usDlgTitle = iusDlgTitle;

	CATDlgNotify* pDlgNotify = new CATDlgNotify((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(), istrMsgType, Dlgstyle);
	if (!pDlgNotify) return 0;

	RetUserReply = pDlgNotify->DisplayBlocked(iusMsgToDisplay, usDlgTitle); // Get the User selected button
	return RetUserReply;
}

HRESULT CallPowerCopyLanGanCmd::InitializeMainDialog()
{
	_pCallPowerCopyLanGanDlg = new CallPowerCopyLanGanDlg((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
		"PowerCopyDlg");
	_pCallPowerCopyLanGanDlg->Build();

	CATNavigation3DViewer* p3DViewer = _pCallPowerCopyLanGanDlg->_Nav3DViewerModel;
	if (NULL != p3DViewer)
	{
		p3DViewer->SetBackgroundColor(0.235294f, 0.4f, 0.501961f);
	}

	_pCallPowerCopyLanGanDlg->_SelectorListPath->SetLine("No Selection");

	int ArraySel[1] = { 0 };
	_pCallPowerCopyLanGanDlg->_SelectorListPath->SetSelect(ArraySel, 1);


	_pCallPowerCopyLanGanDlg->_SpinnerExc->SetValue(0.0f);
	_pCallPowerCopyLanGanDlg->_SpinnerSep->SetValue(0.5f);
	_pCallPowerCopyLanGanDlg->_SpinnerHeight->SetValue(1.2f);

	_pCallPowerCopyLanGanDlg->_LabelLog->SetIconName("I_ZMXALog");
	_pCallPowerCopyLanGanDlg->SetVisibility(CATDlgShow);
	return S_OK;
}

HRESULT CallPowerCopyLanGanCmd::GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart)
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL == pFrmEditor) return E_FAIL;

	CATPathElement& CurrentElemPath = pFrmEditor->GetUIActiveObject();
	CATBaseUnknown* pCurrentObject = CurrentElemPath.FindElement(IID_CATIMmiUsePrtPart);
	if (NULL != pCurrentObject)
	{
		ospPrtPart = pCurrentObject;

	}

	return S_OK;
}

HRESULT CallPowerCopyLanGanCmd::DisplayTemplateView()
{
	CATLISTV(CATString)        listAttrName;
	CATLISTV(CATUnicodeString) listAttrValue;
	listAttrName.Append("PLM_ExternalID");
	listAttrName.Append("revision");

	listAttrValue.Append(_strFeatID);
	listAttrValue.Append(_strFeatVersion);
	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	GetPLMObjectsFromAttrAndFromType(listAttrName, listAttrValue, "VPMReference", listQueryResult);
	if (listQueryResult.Size() > 0)
	{
		CATBoolean authoringMode = TRUE;
		CATIPLMNavReference* piProductRef = NULL;
		OpenPLMComponent("VPMReference", listAttrName, listAttrValue,
			IID_CATIPLMNavReference, (void**)&piProductRef, _ModelBag, authoringMode);
		if (NULL != piProductRef)
		{
			//CATIPLMComponent_var spPLMComponent = piProductRef;
			//if (NULL_var != spPLMComponent)
			//{
			//	PrintComponentAttrs(spPLMComponent);
			//}

			CATIPrdOccurrenceMngt* piOccurrMngt = NULL;
			if (SUCCEEDED(CATPrdGetOccurrenceMngt(piOccurrMngt)) && piOccurrMngt)
			{
				CATIPLMNavOccurrence_var spPrdOccurr = NULL_var;
				piOccurrMngt->GetOrCreateRootOccurrence(piProductRef, spPrdOccurr);
				if (NULL_var != spPrdOccurr)
				{
					CATFrmEditor * pEditor = CATFrmEditor::GetCurrentEditor();
					CATVisManager * pVisuManager = CATVisManager::GetVisManager();
					CATCommand * pCommandSelector = (CATCommand*)pEditor->GetCommandSelector();
					list<IID> ListIVisu3d;
					IID visu3d = IID_CATI3DGeoVisu;
					ListIVisu3d.fastadd(&visu3d);
					CATPathElement*  pRootObjectPath = new CATPathElement(spPrdOccurr);
					CATViewpoint*  pModelViewPoint = (CATViewpoint*)&(_pCallPowerCopyLanGanDlg->_Nav3DViewerModel->GetMain3DViewpoint());
					HRESULT rc = pVisuManager->AttachTo(pRootObjectPath, pModelViewPoint, ListIVisu3d, pCommandSelector);

					_pCallPowerCopyLanGanDlg->_Nav3DViewerModel->Draw();
					_pCallPowerCopyLanGanDlg->_Nav3DViewerModel->Reframe();
				}

				piOccurrMngt->Release(); piOccurrMngt = NULL;
			}
			_spFeatNavRef = piProductRef;
			piProductRef->Release(); piProductRef = NULL;
		}
	}

	return S_OK;
}

HRESULT CallPowerCopyLanGanCmd::GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	const CATListOfCATUnicodeString &listOfValues,
	const CATUnicodeString &iStrPLMType,
	CATListPtrCATAdpQueryResult & opQueryResults)
{
	HRESULT hr = S_OK;
	//cout << "   GetPLMObjectsFromAttrAndFromType " << endl;

	if ((0 == listOfAttribute.Size()) || (0 == listOfValues.Size())) return E_INVALIDARG;
	if (listOfAttribute.Size() != listOfValues.Size()) return E_INVALIDARG;
	if (0 < opQueryResults.Size())return E_INVALIDARG;


	int iListSize = listOfAttribute.Size();

	CATAdpAttributeSet iAttributeSet;
	//cout << "   Build an Attribute set with inputs from user, for query into db" << endl;
	int i = 1;
	while ((i <= iListSize) && (SUCCEEDED(hr)))
	{
		CATUnicodeString Name = listOfAttribute[i].CastToCharPtr();
		const CATString AttributeINPUT = CATCkePLMNavPublicServices::RetrieveBasicAttributeNameFromPreviousOne(NULL_var, Name).CastToCharPtr();
		CATUnicodeString AttrValue = listOfValues[i];

		hr = iAttributeSet.AddAttribute(AttributeINPUT, AttrValue);
		i++;
	}

	CATIType_var spTypeObj = NULL_var;
	hr = RetrievePLMType(iStrPLMType, spTypeObj);
	if (FAILED(hr) || (NULL_var == spTypeObj))
	{
		cout << "ERROR:ClsPLMUtilities::GetPLMObjectsFromAttrAndFromType()-NULL_var == spTypeObj" << endl;
		return E_FAIL;
	}


	hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spTypeObj,
		iAttributeSet,
		opQueryResults);

	return hr;
}

HRESULT CallPowerCopyLanGanCmd::OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATListOfCATString &listAttrName,
	const CATLISTV(CATUnicodeString) &ListAttrValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll)
{
	HRESULT hr = S_OK;
	if (CATUnicodeString("") == istrPLMType) return E_FAIL;
	if (0 == listAttrName.Size()) return E_FAIL;
	if (0 == ListAttrValue.Size()) return E_FAIL;

	int iListSize = listAttrName.Size();

	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	hr = GetPLMObjectsFromAttrAndFromType(listAttrName, ListAttrValue, istrPLMType, listQueryResult);
	if (FAILED(hr) || (0 == listQueryResult.Size()))
	{

		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-0 == listQueryResult.Size()" << endl;
		return hr;
	}

	CATIAdpPLMIdentificator* piAdpPLMIdentificator = NULL;
	listQueryResult[1]->GetIdentifier(piAdpPLMIdentificator);
	if (NULL == piAdpPLMIdentificator)
	{
		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-NULL == piAdpPLMIdentificator" << endl;
		return E_FAIL;
	}

	if (TRUE == iExpandAll)
	{
		CATAdpOpenParameters params_Auth(CATAdpExpandParameters::Authoring);
		CATAdpOpener opener_Auth(iBag, params_Auth);
		// 5.2. Open the Retrieved Component by using CATAdpOpener
		hr = opener_Auth.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	else
	{
		CATAdpOpenParameters params_Nav(CATAdpExpandParameters::OneLevelRepresentations);
		CATAdpOpener opener_Nav(iBag, params_Nav);
		hr = opener_Nav.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	piAdpPLMIdentificator->Release();
	piAdpPLMIdentificator = NULL;

	return S_OK;
}

HRESULT CallPowerCopyLanGanCmd::RetrievePLMType(const CATUnicodeString & isPLMType,
	CATIType_var & ospType)
{
	HRESULT rc = E_INVALIDARG;
	if (isPLMType != "")
	{
		// For DS type
		rc = CATCkePLMNavPublicServices::RetrieveKnowledgeType(isPLMType, ospType);
		// For Specialization Type
		if (FAILED(rc))  rc = CATCkePLMNavSpecializationAccessPublicServices::RetrieveSpecializationType(isPLMType, ospType);
	}
	return rc;
}
//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CallPowerCopyLanGanCmd::~CallPowerCopyLanGanCmd()
{
	_pCurveElemLine = NULL;

	if (NULL != _pSelCurveDlgAgent)
	{
		_pSelCurveDlgAgent->RequestDelayedDestruction();
		_pSelCurveDlgAgent = NULL;
	}
	
	if (NULL != _pSelCurvePathElemAgent)
	{
		_pSelCurvePathElemAgent->RequestDelayedDestruction();
		_pSelCurvePathElemAgent = NULL;
	}

	if (NULL != _pCallPowerCopyLanGanDlg)
	{
		_pCallPowerCopyLanGanDlg->RequestDelayedDestruction();
		_pCallPowerCopyLanGanDlg = NULL;
	}

	_ModelBag.RemoveAll();
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void CallPowerCopyLanGanCmd::BuildGraph()
{
	_pSelCurvePathElemAgent = new CATPathElementAgent("SelectCurve");
	_pSelCurvePathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelCurvePathElemAgent->AddElementType(IID_CATIMmiUseWireREdge);

	_pSelCurveDlgAgent = new CATDialogAgent("CurveDlg");
	_pSelCurveDlgAgent->AcceptOnNotify(_pCallPowerCopyLanGanDlg->_SelectorListPath,
		_pCallPowerCopyLanGanDlg->_SelectorListPath->GetListSelectNotification());

	CATDialogState * SelectCurveState = GetInitialState("请选择路径");
	SelectCurveState->AddDialogAgent(_pSelCurvePathElemAgent);

	AddTransition(SelectCurveState, SelectCurveState,
		IsOutputSetCondition(_pSelCurvePathElemAgent),
		Action((ActionMethod)&CallPowerCopyLanGanCmd::SelectCurveObj));

	//callbacks
	AddAnalyseNotificationCB(_pCallPowerCopyLanGanDlg,
		_pCallPowerCopyLanGanDlg->GetWindCloseNotification(),
		(CATCommandMethod)&CallPowerCopyLanGanCmd::ExitCmd, NULL);
	//click cancel button
	AddAnalyseNotificationCB(_pCallPowerCopyLanGanDlg,
		_pCallPowerCopyLanGanDlg->GetDiaCANCELNotification(),
		(CATCommandMethod)&CallPowerCopyLanGanCmd::ExitCmd, NULL);

	//click OK button
	AddAnalyseNotificationCB(_pCallPowerCopyLanGanDlg,
		_pCallPowerCopyLanGanDlg->GetDiaOKNotification(),
		(CATCommandMethod)&CallPowerCopyLanGanCmd::OKAction, NULL);
}

void CallPowerCopyLanGanCmd::SelectCurveObj(void* idata)
{
	
	_pCurveElemLine = _pSelCurvePathElemAgent->GetValue();
	_pSelCurvePathElemAgent->InitializeAcquisition();


	CATUnicodeString strFullPath("");
	PathElementString(_pCurveElemLine, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallPowerCopyLanGanDlg->_SelectorListPath;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}



}

void CallPowerCopyLanGanCmd::PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName)
{

	oPathName = "";
	if (NULL != ipPath)
	{
		int sizeOfThePath = ipPath->GetSize();

		for (int i = sizeOfThePath - 1; i >= 0; i--)
		{
			CATBaseUnknown * pElt = (*ipPath)[i];
			if (NULL != pElt)
			{
				CATIAlias * pIAliasOnElt = NULL;
				HRESULT rc = pElt->QueryInterface(IID_CATIAlias, (void**)&pIAliasOnElt);
				if (SUCCEEDED(rc))
				{
					CATUnicodeString Name = pIAliasOnElt->GetAlias();
					oPathName.Append(Name);

					if (i > 0)
					{
						oPathName.Append("/"); ;
					}

					pIAliasOnElt->Release();
					pIAliasOnElt = NULL;
				}
			}
		}
	}
}

void CallPowerCopyLanGanCmd::ExitCmd(void* idata)
{
	this->RequestDelayedDestruction();
	return;
}

void CallPowerCopyLanGanCmd::OKAction(void* idata)
{
	if (NULL == _pCurveElemLine)
	{
		DisplayMessage("Warning", "请选择路径线!", "警告");
		return;
	}

	HRESULT rc = E_FAIL;
	if (NULL_var == _spFeatNavRef)
	{
		DisplayMessage("Warning", "NULL_var == _spFeatNavRef", "警告");
		return;
	}

	//获取container
	CATIMmiPrtContainer *pIPrtContOnPC(NULL);
	CATIPLMComponent *piPLMCompOnFeatRef(NULL);
	rc = GetUDFContainerFromDB(_ModelBag, _spFeatNavRef, piPLMCompOnFeatRef, pIPrtContOnPC);
	if (FAILED(rc) || NULL == pIPrtContOnPC || NULL == piPLMCompOnFeatRef)
	{
		DisplayMessage("Warning", "GetUDFContainerFormDB is failed!!", "警告");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - GetUDFContainerFormDB is failed!" << endl;
		return;
	}

	CATIPLMComponent_var spiPLMCompOnFeatRef(NULL_var);
	spiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;

	//获取结构树上超级副本
	CATLISTV(CATIUdfInstantiate_var) iListOfPCReferences;
	rc = CATTemplatesAccessServices::GetPowerCopyList(pIPrtContOnPC, iListOfPCReferences);

	pIPrtContOnPC->Release();
	pIPrtContOnPC = NULL;

	if (0 == iListOfPCReferences.Size())
	{
		DisplayMessage("Warning", "0 == iListOfPCReferences.Size()!", "警告");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - UDF Number is 0!" << endl;
		return;
	}

	CATIUdfInstantiate_var hIUdfInstantiate(NULL_var);
	CATUnicodeString type("");
	_pCallPowerCopyLanGanDlg->_ComboType->GetField(type);

	if (CATUnicodeString("开放路径") == type)
		hIUdfInstantiate = iListOfPCReferences[1];
	else
		hIUdfInstantiate = iListOfPCReferences[2];
	

	/*CATIAlias_var spAlias = hIUdfInstantiate;
	if (NULL_var == spAlias)
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - spAlias is NULL!" << endl;
		return;
	}
	CATUnicodeString strUDFAlias = spAlias->GetAlias();
	
	DisplayMessage("Warning", strUDFAlias, "警告");*/
	

	if (NULL_var == spiPLMCompOnFeatRef)
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - spiPLMCompOnFeatRef is NULL!" << endl;
		return;
	}
	if (NULL_var == hIUdfInstantiate)
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - hIUdfInstantiate is NULL!" << endl;
		return;
	}

	//设置实例化位置
	CATBaseUnknown_var spPartRequestBU = _spCurrentPart;
	if (NULL_var == spPartRequestBU)
	{
		DisplayMessage("Error", "NULL_var == spPartRequestBU", "ERROR");
		cout << "Error:NULL_var == spPartRequestBU" << endl;
		return;
	}
	CATBaseUnknown* pPartRequestBU = (CATBaseUnknown*)spPartRequestBU;
	if (NULL == pPartRequestBU)
	{
		cout << "Error:ATOZRDCSICITUDFImportCmd::OutRibUDFImp() - pPartRequestBU is NULL!" << endl;
		return;
	}
	CATPathElement PartRequestPath(pPartRequestBU);

	/*pPartRequestBU->Release();
	pPartRequestBU = NULL;*/

	CATPathElement *pUIactivePath(NULL);
	CATBaseUnknown_var spDestBU(NULL_var);

	rc = hIUdfInstantiate->SetDestinationPath(&PartRequestPath, pUIactivePath, spDestBU);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "SetDestinationPath Failed", "ERROR");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - SetDestinationPath() is failed!" << endl;
		return;
	}

	if (NULL != pUIactivePath)
	{
		pUIactivePath->Release();
		pUIactivePath = NULL;
	}


	rc = UDFImpInstantiating(spPartRequestBU, hIUdfInstantiate);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "UDFImpInstantiating Failed", "ERROR");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - SetDestinationPath() is failed!" << endl;
		return;
	}

	CAAUpdateObject(_spCurrentPart);

	if (FAILED(_ModelBag.RemoveAll()))
	{
		DisplayMessage("Warning", "_ModelBag", "警告");
	}

	if (NULL != piPLMCompOnFeatRef)
	{
		piPLMCompOnFeatRef->Release();
		piPLMCompOnFeatRef = NULL;
	}


	CATULong state(0);
	state = _pCallPowerCopyLanGanDlg->_CheckButton->GetState();
	if (CATULong(CATDlgCheck) == state)
		_pCallPowerCopyLanGanDlg->Refresh();
	else {
		this->RequestDelayedDestruction();
		return;
	}
}


HRESULT CallPowerCopyLanGanCmd::GetUDFContainerFromDB(CATOmbLifeCycleRootsBag &iobag,
	CATIPLMNavReference_var &ispFeatNavRef,
	CATIPLMComponent *&opiPLMCompOnFeatRef,
	CATIMmiPrtContainer *&opIPrtContOnCAAUdfLoft)
{
	HRESULT rc = S_OK;

	//QI
	CATIPLMComponent_var spiPLMCompOnFeatRef = NULL_var;
	CATIPLMNavReference* pFeatNavRef = NULL;
	pFeatNavRef = (CATIPLMNavReference*)ispFeatNavRef;
	if (NULL == pFeatNavRef)
	{
		DisplayMessage("Warning", "(NULL == pFeatNavRef)!", "警告");
		return E_FAIL;
	}

	CATIPLMComponent* piPLMCompOnFeatRef = NULL;
	rc = pFeatNavRef->QueryInterface(IID_CATIPLMComponent, (void**)&piPLMCompOnFeatRef);
	if (FAILED(rc) || NULL == piPLMCompOnFeatRef)
	{
		DisplayMessage("Warning", "(NULL == opiPLMCompOnFeatRef)!", "警告");
		return E_FAIL;
	}


	opiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	opiPLMCompOnFeatRef->AddRef();

	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;

	/////////////////////////////////////////////////////////////////////////////////////

	//3DShape

	CATPLMCoreType coreType = CATPLMCoreType::PLMCoreRepInstance;
	CATListPtrCATIPLMNavEntity ChildrenList;

	rc = pFeatNavRef->ListChildren(ChildrenList, 1, &coreType);
	if (ChildrenList.Size() == 0)
	{
		DisplayMessage("Warning", "ChildrenList.Size() == 0", "警告");
		return E_FAIL;
	}


	CATIPLMNavEntity *piNavEntity = ChildrenList[1];
	if (NULL == piNavEntity)
	{
		DisplayMessage("Warning", "NULL == piNavEntity", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piNavEntity is NULL!" << endl;
		return E_FAIL;
	}

	CATIPLMNavRepInstance * piPrdObjOnRepInst = NULL;
	rc = piNavEntity->QueryInterface(IID_CATIPLMNavRepInstance, (void**)&piPrdObjOnRepInst);
	if (FAILED(rc) || NULL == piPrdObjOnRepInst)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piPrdObjOnRepInst is NULL!" << endl;
		return E_FAIL;
	}


	CATIPLMNavRepReference* pi3DShapeRepRefer = NULL;
	rc = piPrdObjOnRepInst->GetRepReferenceInstanceOf(pi3DShapeRepRefer);
	if (FAILED(rc) || NULL == pi3DShapeRepRefer)
	{
		DisplayMessage("Warning", "NULL == pi3DShapeRepRefer", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piFirst3DShapeRepRefer is NULL!" << endl;
		return E_FAIL;
	}
	piPrdObjOnRepInst->Release();
	piPrdObjOnRepInst = NULL;


	CATIPLMNavRepReference_var spi3DShapeRepRefer(pi3DShapeRepRefer);
	pi3DShapeRepRefer->Release();
	pi3DShapeRepRefer = NULL;

	// edit mode is no longer default
	CATIPsiRepresentationLoadMode_var spRepLoadMode = spi3DShapeRepRefer;
	if (NULL_var == spRepLoadMode)
	{
		DisplayMessage("Warning", "(NULL == spRepLoadMode)!", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - spRepLoadMode is NULL!" << endl;
		return E_FAIL;
	}
	rc = spRepLoadMode->ChangeLoadingMode(CATIPsiRepresentationLoadMode::EditMode);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "ChangeLoadingMode is failed!", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ChangeLoadingMode is failed!" << endl;
	}

	//container
	CATIMmiPrtContainer *pIPrtContOnCAAUdfLoft = NULL;
	rc = spi3DShapeRepRefer->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pIPrtContOnCAAUdfLoft);
	if (FAILED(rc) || (NULL_var == pIPrtContOnCAAUdfLoft))
	{
		DisplayMessage("Warning", "(NULL == pIPrtContOnCAAUdf)!", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - RetrieveApplicativeContainer is failed!" << endl;
		return E_FAIL;
	}
	opIPrtContOnCAAUdfLoft = pIPrtContOnCAAUdfLoft;
	opIPrtContOnCAAUdfLoft->AddRef();

	// 3-bis Lock the Representation Reference containing the reference to instantiate
	//CATOmbLifeCycleRootsBag Bag ;
	rc = iobag.InsertRoot(opiPLMCompOnFeatRef);
	if (FAILED(rc))
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ibag.InsertRoot is failed!" << endl;
	}

	ULONG iL = pIPrtContOnCAAUdfLoft->Release();
	pIPrtContOnCAAUdfLoft = NULL;

	piNavEntity->Release();
	piNavEntity = NULL;

	return S_OK;
}

HRESULT CallPowerCopyLanGanCmd::UDFImpInstantiating(CATBaseUnknown_var &ispBUCurrentPartRef, CATIUdfInstantiate_var &hIUdfInstantiate)
{
	HRESULT rc = E_FAIL;

	//输入元素
	//对称 线 后面 前面

	if (NULL == _pCurveElemLine)
	{
		DisplayMessage("Warning", "NULL == pPathInput1", "警告");
		return E_FAIL;
	}
	rc = hIUdfInstantiate->SetNewInput(1, _pCurveElemLine);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "ERROR:SetNewInput1", "警告");
		return E_FAIL;
	}


	//修改模板参数
	rc = ModifyPartParams(hIUdfInstantiate);

	//实例化
	rc = hIUdfInstantiate->Instantiate(ispBUCurrentPartRef);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "Instantiate", "警告");
		return E_FAIL;
	}

	rc = hIUdfInstantiate->EndInstantiate();
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "EndInstantiate", "警告");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - EndInstantiate() is failed!" << endl;
		return E_FAIL;
	}



	return rc;
}

HRESULT CallPowerCopyLanGanCmd::ModifyPartParams(CATIUdfInstantiate_var &hIUdfInstantiate)
{
	HRESULT rc = E_FAIL;
	CATListValCATBaseUnknown_var * plistParamObj = NULL;
	CATListOfCATUnicodeString    * plistParamName = NULL;
	rc = hIUdfInstantiate->GetParameters(plistParamObj, plistParamName);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "GetParameters Failed", "ERROR");
		return rc;
	}


	CATUnicodeString strParamName("");
	for (int i = 1; i <= plistParamObj->Size(); i++)
	{
		CATICkeParm_var spCkeParm = (*plistParamObj)[i];

		strParamName = spCkeParm->Name();

		strParamName = GetRightParamName(strParamName);

		if (CATUnicodeString("偏移") == strParamName)
		{
			double iValue = _pCallPowerCopyLanGanDlg->_SpinnerExc->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("间距") == strParamName)
		{
			double iValue = _pCallPowerCopyLanGanDlg->_SpinnerSep->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("栏杆高度") == strParamName)
		{
			double iValue = _pCallPowerCopyLanGanDlg->_SpinnerHeight->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else 
		{
			DisplayMessage("Error", "参数输入错误", "ERROR");
		}

	}

	delete plistParamObj;
	plistParamObj = NULL;

	delete plistParamName;
	plistParamName = NULL;

	return rc;
}

HRESULT CallPowerCopyLanGanCmd::CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU)
{
	if (NULL_var == spUpdateObjectBU)
	{
		cout << "ERROR:CAAUpdateObject() - spUpdateObjectBU is NULL!" << endl;
		return E_FAIL;
	}

	CATIUseEntity *piUseEntity = NULL;
	HRESULT rc = spUpdateObjectBU->QueryInterface(IID_CATIUseEntity, (void**)&piUseEntity);
	if (SUCCEEDED(rc))
	{
		rc = DataCommonProtocolServices::Update(piUseEntity);
		if (FAILED(rc))
		{
			CATError * pError = CATError::CATGetLastError(rc);
			if (NULL != pError)
			{
				cerr << "Error message is " << pError->GetNLSMessage() << endl;
				pError->Release();
				pError = NULL;
			}
		}
		piUseEntity->Release();
		piUseEntity = NULL;
	}

	return rc;
}

CATUnicodeString CallPowerCopyLanGanCmd::GetRightParamName(const CATUnicodeString &istrfullParamName)
{
	int iLength = istrfullParamName.GetLengthInChar();
	if (0 == iLength) return "";

	int iStartPos = 0;
	for (int i = iLength - 1; i >= 0; i--)
	{
		CATUnicodeChar iCurrentChar = istrfullParamName[i];
		if (iCurrentChar == CATUnicodeChar('\\'))
		{
			iStartPos = i + 1;
			break;
		}
	}

	CATUnicodeString strValue("");
	strValue = istrfullParamName.SubString(iStartPos, iLength - iStartPos);
	return strValue;
}