//===================================================================
// COPYRIGHT atoz 2020/12/07
//===================================================================
// ATOZZMXAEngineeringTemplate10.cpp
// Header definition of class ATOZZMXAEngineeringTemplate10
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/12/07 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByATOZZMXAEngineeringTemplate10_H
#define ExportedByATOZZMXAEngineeringTemplate10_H
#if defined(__ATOZZMXAEngineeringTemplate10)
# define ExportedByATOZZMXAEngineeringTemplate10   DSYExport
#else // __ATOZZMXAEngineeringTemplate10
# define ExportedByATOZZMXAEngineeringTemplate10   DSYImport
#endif  // __ATOZZMXAEngineeringTemplate10
#include "DSYExport.h"
#endif //ExportedByATOZZMXAEngineeringTemplate10_H

