//===================================================================
// COPYRIGHT atoz 2021/03/18
//===================================================================
// AtoZDDTZMXACmdAddFakeValue.cpp
// Header definition of class AtoZDDTZMXACmdAddFakeValue
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/03/18 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByAtoZDDTZMXACmdAddFakeValue_H
#define ExportedByAtoZDDTZMXACmdAddFakeValue_H
#if defined(__AtoZDDTZMXACmdAddFakeValue)
# define ExportedByAtoZDDTZMXACmdAddFakeValue   DSYExport
#else // __AtoZDDTZMXACmdAddFakeValue
# define ExportedByAtoZDDTZMXACmdAddFakeValue   DSYImport
#endif  // __AtoZDDTZMXACmdAddFakeValue
#include "DSYExport.h"
#endif //ExportedByAtoZDDTZMXACmdAddFakeValue_H

