//===================================================================
// COPYRIGHT atoz 2021/01/06
//===================================================================
// ATOZAddingParameterSet.cpp
// Header definition of class ATOZAddingParameterSet
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/01/06 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByATOZAddingParameterSet_H
#define ExportedByATOZAddingParameterSet_H
#if defined(__ATOZAddingParameterSet)
# define ExportedByATOZAddingParameterSet   DSYExport
#else // __ATOZAddingParameterSet
# define ExportedByATOZAddingParameterSet   DSYImport
#endif  // __ATOZAddingParameterSet
#include "DSYExport.h"
#endif //ExportedByATOZAddingParameterSet_H

