//===================================================================
// COPYRIGHT atoz 2021/03/12
//===================================================================
// AtoZDDTZMXACmdShowTurningPt.cpp
// Header definition of class AtoZDDTZMXACmdShowTurningPt
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/03/12 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByAtoZDDTZMXACmdShowTurningPt_H
#define ExportedByAtoZDDTZMXACmdShowTurningPt_H
#if defined(__AtoZDDTZMXACmdShowTurningPt)
# define ExportedByAtoZDDTZMXACmdShowTurningPt   DSYExport
#else // __AtoZDDTZMXACmdShowTurningPt
# define ExportedByAtoZDDTZMXACmdShowTurningPt   DSYImport
#endif  // __AtoZDDTZMXACmdShowTurningPt
#include "DSYExport.h"
#endif //ExportedByAtoZDDTZMXACmdShowTurningPt_H

