//===================================================================
// COPYRIGHT atoz 2021/02/25
//===================================================================
// AtoZDDTZMXACmdPipeHgtLabling.cpp
// Header definition of class AtoZDDTZMXACmdPipeHgtLabling
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/02/25 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByAtoZDDTZMXACmdPipeHgtLabling_H
#define ExportedByAtoZDDTZMXACmdPipeHgtLabling_H
#if defined(__AtoZDDTZMXACmdPipeHgtLabling)
# define ExportedByAtoZDDTZMXACmdPipeHgtLabling   DSYExport
#else // __AtoZDDTZMXACmdPipeHgtLabling
# define ExportedByAtoZDDTZMXACmdPipeHgtLabling   DSYImport
#endif  // __AtoZDDTZMXACmdPipeHgtLabling
#include "DSYExport.h"
#endif //ExportedByAtoZDDTZMXACmdPipeHgtLabling_H

