//===================================================================
// COPYRIGHT ATOZ 2015/09/01
//===================================================================
// ATOZDrawingTest.cpp
// Header definition of class ATOZDrawingTest
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2015/09/01 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __ATOZDrawingTest
#define ExportedByATOZDrawingTest     __declspec(dllexport)
#else
#define ExportedByATOZDrawingTest     __declspec(dllimport)
#endif
#else
#define ExportedByATOZDrawingTest
#endif
