//===================================================================
// COPYRIGHT atoz 2021/01/29
//===================================================================
// AtoZDDTZMXACmdPipeProjAnno.cpp
// Header definition of class AtoZDDTZMXACmdPipeProjAnno
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/01/29 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByAtoZDDTZMXACmdPipeProjAnno_H
#define ExportedByAtoZDDTZMXACmdPipeProjAnno_H
#if defined(__AtoZDDTZMXACmdPipeProjAnno)
# define ExportedByAtoZDDTZMXACmdPipeProjAnno   DSYExport
#else // __AtoZDDTZMXACmdPipeProjAnno
# define ExportedByAtoZDDTZMXACmdPipeProjAnno   DSYImport
#endif  // __AtoZDDTZMXACmdPipeProjAnno
#include "DSYExport.h"
#endif //ExportedByAtoZDDTZMXACmdPipeProjAnno_H

