//===================================================================
// COPYRIGHT atoz 2020/12/18
//===================================================================
// ATOZCatalogBrowsing.cpp
// Header definition of class ATOZCatalogBrowsing
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/12/18 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByATOZCatalogBrowsing_H
#define ExportedByATOZCatalogBrowsing_H
#if defined(__ATOZCatalogBrowsing)
# define ExportedByATOZCatalogBrowsing   DSYExport
#else // __ATOZCatalogBrowsing
# define ExportedByATOZCatalogBrowsing   DSYImport
#endif  // __ATOZCatalogBrowsing
#include "DSYExport.h"
#endif //ExportedByATOZCatalogBrowsing_H

