//===================================================================
// COPYRIGHT ATOZ 2020/11/18
//===================================================================
// ClsDrawingPubServices.cpp
// Header definition of class ClsDrawingPubServices
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/11/18 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef ClsDrawingPubServices_H
#define ClsDrawingPubServices_H

#include "ATOZDrawingPubFunc.h"

//system includes
#include "CATUnicodeString.h"
#include "CATLISTV_CATBaseUnknown.h"
#include "CATIUnknownList.h"
#include "CATAutoConversions.h"
#include "CATVariant.h"

//Mathematics includes
#include "CATMathPlane.h"
#include "CATMathDirection.h"
#include "CATMathPoint.h"
#include "CATMathAxis.h"
#include "CATMathTransformation.h"
#include "CATMathAxis2D.h"
#include "CATMathTransformation2D.h"
//DraftingUseItf includes
#include "CATIDftSheet.h"
#include "CATIDftView.h"
#include "CATIDftGenerSpec.h"
#include "CATIDftDrawing.h"
#include "CATIDftBaseAnnotationFactory.h"
#include "CATDftDrawingPLMServices.h"

//CATDraftingGenUseItf includes
#include "CATIDftGenGeom.h"

//DraftingIDLItf includes
#include "CATIADrawingView.h"
#include "CATIADrawingGenView.h"
#include "CATIADrawingComponents.h"
#include "CATIADrawingComponent.h"
#include "CATIADrawingText.h"
#include "CATIADrawingTables.h"
#include "CATIADrawingTable.h"

//CATDraftingGenUseItf includes
#include "CATIDftGenGeomAccess.h"
#include "CATIDftGenGeom.h"

//AfrFoundation includes
#include "CATFrmEditor.h"
#include "CATIAEditor.h"
#include "CATApplicationFrame.h"
#include "CATFrmContext.h"
#include "CATListOfCATFrmEditor.h"

//ObjectModelerBase includes
#include "CATOmbObjectInContext.h"

//CATPLMComponentInterfaces includes
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavReference.h"

//CATPLMIdentificationAccess includes
#include "CATIPLMComponent.h"
#include "CATListPtrCATIPLMComponent.h"
#include "CATIDrwDimDimension.h"
#include "CATIDrwDimValue.h"
#include "CATIDrwDimFakeComponent.h"
#include "CATIDrwTextProperties.h"
#include "CATIAlias.h"
#include "CATIDftGenViewModification.h"
#include "CATIDftGenViewUpdate.h"
#include "CATDftGenViewProperties.h"
#include "CATDftGenPLMServices.h"
#include "CATIPsiRepresentationReference.h"
//-----------------------------------------------------------------------
#include "iostream.h"
using namespace std;


class ExportedByATOZDrawingPubFunc ClsDrawingPubServices
{
public:
// Standard constructors and destructors
// -------------------------------------
ClsDrawingPubServices ();
virtual ~ClsDrawingPubServices ();

//获取当前二维图激活页
static HRESULT RetrieveCurrentDftSheet(CATIDftSheet_var &ospDftSheet);

//获取当前drawing对象
static HRESULT GetCurrentDrawing(CATIDftDrawing * &piDftDrawing);

//获取所有视图，不包括主视图和背景视图
//V6 有自带API 直接获取所有视图对象（不包括主视图和辅助视图
static HRESULT RetrieveOtherViews(const CATIDftSheet_var &spDftSheet,
	                              CATLISTV(CATBaseUnknown_var) &olistOtherViews);

//获取视图中几何元素关联的Instance Product对象
static HRESULT RetrieveRelatedInsProOfDftGeo(const CATIDftGenGeom_var &ispDftGenGeom,
	                                         CATIPLMNavInstance_var &ospPLMNavInstance);

//获取二维视图中的所有几何元素特征
static HRESULT GetViewAllGenElems(const CATIDftView_var &ispDftView,
	                              CATLISTV(CATBaseUnknown_var) &olistGenElems);

//获取二维视图关联的文档节点
static HRESULT GetProductFromView(const CATIDftView_var &spDftView,
	                              CATIPLMNavReference_var &ospNavRef);

//获取Drawing对象下所有详细页下的组件模板
static HRESULT GetAllDrawingComponents(const CATIDftDrawing_var &ispDftDrawing,
	                                   CATLISTV(CATBaseUnknown_var) &olistComponents);

//视图添加实例化组件
static HRESULT AddViewComponent(CATBaseUnknown_var spTargetViewBU, CATBaseUnknown_var spSourceViewBU,
	                            double xPosition, double yPosition,
	                            CATBaseUnknown_var &spInstanteComponentBU);

//获取View的投影平面信息，输出结果为转换矩阵
static HRESULT RetrieveProjectPlaneInView(const CATIDftView_var &ispDftView,
	                                      CATMathTransformation &oMathTrans,
	                                      CATMathDirection &oProjectDirection);

//获取视图下的所有的组件实例
static HRESULT GetAllComponentsOnView(const CATIDftView_var &ispDftView, 
	                                  CATLISTV(CATBaseUnknown_var) &olist2DComponent);

//从视图坐标转换到全局坐标
static void GetGlobalMathPt(const CATIDftView_var &ispActiveView,
	                        double         iOriginScale,
	                        CATMathPoint2D iLocalMathPt2D,
	                        CATMathPoint2D &oGolobalMathPt2D);

HRESULT GetAllSheets(const CATIDftDrawing_var &ispDftDrawing,
	CATLISTV(CATBaseUnknown_var) &olistSheets);

HRESULT ClsDrawingPubServices::ManageAllDims(CATLISTV(CATBaseUnknown_var) &ilistDimElems);


HRESULT GetViewAllDimElems(const CATIDftView_var &ispDftView,
	CATLISTV(CATBaseUnknown_var) &olistDimElems);

HRESULT Link3DModel(CATIDftDrawing_var &ispDrawing, CATIDftView_var &ospActiveView);
private:
// Copy constructor and equal operator
// -----------------------------------
ClsDrawingPubServices (ClsDrawingPubServices &);
ClsDrawingPubServices& operator=(ClsDrawingPubServices&);

};

//-----------------------------------------------------------------------

#endif
