//===================================================================
// COPYRIGHT ATOZ 2019/10/16
//===================================================================
// ClsPLMUtilities.cpp
// Header definition of class ClsPLMUtilities
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2019/10/16 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef ClsPLMUtilities_H
#define ClsPLMUtilities_H

#include "ATOZDrawingPubFunc.h"

//-----------------------------------------------------------------------
// CATPLMIntegrationAccess Framework
#include "CATAdpAttributeSet.h"
#include "CATAdpQueryServices.h"
#include "CATAdpQueryResult.h"
#include "CATAdpIdentificationSet.h"
#include "CATLISTP_CATAdpQueryResult.h"
#include "CATIAdpPLMIdentificator.h"

// CATPLMIntegrationUse Framework
#include "CATAdpPLMQueryFilter.h"
#include "CATAdpPLMComponentsInfos.h"
#include "CATAdpPLMComponentsInfosIter.h"
#include "CATAdpPLMExtendedQueryServices.h"
#include "CATAdpPLMQueryAttributeSet.h"
#include "CATAdpPLMComponentInfos.h"
#include "CATAdpPLMComponentUniqueKey.h"
#include "CATAdpPLMQueryServices.h"
#include "CATAdpOpenParameters.h"
#include "CATAdpOpener.h"

//ProductStructureInterfaces includes
#include "CATIPLMProducts.h"

//ProductStructureUseItf includes
#include "CATPrdFactory.h"
#include "CATIPrdReferenceFactory.h"
#include "CATIPrd3DPartReferenceFactory.h"

//CATPLMComponentInterfaces includes
#include "CATIPLMNavReference.h"

//PLMDictionaryNavServices includes
#include "CATCkePLMNavSpecializationAccessPublicServices.h"

//CATPLMIntegrationUse includes
#include "CATAdpPLMQueryServices.h"

//PLMDictionaryNavServices Framework
#include "CATCkePLMNavPublicServices.h"
#include "CATCkePLMNavCustoAccessPublicServices.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"

//KnowledgeInterfaces Framework
#include "CATIType.h"
#include "CATICkeParm.h"
#include "CATListValCATICkeParm.h"

// CATPLMIdentificationAccess Framework
#include "CATAdpAttributeSet.h"
#include "CATPLMCoreType.h"
#include "CATListPtrCATIPLMComponent.h"

// System
#include "CATString.h"
#include "CATListOfCATString.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"
#include "CATSysBoolean.h"
#include "CATBaseUnknown.h"
#include "CATLISTP_CATBaseUnknown.h"

//ObjectModelerBase includes
#include "CATOmbLifeCycleRootsBag.h"

// Standard C++ library
#include "iostream.h"

class ExportedByATOZDrawingPubFunc ClsPLMUtilities
{
public:
// Standard constructors and destructors
// -------------------------------------
ClsPLMUtilities ();
virtual ~ClsPLMUtilities ();

//
// TODO: Add your methods for this class here.
//
static HRESULT GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
											    const CATListOfCATUnicodeString &listOfValues ,
											    const CATUnicodeString &iStrPLMType ,
											    CATListPtrCATAdpQueryResult & opQueryResults);

static HRESULT OpenUniquePLMComponent (const CATUnicodeString &istrPLMType,
									   const CATUnicodeString& iPLM_ExternalIDValue,
									   const CATUnicodeString& iV_versionValue,
									   const IID& iIID,
									   void **opiPLMComp,
									   CATOmbLifeCycleRootsBag &iBag,
									   CATBoolean iExpandAll);

static HRESULT OpenPLMComponent (const CATUnicodeString &istrPLMType,
								 const CATListOfCATString &listAttrName,
								 const CATLISTV(CATUnicodeString) &ListAttrValue,
								 const IID& iIID,
								 void **opiPLMComp,
								 CATOmbLifeCycleRootsBag &iBag,
								 CATBoolean iExpandAll);

static HRESULT AddChldProduct(const CATIPLMNavReference_var &ispParentProRef,
							  const CATIPLMNavReference_var &ispChildProRef,
							  CATBaseUnknown_var &ospProdInstanceObj);
//create Product Reference
static HRESULT CreateProdReference(const CATUnicodeString &istrPrdType,CATIPLMNavReference_var &ospCreatedProRef);

//Create 3DPart Reference
static HRESULT Create3DPart(const CATUnicodeString &istrPrdType,CATIPLMNavReference_var &ospCreatePrdRef);
//-------------------------------------------------------------------------
// RetrievePLMType (for DS Types and Specialization Types)
//-------------------------------------------------------------------------
static HRESULT RetrievePLMType (const CATUnicodeString & isPLMType, CATIType_var & ospType);

private:
// Copy constructor and equal operator
// -----------------------------------
ClsPLMUtilities (ClsPLMUtilities &);
ClsPLMUtilities& operator=(ClsPLMUtilities&);

};

//-----------------------------------------------------------------------

#endif
