//===================================================================
// COPYRIGHT ATOZ 2020/11/23
//===================================================================
// ClsUniversalOperationFunc.cpp
// Header definition of class ClsUniversalOperationFunc
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/11/23 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef ClsUniversalOperationFunc_H
#define ClsUniversalOperationFunc_H

#include "ATOZDrawingPubFunc.h"

//system includes
#include "CATUnicodeString.h"
#include "CATCommand.h"
#include "CATBaseUnknown.h"   
#include "CATGetEnvValue.h"
#include "CATLib.h"   
#include "CATListOfCATUnicodeString.h"
#include "CATError.h" 

//AfrFoundation includes
#include "CATApplicationFrame.h"
#include "CATFrmEditor.h"
#include "CATFrmLayout.h"
#include "CATFrmWindow.h"
//Dialog includes
#include "CATDlgNotify.h"

//AfrNavigator includes
#include "CATFrmNavigGraphicWindow.h"
#include "CATNavigBox.h"

//CATIAApplicationFrame includes
#include "CATCafCenterGraph.h"
//CATPLMComponentInterfaces includes
#include "CATIPLMNavReference.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"
#include "CATPLMComponentInterfacesServices.h"

//CATPLMIdentificationAccess includes
#include "CATIPLMComponent.h"
#include "CATIAdpType.h"
#include "CATPLMTypeServices.h"
#include "CATListPtrCATIPLMComponent.h"

//PLMDictionaryNavServices includes
#include "CATCkePLMNavPublicServices.h"

//CAT3DPhysicalRepInterfaces includes
#include "CATIPsiRepresentationLoadMode.h"

//CATMecModLiveUseItf includes
#include "CATIMmiUsePrtPart.h"
#include "CATIMmiPrtContainer.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATIPartRequest.h"
#include "CATIBodyRequest.h"

//CATMecModUseItf inlcudes
#include "CATIMmiUseSetFactory.h"
#include "CATIMmiUseMfBRep.h"
#include "CATIMmiUseGeometricalElement.h"

//DataCommonProtocolUse includes
#include "DataCommonProtocolServices.h"
#include "CATIUseEntity.h"

//VisualizationInterfaces includes
#include "CATPathElement.h"
#include "CATIBuildPath.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATIVisProperties.h"
#include "CATVisPropertiesValues.h"
#include "CATModifyVisProperties.h"

//VisualizationController includes
#include "CATViewer.h"
#include "CAT3DViewer.h"
//ObjectModelerNavigator includes
#include "CATIRedrawEvent.h"

//SGInfra includes
#include "CAT3DViewpoint.h"
#include "CAT3DBoundingSphere.h"
#include "CAT3DViewpoint.h"
#include "CATSupport.h"
//Mathematics includes
#include "CATMathPointf.h"
#include "CATMathBox.h"

//SGManager includes
#include "CATHSO.h"

//ObjectModelerSystem includes
#include "CATIAlias.h"

//KnowledgeInterfaces includes
#include "CATICkeObject.h"
#include "CATCkeObjectAttrReadServices.h"
#include "CATIType.h"
#include "CATAttributeInfos.h"
#include "CATListValCATAttributeInfos.h"

//GMModelInterfaces includes
#include "CATBody.h"

//CATMecModUseItf 
#include "CATIMmiUseCreateImport.h"
#include "CATMmiUseServicesFactory.h"

//VisualizationInterfaces 
#include "CATIVisProperties.h"
#include "CATVisPropertiesValues.h"
#include "CATIModelEvents.h"
#include "CATModifyVisProperties.h"

//ObjectModelerNavigator 
#include "CATIRedrawEvent.h"

#include "CATOmbLifeCycleRootsBag.h"
#include "CATLISTP_CATAdpQueryResult.h"
#include "CATAdpOpenParameters.h"
#include "CATAdpOpener.h"
#include "CATIAdpPLMIdentificator.h"
#include "CATAdpAttributeSet.h"
#include "CATAdpPLMQueryServices.h"
#include "CATCkePLMNavSpecializationAccessPublicServices.h"
#include "CATAdpPLMQueryAttributeSet.h"
#include "CATAdpPLMComponentsInfos.h"
#include "CATAdpPLMQueryFilter.h"
#include "CATAdpPLMExtendedQueryServices.h"
#include "CATAdpPLMComponentInfos.h"
#include "CATAdpPLMComponentUniqueKey.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMOpenServices.h"
#include "CATPLMOpenServicesFactory.h"
#include "CATISktUse2DWFFactory.h"
#include "CATISktUseSketch.h"
#include "CATIPrdObject.h"
#include "CATIPrdPublications.h"
#include "CATIPrdPublication.h"
#include "CATIPsiRepresentationReference.h"
#include "CATIPLMRepInstances.h"
#include "CATIPrdIterator.h"
#include "CATFmtPath.h"
#include "CATFmtPathFactory.h"
#include "CATFmtListOfPath.h"
#include "CATIPLMProducts.h"
#include "CATIPLMNavInstance.h"
#include "CATOmbObjectInContext.h"
#include "CATPathOfFirstInstances.h"
#include "CATIPLMUpdateEngine.h"
#include "CATPLMUpdateFactory.h"
#include "CATListPtrCATIPLMNavOccurrence.h"
#include "CATIPrd3DPartReferenceFactory.h"
#include "CATPrdFactory.h"
#include <iostream>

using namespace std;

ExportedByATOZDrawingPubFunc
void Get_current_viewer(CATViewer *& pCurrentViewer);

//get RootNavRef
ExportedByATOZDrawingPubFunc
HRESULT RetrieveRootProd(CATIPLMNavReference_var &ospRootNavRef);
//Get PartObject
ExportedByATOZDrawingPubFunc
HRESULT GetPartObject(const CATIPLMNavReference_var &ispPLMNavRef, CATIMmiUsePrtPart_var &ospPrtPart);

ExportedByATOZDrawingPubFunc
void  Send_Message(CATUnicodeString strMessage, CATUnicodeString strTitle = CATUnicodeString("Prompt"));

ExportedByATOZDrawingPubFunc
HRESULT CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU);

ExportedByATOZDrawingPubFunc
HRESULT DeleteAnything(CATBaseUnknown_var spDeleteObjectBU);

//get object fullpath
ExportedByATOZDrawingPubFunc
CATUnicodeString RetrievefullPathOfObj(CATBaseUnknown* pObject);

//extract object pathelement
ExportedByATOZDrawingPubFunc
CATPathElement* ExtractPathElement(CATBaseUnknown* pObject);

//printf object fullpath
ExportedByATOZDrawingPubFunc
void PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName);

//add highlightObject
ExportedByATOZDrawingPubFunc
void AddHighlightRelatedObj(CATBaseUnknown* pObject);

//redraw spectree
ExportedByATOZDrawingPubFunc
HRESULT RedrawSpecTree(const CATIPLMNavReference_var &iNodeProd);

//Check reference is parttype
ExportedByATOZDrawingPubFunc
HRESULT Check3DPart(const CATIPLMNavReference_var ispNavReference, CATBoolean & oIsA3DPart);

//get PLMComponent type
ExportedByATOZDrawingPubFunc
HRESULT RetrieveComponentType(const CATBaseUnknown_var &ispPLMObject, CATUnicodeString &ostrType);

//get component allAttrs
ExportedByATOZDrawingPubFunc
HRESULT DisplayAttributes(CATIPLMComponent* ipPLMComp);

//get component attrValues
ExportedByATOZDrawingPubFunc
HRESULT GetAttributes(CATIPLMComponent* ipPLMComp,
	CATListOfCATUnicodeString &strListOfName,
	CATListOfCATUnicodeString &strListOfValue);

//Create geoSet under the part
ExportedByATOZDrawingPubFunc
HRESULT CAAGsiCreateGeometricFeatureSets(CATIMmiUsePrtPart_var spPrtPart,
	CATUnicodeString strGSMName,
	CATIMmiMechanicalFeature_var &ospGsmTool);

//Create geoSet under the GeoSet
ExportedByATOZDrawingPubFunc
HRESULT CAAGsiCreateSonGeometricFeatureSets(CATIMmiUsePrtPart_var spPrtPart,
	const CATIMmiMechanicalFeature_var &spParentGSMTool,
	CATUnicodeString strGSMName,
	CATIMmiMechanicalFeature_var &ospGsmTool);

//get the geoset under the part
ExportedByATOZDrawingPubFunc
HRESULT CAAGsiGetGeometricFeatureSets(CATIMmiUsePrtPart_var spPrtPart,
	CATUnicodeString strGSMName,
	CATIMmiMechanicalFeature_var &ospGsmTool);

//get the geoset under the geoset
ExportedByATOZDrawingPubFunc
HRESULT CAAGsiGetSonGeometricFeatureSets(const CATIMmiMechanicalFeature_var &ispParentTool,
	CATUnicodeString strGSMName,
	CATIMmiMechanicalFeature_var &ospGsmTool);

ExportedByATOZDrawingPubFunc
void ViewReframe(CAT3DViewer* p3DViewer, CAT3DRep* p3DBagRep);

//get topbody of the feature
ExportedByATOZDrawingPubFunc
CATBody_var GetBodyFromFeature(const CATIMmiMechanicalFeature_var& ispFeature);

//reframe specobject center
ExportedByATOZDrawingPubFunc
void ReFrameSpecObjCenter(const CATIMmiMechanicalFeature_var &ispSpecObject);

//get the Feature BoundingBox
ExportedByATOZDrawingPubFunc
HRESULT BoundingShape(const CATIMmiMechanicalFeature_var &ispSpecObject, double oBoxCord[6]);

//add highlightObject
ExportedByATOZDrawingPubFunc
void AddHighlightRelatedObj(CATBaseUnknown* pObject);

//清空所有高亮
ExportedByATOZDrawingPubFunc
void ClearSO();

//高亮CATPathElement对象
ExportedByATOZDrawingPubFunc
void HighlightPathElemObj(CATBaseUnknown* pObject);

//get the Feature BoundingBox
ExportedByATOZDrawingPubFunc
CATBoolean CenterGraphOnObject();

ExportedByATOZDrawingPubFunc
HRESULT CopyObjectIntoSpecGeoTool(CATIMmiMechanicalFeature_var  spGeometryTool, CATBaseUnknown_var ispSelSketchReferPlaneBU, CATIMmiMechanicalFeature_var &ospResult);

ExportedByATOZDrawingPubFunc
HRESULT SetSpecObjShowAttr(const CATIMmiMechanicalFeature_var &ispFeature, CATUnicodeString iShowOrHide);

ExportedByATOZDrawingPubFunc
HRESULT SetSpecLineObjColor(const CATIMmiMechanicalFeature_var &ispFeature, int iColor);

//消息类型：Error、Information、Warning
ExportedByATOZDrawingPubFunc
int DisplayMessage(const CATString &istrMsgType,
	               const CATUnicodeString &iusMsgToDisplay,
	               const CATUnicodeString &iusDlgTitle);

ExportedByATOZDrawingPubFunc
HRESULT OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATListOfCATString &listAttrName,
	const CATLISTV(CATUnicodeString) &ListAttrValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll);

ExportedByATOZDrawingPubFunc
HRESULT GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	const CATListOfCATUnicodeString &listOfValues,
	const CATUnicodeString &iStrPLMType,
	CATListPtrCATAdpQueryResult & opQueryResults);

ExportedByATOZDrawingPubFunc
HRESULT RetrievePLMType(const CATUnicodeString & isPLMType,
	CATIType_var & ospType);

ExportedByATOZDrawingPubFunc
HRESULT OpenUniquePLMComponent(const CATUnicodeString &istrPLMType,
	const CATUnicodeString& iPLM_ExternalIDValue,
	const CATUnicodeString& iV_versionValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll);
ExportedByATOZDrawingPubFunc
HRESULT OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATUnicodeString &iPLM_ExternalIDValue,
	const CATUnicodeString &iV_versionValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll);

ExportedByATOZDrawingPubFunc
HRESULT GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart,
	CATIPLMNavOccurrence_var &ospParentOccurr);

ExportedByATOZDrawingPubFunc
HRESULT OpenObjInSession(CATBaseUnknown_var& ispTargetObj);

ExportedByATOZDrawingPubFunc
HRESULT Get2DWFFactory(CATISktUse2DWFFactory_var &ospCATISktUse2DWFFactory, CATISktUseSketch_var &ospSketch);

ExportedByATOZDrawingPubFunc
HRESULT GetPartRepRef(const CATIPLMNavReference_var &ispPLMNavRef, CATIPLMNavRepReference_var &ospPrtRepRef);

ExportedByATOZDrawingPubFunc
HRESULT GetPublicationByName(const CATIPrdObject_var ispProduct, const CATUnicodeString iPublicationName, CATBaseUnknown_var &ospPublication);

ExportedByATOZDrawingPubFunc
CATBoolean IsA3DShape(CATBaseUnknown_var ispRepresentation);

ExportedByATOZDrawingPubFunc
HRESULT Get3DShapes(CATIPrdObject_var ispProduct, CATFmtListOfPath &oList3DShapes);

ExportedByATOZDrawingPubFunc
HRESULT GetPartReferenceByName(CATIPLMNavReference *ipNavRef, const CATUnicodeString iPrdInstanceName, CATIPLMNavReference *&oPartReference);

ExportedByATOZDrawingPubFunc
HRESULT GetAppContainerFromPLMNavRef(CATIPLMNavReference * ipiPLMNavReference, CATIMmiPrtContainer *& opiPartContainer, CATIPrdObject *& opiRepInstanceAsPrdObj);

ExportedByATOZDrawingPubFunc
CATBaseUnknown_var GetMainBodyPath(CATIPLMNavReference * ipNavRootRef, const CATUnicodeString iPrdInstanceName, CATIPrdObject *& opiRepInstanceAsPrdObj, CATLISTP(CATIPLMComponent) &oPathOfInstance);

ExportedByATOZDrawingPubFunc
HRESULT Print_OmbObjectInContext(CATUnicodeString Title, CATOmbObjectInContext * piOmbObjectInContext);

ExportedByATOZDrawingPubFunc
HRESULT GetObjectInContextFromPublicationName(const CATIPrdObject_var ispProduct, const CATUnicodeString iPublicationName, CATISimObjectInContext *&opiObjectInContext);

ExportedByATOZDrawingPubFunc
HRESULT LoadRepresentations(CATIPLMNavReference *ipNavRef);

ExportedByATOZDrawingPubFunc
HRESULT RecursiveLoad(CATIPLMNavReference *ipNavRef);

ExportedByATOZDrawingPubFunc
HRESULT GetMechanicalPartFromProduct(const CATIPLMNavOccurrence_var &ispOriginOccurrence, CATIMmiMechanicalFeature_var &ospMechanicalPart);

ExportedByATOZDrawingPubFunc
HRESULT UpdateAll(const CATIPLMNavOccurrence_var &ispRootProduct);

ExportedByATOZDrawingPubFunc
void PrintAllComponentsInSession(CATLISTV(CATIPLMComponent_var) &oList);

ExportedByATOZDrawingPubFunc
bool IsSameComponent(CATBaseUnknown_var &ispInterface1, CATBaseUnknown_var &ispInterface2);

ExportedByATOZDrawingPubFunc
HRESULT GetContainer(const CATIPLMNavReference_var &ispPLMNavRef, CATIMmiPrtContainer_var &iospCont);

ExportedByATOZDrawingPubFunc
HRESULT BrowseOccurrences(CATIPLMNavOccurrence_var &spPLMNavOccOnCurrentNode, CATListPtrCATIPLMNavOccurrence &ChildrenList);

ExportedByATOZDrawingPubFunc
HRESULT CreatePartUnderRoot(const CATIPLMNavReference_var &ispParentRef, CATIPLMNavInstance_var &ospNewPartInst, CATOmbLifeCycleRootsBag &ibag);

ExportedByATOZDrawingPubFunc
HRESULT CAAMmrGetPartFromProduct(CATIPLMNavInstance_var   spNavInstance, CATIPartRequest_var  & ospPartFromProduct);

#endif
