//===================================================================
// COPYRIGHT atoz 2020/10/15
//===================================================================
// ATOZNWHPowerCCmd.cpp
// Header definition of class ATOZNWHPowerCCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/10/15 Creation: Code generated by the 3DS wizard
//===================================================================

#include "ATOZNWHPowerCCmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"


#include "CATCreateExternalObject.h"
CATCreateClass( ATOZNWHPowerCCmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
ATOZNWHPowerCCmd::ATOZNWHPowerCCmd() :
CATStateCommand ("ATOZNWHPowerCCmd", CATDlgEngOneShot, CATCommandModeExclusive)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, _strFeatID("")
, _strFeatVersion("")
, _ModelBag()
, _pATOZNWHPowerCDlg(NULL)
, _pSelCenterLineDlgAgent(NULL)
, _pSelFrontPlaneDlgAgent(NULL)
, _pSelBackPlaneDlgAgent(NULL)
, _pSelCenterPlaneDlgAgent(NULL)
, _pPathElemLine(NULL)
, _pPathElemFrontPlane(NULL)
, _pPathElemBackPlane(NULL)
, _pPathElemCenterPlane(NULL)
, _spCurrentPart(NULL_var)
, _spFeatNavRef(NULL_var)
, _pSelPlanePathElemAgent(NULL)
, _pSelLinePathElemAgent(NULL)
, _listTemplateInstruction(NULL)
{
	HRESULT rc = InitializeConfigData();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}

	rc = InitializeMainDialog();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}
	for (int i = 1; i <= _listTemplateInstruction.Size(); i++)
	{
		_pATOZNWHPowerCDlg->_EditorInstructions->SetLine(_listTemplateInstruction[i]);
	}


	GetCurrentPart(_spCurrentPart);

	DisplayTemplateView();

}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
ATOZNWHPowerCCmd::~ATOZNWHPowerCCmd()
{
	
	_pPathElemLine = NULL;
	_pPathElemCenterPlane = NULL;
	_pPathElemBackPlane = NULL;
	_pPathElemFrontPlane = NULL;


	if (NULL != _pSelPlanePathElemAgent)
	{
		_pSelPlanePathElemAgent->RequestDelayedDestruction();
		_pSelPlanePathElemAgent = NULL;
	}


	if (NULL != _pSelLinePathElemAgent)
	{
		_pSelLinePathElemAgent->RequestDelayedDestruction();
		_pSelLinePathElemAgent = NULL;
	}

	
	if (NULL != _pSelCenterPlaneDlgAgent)
	{
		_pSelCenterPlaneDlgAgent->RequestDelayedDestruction();
		_pSelCenterPlaneDlgAgent = NULL;
	}

	if (NULL != _pSelBackPlaneDlgAgent)
	{
		_pSelBackPlaneDlgAgent->RequestDelayedDestruction();
		_pSelBackPlaneDlgAgent = NULL;
	}

	if (NULL != _pSelFrontPlaneDlgAgent)
	{
		_pSelFrontPlaneDlgAgent->RequestDelayedDestruction();
		_pSelFrontPlaneDlgAgent = NULL;
	}

	if (NULL != _pSelCenterLineDlgAgent)
	{
		_pSelCenterLineDlgAgent->RequestDelayedDestruction();
		_pSelCenterLineDlgAgent = NULL;
	}

	if (NULL != _pATOZNWHPowerCDlg)
	{
		_pATOZNWHPowerCDlg->RequestDelayedDestruction();
		_pATOZNWHPowerCDlg = NULL;
	}

}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void ATOZNWHPowerCCmd::BuildGraph()
{
	_pSelLinePathElemAgent = new CATPathElementAgent("SelectLine");
	_pSelLinePathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelLinePathElemAgent->AddElementType("CATIMfLine");

	_pSelPlanePathElemAgent = new CATPathElementAgent("SelectPlane");
	_pSelPlanePathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelPlanePathElemAgent->AddElementType("CATIMfPlane");

	_pSelCenterLineDlgAgent = new CATDialogAgent("CenterLineDlg");
	_pSelCenterLineDlgAgent->AcceptOnNotify(_pATOZNWHPowerCDlg->_SelectorListCenterLine,
		_pATOZNWHPowerCDlg->_SelectorListCenterLine->GetListSelectNotification());

	_pSelFrontPlaneDlgAgent = new CATDialogAgent("FrontPlaneDlg");
	_pSelFrontPlaneDlgAgent->AcceptOnNotify(_pATOZNWHPowerCDlg->_SelectorListHeadPlane,
		_pATOZNWHPowerCDlg->_SelectorListHeadPlane->GetListSelectNotification());
	
	_pSelBackPlaneDlgAgent = new CATDialogAgent("BackPlaneDlg");
	_pSelBackPlaneDlgAgent->AcceptOnNotify(_pATOZNWHPowerCDlg->_SelectorListTailPlane,
		_pATOZNWHPowerCDlg->_SelectorListTailPlane->GetListSelectNotification());
	
	_pSelCenterPlaneDlgAgent = new CATDialogAgent("CenterPlaneDlg");
	_pSelCenterPlaneDlgAgent->AcceptOnNotify(_pATOZNWHPowerCDlg->_SelectorListCenterPlane,
		_pATOZNWHPowerCDlg->_SelectorListCenterPlane->GetListSelectNotification());

	CATDialogState * SelectCenterLineState = GetInitialState("Please select center line");
	SelectCenterLineState->AddDialogAgent(_pSelLinePathElemAgent);
	SelectCenterLineState->AddDialogAgent(_pSelFrontPlaneDlgAgent);
	SelectCenterLineState->AddDialogAgent(_pSelBackPlaneDlgAgent);
	SelectCenterLineState->AddDialogAgent(_pSelCenterPlaneDlgAgent);

	CATDialogState * SelectFrontPlaneState = AddDialogState("Please select front plane");
	SelectFrontPlaneState->AddDialogAgent(_pSelPlanePathElemAgent);
	SelectFrontPlaneState->AddDialogAgent(_pSelCenterLineDlgAgent);
	SelectFrontPlaneState->AddDialogAgent(_pSelBackPlaneDlgAgent);
	SelectFrontPlaneState->AddDialogAgent(_pSelCenterPlaneDlgAgent);

	CATDialogState * SelectBackPlaneState = AddDialogState("Please select back plane");
	SelectBackPlaneState->AddDialogAgent(_pSelPlanePathElemAgent);
	SelectBackPlaneState->AddDialogAgent(_pSelCenterLineDlgAgent);
	SelectBackPlaneState->AddDialogAgent(_pSelFrontPlaneDlgAgent);
	SelectBackPlaneState->AddDialogAgent(_pSelCenterPlaneDlgAgent);

	CATDialogState * SelectCenterPlaneState = AddDialogState("Please select center plane");
	SelectCenterPlaneState->AddDialogAgent(_pSelPlanePathElemAgent);
	SelectCenterPlaneState->AddDialogAgent(_pSelCenterLineDlgAgent);
	SelectCenterPlaneState->AddDialogAgent(_pSelFrontPlaneDlgAgent);
	SelectCenterPlaneState->AddDialogAgent(_pSelBackPlaneDlgAgent);

	//SelectCenterLineState 选择顶面中心线
	AddTransition(SelectCenterLineState, SelectCenterLineState,
		IsOutputSetCondition(_pSelLinePathElemAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::SelectCenterLineObj));

	AddTransition(SelectCenterLineState, SelectFrontPlaneState,
		IsOutputSetCondition(_pSelFrontPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	AddTransition(SelectCenterLineState, SelectBackPlaneState,
		IsOutputSetCondition(_pSelBackPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	AddTransition(SelectCenterLineState, SelectCenterPlaneState,
		IsOutputSetCondition(_pSelCenterPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	//SelectFrontPlaneState 前限制面
	AddTransition(SelectFrontPlaneState, SelectFrontPlaneState,
		IsOutputSetCondition(_pSelPlanePathElemAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::SelectFrontPlaneObj));

	AddTransition(SelectFrontPlaneState, SelectCenterLineState,
		IsOutputSetCondition(_pSelCenterLineDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	AddTransition(SelectFrontPlaneState, SelectBackPlaneState,
		IsOutputSetCondition(_pSelBackPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	AddTransition(SelectFrontPlaneState, SelectCenterPlaneState,
		IsOutputSetCondition(_pSelCenterPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	//SelectBackPlaneState 后限制面
	AddTransition(SelectBackPlaneState, SelectBackPlaneState,
		IsOutputSetCondition(_pSelPlanePathElemAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::SelectBackPlaneObj));

	AddTransition(SelectBackPlaneState, SelectCenterLineState,
		IsOutputSetCondition(_pSelCenterLineDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	AddTransition(SelectBackPlaneState, SelectFrontPlaneState,
		IsOutputSetCondition(_pSelFrontPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	AddTransition(SelectBackPlaneState, SelectCenterPlaneState,
		IsOutputSetCondition(_pSelCenterPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));


	//SelectCenterPlaneState 选择对称面
	AddTransition(SelectCenterPlaneState, SelectCenterPlaneState,
		IsOutputSetCondition(_pSelPlanePathElemAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::SelectCenterPlaneObj));

	AddTransition(SelectCenterPlaneState, SelectFrontPlaneState,
		IsOutputSetCondition(_pSelFrontPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	AddTransition(SelectCenterPlaneState, SelectBackPlaneState,
		IsOutputSetCondition(_pSelBackPlaneDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));

	AddTransition(SelectCenterPlaneState, SelectCenterLineState,
		IsOutputSetCondition(_pSelCenterLineDlgAgent),
		Action((ActionMethod)&ATOZNWHPowerCCmd::CleanDialogAgent));



	//click Wndclose buttion
	AddAnalyseNotificationCB(_pATOZNWHPowerCDlg,
		_pATOZNWHPowerCDlg->GetWindCloseNotification(),
		(CATCommandMethod)&ATOZNWHPowerCCmd::ExitCmd, NULL);
	//click cancel button
	AddAnalyseNotificationCB(_pATOZNWHPowerCDlg,
		_pATOZNWHPowerCDlg->GetDiaCANCELNotification(),
		(CATCommandMethod)&ATOZNWHPowerCCmd::ExitCmd, NULL);

	//click OK button
	AddAnalyseNotificationCB(_pATOZNWHPowerCDlg,
		_pATOZNWHPowerCDlg->GetDiaOKNotification(),
		(CATCommandMethod)&ATOZNWHPowerCCmd::OKAction, NULL);


}

HRESULT ATOZNWHPowerCCmd::InitializeConfigData()
{
	CATUnicodeString strInstallPath("");
	ClsConfigXMLServices::Get_ComputeDataExePath(strInstallPath);
	if (CATUnicodeString("") == strInstallPath) return E_FAIL;

	CATUnicodeString strProjectConfigPath = strInstallPath + "bin\\\ATOZ\\CAAEKLConfig";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		DisplayMessage("Error", "找不到CAAEKLConfig配置文件夹!", "ERROR");
		return E_FAIL;
	}

	const char* pxmlfilePath = CATFindPath("CAAPCConfig.xml", strProjectConfigPath);
	if (NULL == pxmlfilePath)
	{
		DisplayMessage("Error", "找不到CAAPCConfig.xml配置文件!", "ERROR");
		return E_FAIL;
	}

	CATUnicodeString strXMLFilePath = pxmlfilePath;
	HRESULT rc = ClsConfigXMLServices::GetCUPSConfigData(strXMLFilePath, "栈桥", _strFeatID,_strFeatVersion);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "读取CAAEKLConfig.xml配置文件失败!", "ERROR");
		return E_FAIL;
	}

	strProjectConfigPath = strInstallPath + "bin\\\ATOZ";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		DisplayMessage("Error", "找不到ATOZ配置文件夹!", "ERROR");
		return E_FAIL;
	}
	else
	{
		const char* pfilePath = CATFindPath("TemplateInstruction_4.ini", strProjectConfigPath);
		if (NULL != pfilePath)
		{
			ClsConfigXMLServices::ReadTemplateText(pfilePath, _listTemplateInstruction);
			for (int i = 1; i <= _listTemplateInstruction.Size(); i++)
			{
				cout << "_listTemplateInstruction["<<i<<"] == "<< _listTemplateInstruction[i] << endl;
			}
		}
	}

	return S_OK;
}

//消息类型：Error、Information、Warning
int ATOZNWHPowerCCmd::DisplayMessage(const CATString &istrMsgType,
	const CATUnicodeString &iusMsgToDisplay,
	const CATUnicodeString &iusDlgTitle)
{

	int RetUserReply = 0;

	CATDlgStyle Dlgstyle;
	CATUnicodeString usDlgTitle = "";

	if (istrMsgType == "Error")
	{
		Dlgstyle = CATDlgNfyError | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Error";
	}
	else if (istrMsgType == "Information")
	{
		Dlgstyle = CATDlgNfyInformation | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Information";
	}
	else if (istrMsgType == "Warning")
	{
		Dlgstyle = CATDlgNfyWarning | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Warning";
	}

	if (iusDlgTitle != "")usDlgTitle = iusDlgTitle;

	CATDlgNotify* pDlgNotify = new CATDlgNotify((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(), istrMsgType, Dlgstyle);
	if (!pDlgNotify) return 0;

	RetUserReply = pDlgNotify->DisplayBlocked(iusMsgToDisplay, usDlgTitle); // Get the User selected button
	return RetUserReply;
}

HRESULT ATOZNWHPowerCCmd::InitializeMainDialog()
{
	_pATOZNWHPowerCDlg = new ATOZNWHPowerCDlg((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
		"PowerCopyDlg");
	_pATOZNWHPowerCDlg->Build();

	_pATOZNWHPowerCDlg->_SpinnerWDJD->SetValue(3.0f);
	_pATOZNWHPowerCDlg->_SpinnerWDLength->SetValue(3.86f);
	_pATOZNWHPowerCDlg->_SpinnerZJLength->SetValue(6.0f);


	_pATOZNWHPowerCDlg->_SpinnerWidth->SetValue(4.769f);
	_pATOZNWHPowerCDlg->_SpinnerHeight->SetValue(3.442f);
	_pATOZNWHPowerCDlg->_SpinnerWinHeight->SetValue(1.5f);
	_pATOZNWHPowerCDlg->_SpinnerWinUDloc->SetValue(1.2f);

	_pATOZNWHPowerCDlg->_SpinnerWinFBLoc->SetValue(0.75f);
	_pATOZNWHPowerCDlg->_SpinnerWDHalfWid->SetValue(2.566f);
	_pATOZNWHPowerCDlg->_SpinnerWinWidth->SetValue(0.9f);
	_pATOZNWHPowerCDlg->_SpinnerWall->SetValue(0.0625f);
	
	_pATOZNWHPowerCDlg->_SpinnerZLCount->SetValue(8);

	_pATOZNWHPowerCDlg->_LabelLog->SetIconName("I_ZMXALog");

	_pATOZNWHPowerCDlg->SetVisibility(CATDlgShow);
	return S_OK;
}

HRESULT ATOZNWHPowerCCmd::GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart)
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL == pFrmEditor) return E_FAIL;

	CATPathElement& CurrentElemPath = pFrmEditor->GetUIActiveObject();
	CATBaseUnknown* pCurrentObject = CurrentElemPath.FindElement(IID_CATIMmiUsePrtPart);
	if (NULL != pCurrentObject)
	{
		ospPrtPart = pCurrentObject;
	}
	

	return S_OK;
}

HRESULT ATOZNWHPowerCCmd::DisplayTemplateView()
{
	//判断项目中是否存在物料
	CATLISTV(CATString)        listAttrName;
	CATLISTV(CATUnicodeString) listAttrValue;
	listAttrName.Append("PLM_ExternalID");
	listAttrName.Append("revision");

	listAttrValue.Append(_strFeatID);
	listAttrValue.Append(_strFeatVersion);
	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	GetPLMObjectsFromAttrAndFromType(listAttrName, listAttrValue, "VPMReference", listQueryResult);
	if (listQueryResult.Size() > 0)
	{
		CATBoolean authoringMode = TRUE;
		CATIPLMNavReference* piProductRef = NULL;
		OpenPLMComponent("VPMReference", listAttrName, listAttrValue,
			IID_CATIPLMNavReference, (void**)&piProductRef, _ModelBag, authoringMode);
		if (NULL != piProductRef)
		{
			//CATIPLMComponent_var spPLMComponent = piProductRef;
			//if (NULL_var != spPLMComponent)
			//{
			//	PrintComponentAttrs(spPLMComponent);
			//}
		
			CATIPrdOccurrenceMngt* piOccurrMngt = NULL;
			if (SUCCEEDED(CATPrdGetOccurrenceMngt(piOccurrMngt)) && piOccurrMngt)
			{
				CATIPLMNavOccurrence_var spPrdOccurr = NULL_var;
				piOccurrMngt->GetOrCreateRootOccurrence(piProductRef, spPrdOccurr);
				if (NULL_var != spPrdOccurr)
				{
					CATFrmEditor * pEditor = CATFrmEditor::GetCurrentEditor();
					CATVisManager * pVisuManager = CATVisManager::GetVisManager();
					CATCommand * pCommandSelector = (CATCommand*)pEditor->GetCommandSelector();
					list<IID> ListIVisu3d;
					IID visu3d = IID_CATI3DGeoVisu;
					ListIVisu3d.fastadd(&visu3d);
					CATPathElement*  pRootObjectPath = new CATPathElement(spPrdOccurr);
					CATViewpoint*  pModelViewPoint = (CATViewpoint*)&(_pATOZNWHPowerCDlg->_Nav3DViewerModel->GetMain3DViewpoint());
					HRESULT rc = pVisuManager->AttachTo(pRootObjectPath, pModelViewPoint, ListIVisu3d, pCommandSelector);

					_pATOZNWHPowerCDlg->_Nav3DViewerModel->Draw();
					_pATOZNWHPowerCDlg->_Nav3DViewerModel->Reframe();
				}

				piOccurrMngt->Release(); piOccurrMngt = NULL;
			}
			_spFeatNavRef = piProductRef;
			piProductRef->Release(); piProductRef = NULL;
		}
	}

	return S_OK;
}

HRESULT ATOZNWHPowerCCmd::GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	const CATListOfCATUnicodeString &listOfValues,
	const CATUnicodeString &iStrPLMType,
	CATListPtrCATAdpQueryResult & opQueryResults)
{
	HRESULT hr = S_OK;
	//cout << "   GetPLMObjectsFromAttrAndFromType " << endl;

	if ((0 == listOfAttribute.Size()) || (0 == listOfValues.Size())) return E_INVALIDARG;
	if (listOfAttribute.Size() != listOfValues.Size()) return E_INVALIDARG;
	if (0 < opQueryResults.Size())return E_INVALIDARG;


	int iListSize = listOfAttribute.Size();

	CATAdpAttributeSet iAttributeSet;
	//cout << "   Build an Attribute set with inputs from user, for query into db" << endl;
	int i = 1;
	while ((i <= iListSize) && (SUCCEEDED(hr)))
	{
		CATUnicodeString Name = listOfAttribute[i].CastToCharPtr();
		const CATString AttributeINPUT = CATCkePLMNavPublicServices::RetrieveBasicAttributeNameFromPreviousOne(NULL_var, Name).CastToCharPtr();
		CATUnicodeString AttrValue = listOfValues[i];

		hr = iAttributeSet.AddAttribute(AttributeINPUT, AttrValue);
		i++;
	}

	CATIType_var spTypeObj = NULL_var;
	hr = RetrievePLMType(iStrPLMType, spTypeObj);
	if (FAILED(hr) || (NULL_var == spTypeObj))
	{
		cout << "ERROR:ClsPLMUtilities::GetPLMObjectsFromAttrAndFromType()-NULL_var == spTypeObj" << endl;
		return E_FAIL;
	}


	hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spTypeObj,
		iAttributeSet,
		opQueryResults);

	return hr;
}

HRESULT ATOZNWHPowerCCmd::RetrievePLMType(const CATUnicodeString & isPLMType,
	CATIType_var & ospType)
{
	HRESULT rc = E_INVALIDARG;
	if (isPLMType != "")
	{
		// For DS type
		rc = CATCkePLMNavPublicServices::RetrieveKnowledgeType(isPLMType, ospType);
		// For Specialization Type
		if (FAILED(rc))  rc = CATCkePLMNavSpecializationAccessPublicServices::RetrieveSpecializationType(isPLMType, ospType);
	}
	return rc;
}

HRESULT ATOZNWHPowerCCmd::OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATListOfCATString &listAttrName,
	const CATLISTV(CATUnicodeString) &ListAttrValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll)
{
	HRESULT hr = S_OK;
	if (CATUnicodeString("") == istrPLMType) return E_FAIL;
	if (0 == listAttrName.Size()) return E_FAIL;
	if (0 == ListAttrValue.Size()) return E_FAIL;

	int iListSize = listAttrName.Size();

	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	hr = GetPLMObjectsFromAttrAndFromType(listAttrName, ListAttrValue, istrPLMType, listQueryResult);
	if (FAILED(hr) || (0 == listQueryResult.Size()))
	{

		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-0 == listQueryResult.Size()" << endl;
		return hr;
	}

	CATIAdpPLMIdentificator* piAdpPLMIdentificator = NULL;
	listQueryResult[1]->GetIdentifier(piAdpPLMIdentificator);
	if (NULL == piAdpPLMIdentificator)
	{
		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-NULL == piAdpPLMIdentificator" << endl;
		return E_FAIL;
	}

	if (TRUE == iExpandAll)
	{
		CATAdpOpenParameters params_Auth(CATAdpExpandParameters::Authoring);
		CATAdpOpener opener_Auth(iBag, params_Auth);
		// 5.2. Open the Retrieved Component by using CATAdpOpener
		hr = opener_Auth.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	else
	{
		CATAdpOpenParameters params_Nav(CATAdpExpandParameters::OneLevelRepresentations);
		CATAdpOpener opener_Nav(iBag, params_Nav);
		hr = opener_Nav.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	piAdpPLMIdentificator->Release();
	piAdpPLMIdentificator = NULL;

	return S_OK;
}

void ATOZNWHPowerCCmd::SelectCenterLineObj(void* idata)
{
	_pPathElemLine = _pSelLinePathElemAgent->GetValue();
	_pSelLinePathElemAgent->InitializeAcquisition();

	ClearSO();
	HighlightPathElemObj(_pPathElemLine);

	CATUnicodeString strFullPath("");
	PathElementString(_pPathElemLine, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pATOZNWHPowerCDlg->_SelectorListCenterLine;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL == _pPathElemFrontPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListHeadPlane->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pPathElemBackPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListTailPlane->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pPathElemCenterPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListCenterPlane->SetSelect(ArraySel, 1);
	}
}

void ATOZNWHPowerCCmd::SelectFrontPlaneObj(void* idata)
{
	_pPathElemFrontPlane = _pSelPlanePathElemAgent->GetValue();
	_pSelPlanePathElemAgent->InitializeAcquisition();

	ClearSO();
	HighlightPathElemObj(_pPathElemFrontPlane);

	CATUnicodeString strFullPath("");
	PathElementString(_pPathElemFrontPlane, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pATOZNWHPowerCDlg->_SelectorListHeadPlane;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL == _pPathElemLine)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListCenterLine ->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pPathElemBackPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListTailPlane->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pPathElemCenterPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListCenterPlane->SetSelect(ArraySel, 1);
	}
}

void ATOZNWHPowerCCmd::SelectBackPlaneObj(void* idata)
{
	_pPathElemBackPlane = _pSelPlanePathElemAgent->GetValue();
	_pSelPlanePathElemAgent->InitializeAcquisition();

	ClearSO();
	HighlightPathElemObj(_pPathElemBackPlane);

	CATUnicodeString strFullPath("");
	PathElementString(_pPathElemBackPlane, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pATOZNWHPowerCDlg->_SelectorListTailPlane;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL == _pPathElemLine)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListCenterLine->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pPathElemFrontPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListHeadPlane->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pPathElemCenterPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListCenterPlane->SetSelect(ArraySel, 1);
	}
}

void ATOZNWHPowerCCmd::SelectCenterPlaneObj(void* idata)
{
	_pPathElemCenterPlane = _pSelPlanePathElemAgent->GetValue();
	_pSelPlanePathElemAgent->InitializeAcquisition();

	ClearSO();
	HighlightPathElemObj(_pPathElemCenterPlane);

	CATUnicodeString strFullPath("");
	PathElementString(_pPathElemCenterPlane, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pATOZNWHPowerCDlg->_SelectorListCenterPlane;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL == _pPathElemLine)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListCenterLine->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pPathElemBackPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListTailPlane->SetSelect(ArraySel, 1);
	}
	else if (NULL == _pPathElemFrontPlane)
	{
		int ArraySel[1] = { 0 };
		_pATOZNWHPowerCDlg->_SelectorListHeadPlane->SetSelect(ArraySel, 1);
	}
}

void ATOZNWHPowerCCmd::CleanDialogAgent()
{
	if (_pSelCenterLineDlgAgent->IsOutputSet())
	{
		_pSelCenterLineDlgAgent->InitializeAcquisition();
		_pATOZNWHPowerCDlg->_SelectorListHeadPlane->ClearSelect();
		_pATOZNWHPowerCDlg->_SelectorListTailPlane->ClearSelect();
		_pATOZNWHPowerCDlg->_SelectorListCenterPlane->ClearSelect();
	}
	if (_pSelFrontPlaneDlgAgent->IsOutputSet())
	{
		_pSelFrontPlaneDlgAgent->InitializeAcquisition();
		_pATOZNWHPowerCDlg->_SelectorListCenterLine->ClearSelect();
		_pATOZNWHPowerCDlg->_SelectorListTailPlane->ClearSelect();
		_pATOZNWHPowerCDlg->_SelectorListCenterPlane->ClearSelect();
	}
	if (_pSelBackPlaneDlgAgent->IsOutputSet())
	{
		_pSelBackPlaneDlgAgent->InitializeAcquisition();
		_pATOZNWHPowerCDlg->_SelectorListCenterLine->ClearSelect();
		_pATOZNWHPowerCDlg->_SelectorListHeadPlane->ClearSelect();
		_pATOZNWHPowerCDlg->_SelectorListCenterPlane->ClearSelect();
	}
	if (_pSelCenterPlaneDlgAgent->IsOutputSet())
	{
		_pSelCenterPlaneDlgAgent->InitializeAcquisition();
		_pATOZNWHPowerCDlg->_SelectorListCenterLine->ClearSelect();
		_pATOZNWHPowerCDlg->_SelectorListHeadPlane->ClearSelect();
		_pATOZNWHPowerCDlg->_SelectorListTailPlane->ClearSelect();
	}
}
void ATOZNWHPowerCCmd::ExitCmd(void* idata)
{
	this->RequestDelayedDestruction();
	return;
}

void ATOZNWHPowerCCmd::OKAction(void* idata)
{
	if (NULL == _pPathElemLine)
	{
		DisplayMessage("Warning", "请选择顶面中心线!", "警告");
		return;
	}
	if (NULL == _pPathElemFrontPlane)
	{
		DisplayMessage("Warning", "请选择前限制面!", "警告");
		return;
	}
	if (NULL == _pPathElemBackPlane)
	{
		DisplayMessage("Warning", "请选择后限制面!", "警告");
		return;
	}
	if (NULL == _pPathElemCenterPlane)
	{
		DisplayMessage("Warning", "请选择对称面!", "警告");
		return;
	}
	
	HRESULT rc = E_FAIL;
	if (NULL_var == _spFeatNavRef)
	{ 
		DisplayMessage("Warning", "NULL_var == _spFeatProductNavRef", "警告");
		return;
	}

	//获取container
	CATIMmiPrtContainer *pIPrtContOnPC(NULL);
	CATIPLMComponent *piPLMCompOnFeatRef(NULL);
	rc = GetUDFContainerFromDB(_ModelBag, _spFeatNavRef, piPLMCompOnFeatRef, pIPrtContOnPC);
	if (FAILED(rc) || NULL == pIPrtContOnPC || NULL == piPLMCompOnFeatRef)
	{
		DisplayMessage("Warning", "GetUDFContainerFormDB is failed!!", "警告");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - GetUDFContainerFormDB is failed!" << endl;
		return;
	}
	
	CATIPLMComponent_var spiPLMCompOnFeatRef(NULL_var);
	spiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;
	
	
	
	//获取结构树上超级副本
	CATLISTV(CATIUdfInstantiate_var) iListOfPCReferences;
	rc = CATTemplatesAccessServices::GetPowerCopyList(pIPrtContOnPC, iListOfPCReferences);
	
	pIPrtContOnPC->Release();
	pIPrtContOnPC = NULL;
	
	if (0 == iListOfPCReferences.Size())
	{
		DisplayMessage("Warning", "0 == iListOfPCReferences.Size()!", "警告");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - UDF Number is 0!" << endl;
		return;
	}
	
	CATIUdfInstantiate_var hIUdfInstantiate(NULL_var);
	hIUdfInstantiate = iListOfPCReferences[1];
	CATIAlias_var spAlias = hIUdfInstantiate;
	if (NULL_var == spAlias)
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - spAlias is NULL!" << endl;
		return;
	}
	CATUnicodeString strUDFAlias = spAlias->GetAlias();
	cout << "UDF or PowerCopy Name == " << strUDFAlias << endl;
	if (NULL_var == spiPLMCompOnFeatRef)
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - spiPLMCompOnFeatRef is NULL!" << endl;
		return;
	}
	if (NULL_var == hIUdfInstantiate)
	{
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - hIUdfInstantiate is NULL!" << endl;
		return;
	}

	//设置实例化位置
	CATBaseUnknown_var spPartRequestBU = _spCurrentPart;
	if (NULL_var == spPartRequestBU)
	{
		DisplayMessage("Error", "NULL_var == spPartRequestBU", "ERROR");
		cout << "Error:NULL_var == spPartRequestBU" << endl;
		return;
	}
	CATBaseUnknown* pPartRequestBU = (CATBaseUnknown*)spPartRequestBU;
	if (NULL == pPartRequestBU)
	{
		cout << "Error:ATOZRDCSICITUDFImportCmd::OutRibUDFImp() - pPartRequestBU is NULL!" << endl;
		return;
	}
	CATPathElement PartRequestPath(pPartRequestBU);

	/*pPartRequestBU->Release();
	pPartRequestBU = NULL;*/

	CATPathElement *pUIactivePath(NULL);
	CATBaseUnknown_var spDestBU(NULL_var);

	rc = hIUdfInstantiate->SetDestinationPath(&PartRequestPath, pUIactivePath, spDestBU);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "SetDestinationPath Failed", "ERROR");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - SetDestinationPath() is failed!" << endl;
		return;
	}
	
	if (NULL != pUIactivePath)
	{
		pUIactivePath->Release();
		pUIactivePath = NULL;
	}
	
	
	//PrintOldInputs(hIUdfInstantiate);
	rc = UDFImpInstantiating(_spCurrentPart, hIUdfInstantiate);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "UDFImpInstantiating Failed", "ERROR");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - SetDestinationPath() is failed!" << endl;
		return;
	}

	//更新模型
	CAAUpdateObject(_spCurrentPart);
	
	if (FAILED(_ModelBag.RemoveAll()))
	{
		DisplayMessage("Warning", "_ModelBag", "警告");
	}

	if (NULL != piPLMCompOnFeatRef)
	{
		piPLMCompOnFeatRef->Release();
		piPLMCompOnFeatRef = NULL;
	}

	CATULong state(0);
	state = _pATOZNWHPowerCDlg->_CheckButton->GetState();
	if (CATULong(CATDlgCheck) == state)
		_pATOZNWHPowerCDlg->Refresh();
	else {
		this->RequestDelayedDestruction();
		return;
	}
}


void ATOZNWHPowerCCmd::PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName)
{

	oPathName = "";
	if (NULL != ipPath)
	{
		int sizeOfThePath = ipPath->GetSize();

		for (int i = sizeOfThePath - 1; i >= 0; i--)
		{
			CATBaseUnknown * pElt = (*ipPath)[i];
			if (NULL != pElt)
			{
				CATIAlias * pIAliasOnElt = NULL;
				HRESULT rc = pElt->QueryInterface(IID_CATIAlias, (void**)&pIAliasOnElt);
				if (SUCCEEDED(rc))
				{
					CATUnicodeString Name = pIAliasOnElt->GetAlias();
					oPathName.Append(Name);

					if (i > 0)
					{
						oPathName.Append("/"); ;
					}

					pIAliasOnElt->Release();
					pIAliasOnElt = NULL;
				}
			}
		}
	}
}

HRESULT ATOZNWHPowerCCmd::OpenUniquePLMComponent(const CATUnicodeString &istrPLMType,
	const CATUnicodeString& iPLM_ExternalIDValue,
	const CATUnicodeString& iV_versionValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll)
{
	// 1. Initialize the Return Value
	HRESULT hr = E_INVALIDARG;

	// 2. Build The Attribute Set
	CATAdpAttributeSet iAttributeSet;
	CATAdpPLMQueryAttributeSet iAttributeSetForFilter;

	CATUnicodeString V_versionName = CATCkePLMNavPublicServices::GetMajorRevisionAttributeName(NULL_var).CastToCharPtr();

	// CATAdpAttributeSet is formed for the query by GetElementFromAttributes
	hr = iAttributeSet.AddAttribute("PLM_ExternalID", iPLM_ExternalIDValue);
	hr = iAttributeSet.AddAttribute(V_versionName.ConvertToChar(), iV_versionValue);

	hr = iAttributeSetForFilter.AddStringAttribute("PLM_ExternalID", iPLM_ExternalIDValue); //SUCCEEDED
	hr = iAttributeSetForFilter.AddStringAttribute(V_versionName.ConvertToChar(), iV_versionValue); //SUCCEEDED
	

	// 3. Retrieve the Type by using the input String PLM Type
	CATIType_var spCATITypeOnPLMType;
	CATBoolean bPLMType = FALSE;
	if (SUCCEEDED(hr))
	{
		hr = CATCkePLMNavPublicServices::RetrieveKnowledgeType(istrPLMType, spCATITypeOnPLMType); //SUCCEEDED
		
		if (NULL_var == spCATITypeOnPLMType)
		{
			hr = CATCkePLMNavSpecializationAccessPublicServices::RetrieveSpecializationType(istrPLMType, spCATITypeOnPLMType);
			if (SUCCEEDED(hr) && (NULL_var != spCATITypeOnPLMType))
			{
				bPLMType = TRUE;
				DisplayMessage("Warning", "Success CATCkePLMNavSpecializationAccessPublicServices::RetrieveSpecializationType", "警告");
			}
		}
		else
		{
			bPLMType = TRUE;
			DisplayMessage("Warning", "Success CATCkePLMNavPublicAccessServices ::RetrieveKnowledgeType non Specializatio type", "警告");

		}
	}
	if (bPLMType == FALSE)
		DisplayMessage("Warning", "RetrieveSpecializationType AND RetrieveKnowledgeType are Failed, Invalid PLMType : Identify the Correct PLMType in Modeler", "警告");


	// 4. Retrieve the Element From Database by using the PLM Type and Attribute Set
	CATBoolean bMultipleElementAttrSet = FALSE;
	CATBoolean bUniqueKeyDefOnObject = TRUE;
	CATBoolean bIsUnique = TRUE;
	CATBoolean bUniqueObjectFromKey = TRUE;
	CATBoolean bMultipleElementFromQuery = FALSE;
	CATAdpPLMComponentsInfos oComponentsInfos;

	CATIAdpPLMIdentificator *piIdentOnPLMComp = NULL;

	// 4.1. Create the Filter Consists of PLMType and Attribute Set
	CATAdpPLMQueryFilter iQueryFilter(spCATITypeOnPLMType, iAttributeSetForFilter);

	

	// 4.2. Retrieve the Element from Database By using Filter , If Multiple elements are retrieved then Query Fails
	if (SUCCEEDED(hr)) hr = CATAdpPLMExtendedQueryServices::GetElementsFromQueryFilter(iQueryFilter, oComponentsInfos); //SUCCEEDED(hr)
	

	if (oComponentsInfos.Size() == 0) // oComponentsInfos.Size() == 0
	{
		DisplayMessage("Warning", "oComponentsInfos.Size() == 0 ", "警告");
	}

	if (SUCCEEDED(hr) && oComponentsInfos.Size() != 0)
	{
		
		if (oComponentsInfos.Size() != 1)
		{
			DisplayMessage("Warning", "GetElementsFromQueryFilter Returns Multiple Elements. Please Provide Attribute For Identifying the Unique object from Database. Use PLM_EXTERNAL ID + Version", "警告");

			bMultipleElementAttrSet = TRUE;
		}
		
		// 4.3. Retrieve the Iterator for Attribute Set
		CATAdpPLMComponentsInfosIter iterator = oComponentsInfos.GetIterator();
		CATIAdpPLMIdentificator *oComponent = NULL;
		CATAdpPLMComponentInfos oInfos;
		CATAdpPLMComponentUniqueKey oUniqueKey;
		
		// 4.4. Retrieve the Attributes from iterator : Identificator of First PLM Object
		hr = iterator.NextInfos(oComponent, oInfos);

		// 4.5. Retrieve the Unique Key for PLM Object from Identificator
		if (SUCCEEDED(hr) && NULL != oComponent)
			hr = CATAdpPLMQueryServices::GetUniqueKey(oComponent, oUniqueKey);
		

		if (NULL != oComponent)
		{
			oComponent->Release(); oComponent = NULL;
		}
		

		if (FAILED(hr)) bUniqueKeyDefOnObject = FALSE;

		
		// 4.6. Display the Value of Unique Key
		CATUnicodeString oDisplayed;
		if (SUCCEEDED(hr))  hr = oUniqueKey.Display(oDisplayed);
		if (S_OK == hr)
			DisplayMessage("Warning", "Unique Key is  ", "警告");


		// 4.7. Insure the Unicity of Unique Key
		if (SUCCEEDED(hr))  hr = oUniqueKey.UnicityGuarantee();

		if (S_OK == hr)
			DisplayMessage("Warning", "Unicity Guranteed", "警告");
		else
		{
			
			DisplayMessage("Warning", "Unicity of Unique Key is not Guranteed", "警告");
			bIsUnique = FALSE;
		}

		if (TRUE == bIsUnique)
		{
			CATListPtrCATIAdpPLMIdentificator oComponentsIdentifiers;
			// 4.8. Retrieve the Elements from Database by using Unique Key
			if (SUCCEEDED(hr))  hr = CATAdpPLMQueryServices::GetElementsByUniqueKey(oUniqueKey, oComponentsIdentifiers);
			// 4.9. If single element is retrieved return it, if mulitple elements are retrieved then Query Fails.
			if (SUCCEEDED(hr) && oComponentsIdentifiers.Size() != 0)  piIdentOnPLMComp = oComponentsIdentifiers[1];
			else if (oComponentsIdentifiers.Size() != 1)
			{
				DisplayMessage("Warning", "GetElementsByUniqueKey Returns Multiple Elements.", "警告");
				bUniqueObjectFromKey = FALSE;
			}
		}

		// 4.10. If unique Key is not implemented on the Object then Retrieve the Object By using GetElementFromAttributes
		CATListPtrCATAdpQueryResult opQueryResults;
		if (bUniqueKeyDefOnObject == FALSE || bIsUnique == FALSE)
		{
			DisplayMessage("Warning", "Unique Key is not Defined on PLM Object or Unique Key is not Unique Use GetElementFromAttributes", "警告");
			
			hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spCATITypeOnPLMType, iAttributeSet, opQueryResults);
		}

		// 4.11. If multiple elements areretrieved by above query then Query Fails  Return the identifier for first Object only
		if (SUCCEEDED(hr) && opQueryResults.Size() != 0)
		{
			CATAdpQueryResult *res = opQueryResults[1];
			if (res)
			{
				res->GetIdentifier(piIdentOnPLMComp);
				delete res;
				res = NULL;
			}

			if (opQueryResults.Size() != 1)
			{
				DisplayMessage("Warning", "GetElementFromAttributes Returns Mulitple Elements. Use Attributes which are unique", "警告");
				bMultipleElementFromQuery = TRUE;
			}
		}
	}

	// 5. Open the Element in Session
	if (NULL != piIdentOnPLMComp)
	{
		// 5.1. Create opener dpendening on the input mode
		if (TRUE == iExpandAll)
		{
			CATAdpOpenParameters params_Auth(CATAdpExpandParameters::Authoring);
			CATAdpOpener opener_Auth(iBag, params_Auth);
			// 5.2. Open the Retrieved Component by using CATAdpOpener
			hr = opener_Auth.CompleteAndOpen(piIdentOnPLMComp, iIID, opiPLMComp);
		}
		else
		{
			CATAdpOpenParameters params_Nav(CATAdpExpandParameters::Navigation);
			CATAdpOpener opener_Nav(iBag, params_Nav);
			hr = opener_Nav.CompleteAndOpen(piIdentOnPLMComp, iIID, opiPLMComp);
		}
		piIdentOnPLMComp->Release();
		piIdentOnPLMComp = NULL;
	}


	// 5. Check for the Conditional Variable 
	if (bPLMType == FALSE || bMultipleElementAttrSet == TRUE || bUniqueObjectFromKey == FALSE || bMultipleElementFromQuery == TRUE)
		hr = E_FAIL;

	return hr;
}

HRESULT ATOZNWHPowerCCmd::CAAMmrGetGeometry(CATIPartRequest_var ispModelPart, const CATUnicodeString iInputName,
	CATBaseUnknown ** oInput)
{
	HRESULT rc = E_FAIL;
	CATBoolean found = FALSE;

	if ((NULL != oInput) && (NULL_var != ispModelPart))
	{
		*oInput = NULL;

		// Retrieves all root bodies , all GS and all root OGS ( it does not retrieve ALL bodies below the Part)
		CATListValCATBaseUnknown_var pListBodies;
		rc = ispModelPart->GetAllBodies("", pListBodies);
		if (SUCCEEDED(rc))
		{
			int iBodies = 1;
			int nbbodies = pListBodies.Size();

			while ((FALSE == found) && (iBodies <= nbbodies))
			{
				CATIAlias_var spAliasBody = pListBodies[iBodies];
				if (NULL_var != spAliasBody)
				{
					CATUnicodeString currentbodyname = spAliasBody->GetAlias();

					if (iInputName == currentbodyname)
					{
						// We have found a body
						found = TRUE;
						rc = spAliasBody->QueryInterface(IID_CATBaseUnknown, (void**)&(*oInput));
					}
					else
					{
						// Research in the body
						CATIMmiUseBodyContent_var spUseBodyContentOnBody = spAliasBody;
						if (spUseBodyContentOnBody != NULL_var)
						{
							// Retrieve all geometrical element in the body 
							CATListValCATBaseUnknown_var ListFeatureInsideCurrentBody;
							spUseBodyContentOnBody->GetMechanicalFeatures(ListFeatureInsideCurrentBody);
							int nbchild = ListFeatureInsideCurrentBody.Size();

							int iChild = 1;
							while ((FALSE == found) && (iChild <= nbchild))
							{
								CATIAlias_var spChild = ListFeatureInsideCurrentBody[iChild];
								if (NULL_var != spChild)
								{
									CATUnicodeString currentchildname = spChild->GetAlias();

									if (iInputName == currentchildname)
									{
										// we have found a child of a body
										found = TRUE;
										rc = spChild->QueryInterface(IID_CATBaseUnknown, (void**)&(*oInput));
									}
								}
								iChild++;
							}
						}
					}
				}
				iBodies++;
			}
		}

	}

	if (TRUE == found)
	{
		rc = S_OK;
	}
	else rc = E_FAIL;

	return rc;
}


HRESULT ATOZNWHPowerCCmd::CAAMmrGetPartFromProduct(const CATIPLMNavReference_var &ispPLMNavRef,
	CATIPLMNavRepReference_var &ospPLMRepRef,
	CATIMmiMechanicalFeature_var &ospPartFeature)

{
	HRESULT rc = E_FAIL;

	if (NULL_var == ispPLMNavRef) return E_FAIL;
	// Retrieve the first inst rep ref
	CATIPLMNavRepInstance * pNavRepInst = NULL;

	CATListPtrCATIPLMNavEntity ListNavEntity = NULL;
	CATPLMCoreType TypeRepInstance = PLMCoreRepInstance;
	ispPLMNavRef->ListChildren(ListNavEntity, 1, &TypeRepInstance);

	if (ListNavEntity.Size() >= 1)
	{
		CATIPLMNavEntity *pCurrent = ListNavEntity[1];
		rc = pCurrent->QueryInterface(IID_CATIPLMNavRepInstance, (void**)& pNavRepInst);
	}

	// Retrieve the reference of the first inst rep ref
	CATIPLMNavRepReference *pNavRepRef = NULL;
	if (NULL != pNavRepInst)
	{
		rc = pNavRepInst->GetRepReferenceInstanceOf(pNavRepRef);
		pNavRepInst->Release(); pNavRepInst = NULL;
	}

	// change the loading mode
	if (NULL != pNavRepRef)
	{
		CATIPsiRepresentationLoadMode *piRepLoadMode = NULL;
		rc = pNavRepRef->QueryInterface(IID_CATIPsiRepresentationLoadMode, (void **)&piRepLoadMode);
		if (SUCCEEDED(rc) && NULL != piRepLoadMode)
		{
			rc = piRepLoadMode->ChangeLoadingMode(CATIPsiRepresentationLoadMode::EditMode);
			piRepLoadMode->Release();
			piRepLoadMode = NULL;
		}
	}

	//Retrieve the applicative container
	CATIMmiPrtContainer * pContainer = NULL;
	if (SUCCEEDED(rc) && (NULL != pNavRepRef))
	{
		ospPLMRepRef = pNavRepRef;
		rc = pNavRepRef->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pContainer);
		pNavRepRef->Release();
		pNavRepRef = NULL;
	}

	if (SUCCEEDED(rc) && (NULL != pContainer))
	{
		pContainer->GetMechanicalPart(ospPartFeature);
		pContainer->Release();
		pContainer = NULL;
	}
	return rc;
}

//获取参数集下的参数集
HRESULT ATOZNWHPowerCCmd::GetParamSetByName(const CATICkeParameterSet_var &ispParentSet,
	const CATUnicodeString &istrParmSetName,
	CATICkeParameterSet_var &ospParamSet)
{
	if (NULL_var == ispParentSet) return E_FAIL;

	CATIAParameterSet* piCATIAParamSet = NULL;
	HRESULT rc = ispParentSet->QueryInterface(IID_CATIAParameterSet, (void**)&piCATIAParamSet);
	if (FAILED(rc) && (NULL != piCATIAParamSet)) return E_FAIL;

	CATIAParameterSets* piParamsSets = NULL;
	piCATIAParamSet->get_ParameterSets(piParamsSets);
	if (NULL == piParamsSets) return E_FAIL;

	piCATIAParamSet->Release(); piCATIAParamSet = NULL;

	CATBoolean IsFind = FALSE;
	CATLong iCount = 0;
	piParamsSets->get_Count(iCount);
	for (long i = 1; i <= iCount; i++)
	{
		//Item
		CATVariant IndexVar;
		::BuildVariant(i, IndexVar);
		CATIAParameterSet* piCurrentParmSet = NULL;
		piParamsSets->Item(IndexVar, piCurrentParmSet);
		if (NULL != piCurrentParmSet)
		{
			CATBSTR bstrSetName;
			piCurrentParmSet->get_Name(bstrSetName);
			CATUnicodeString strSetName("");
			strSetName.BuildFromBSTR(bstrSetName);

			if (strSetName == istrParmSetName)
			{
				ospParamSet = piCurrentParmSet;
				IsFind = TRUE;
				break;
			}
			else
			{
				CATICkeParameterSet_var spCurrentParamSet = piCurrentParmSet;
				GetParamSetByName(spCurrentParamSet, istrParmSetName, ospParamSet);
			}

		}
	}
	piParamsSets->Release(); piParamsSets = NULL;

	return S_OK;
}

//获取正确的参数名称
CATUnicodeString ATOZNWHPowerCCmd::GetRightParamName(const CATUnicodeString &istrfullParamName)
{
	int iLength = istrfullParamName.GetLengthInChar();
	if (0 == iLength) return "";

	int iStartPos = 0;
	for (int i = iLength - 1; i >= 0; i--)
	{
		CATUnicodeChar iCurrentChar = istrfullParamName[i];
		if (iCurrentChar == CATUnicodeChar('\\'))
		{
			iStartPos = i + 1;
			break;
		}
	}

	CATUnicodeString strValue("");
	strValue = istrfullParamName.SubString(iStartPos, iLength - iStartPos);
	return strValue;
}

HRESULT ATOZNWHPowerCCmd::CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU)
{
	if (NULL_var == spUpdateObjectBU)
	{
		cout << "ERROR:CAAUpdateObject() - spUpdateObjectBU is NULL!" << endl;
		return E_FAIL;
	}

	CATIUseEntity *piUseEntity = NULL;
	HRESULT rc = spUpdateObjectBU->QueryInterface(IID_CATIUseEntity, (void**)&piUseEntity);
	if (SUCCEEDED(rc))
	{
		rc = DataCommonProtocolServices::Update(piUseEntity);
		if (FAILED(rc))
		{
			CATError * pError = CATError::CATGetLastError(rc);
			if (NULL != pError)
			{
				cerr << "Error message is " << pError->GetNLSMessage() << endl;
				pError->Release();
				pError = NULL;
			}
		}
		piUseEntity->Release();
		piUseEntity = NULL;
	}

	return rc;
}

HRESULT ATOZNWHPowerCCmd::GetUDFContainerFromDB(CATOmbLifeCycleRootsBag &iobag,
	CATIPLMNavReference_var &ispFeatNavRef,
	CATIPLMComponent *&opiPLMCompOnFeatRef,
	CATIMmiPrtContainer *&opIPrtContOnCAAUdfLoft)
{
	HRESULT rc = S_OK;

	//QI
	CATIPLMComponent_var spiPLMCompOnFeatRef = NULL_var;
	CATIPLMNavReference* pFeatNavRef = NULL;
	pFeatNavRef =(CATIPLMNavReference*)ispFeatNavRef;
	if (NULL == pFeatNavRef)
	{
		DisplayMessage("Warning", "(NULL == pFeatNavRef)!", "警告");
		return E_FAIL;
	}

	CATIPLMComponent* piPLMCompOnFeatRef = NULL;
	rc = pFeatNavRef->QueryInterface(IID_CATIPLMComponent,(void**)&piPLMCompOnFeatRef);
	if (FAILED(rc) || NULL == piPLMCompOnFeatRef)
	{
		DisplayMessage("Warning", "(NULL == opiPLMCompOnFeatRef)!", "警告");
		return E_FAIL;
	}


	opiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	opiPLMCompOnFeatRef->AddRef();
	
	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;

	/////////////////////////////////////////////////////////////////////////////////////

	//3DShape

	CATPLMCoreType coreType = CATPLMCoreType::PLMCoreRepInstance;
	CATListPtrCATIPLMNavEntity ChildrenList;

	rc = pFeatNavRef->ListChildren(ChildrenList, 1, &coreType);
	if (ChildrenList.Size() == 0)
	{
		DisplayMessage("Warning", "ChildrenList.Size() == 0", "警告");
		return E_FAIL;
	}


	CATIPLMNavEntity *piNavEntity = ChildrenList[1];
	if (NULL == piNavEntity)
	{
		DisplayMessage("Warning", "NULL == piNavEntity", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piNavEntity is NULL!" << endl;
		return E_FAIL;
	}

	CATIPLMNavRepInstance * piPrdObjOnRepInst = NULL;
	rc = piNavEntity->QueryInterface(IID_CATIPLMNavRepInstance, (void**)&piPrdObjOnRepInst);
	if (FAILED(rc) || NULL == piPrdObjOnRepInst)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piPrdObjOnRepInst is NULL!" << endl;
		return E_FAIL;
	}


	CATIPLMNavRepReference* pi3DShapeRepRefer = NULL;
	rc = piPrdObjOnRepInst->GetRepReferenceInstanceOf(pi3DShapeRepRefer);
	if (FAILED(rc) || NULL == pi3DShapeRepRefer)
	{
		DisplayMessage("Warning", "NULL == pi3DShapeRepRefer", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piFirst3DShapeRepRefer is NULL!" << endl;
		return E_FAIL;
	}
	piPrdObjOnRepInst->Release();
	piPrdObjOnRepInst = NULL;


	CATIPLMNavRepReference_var spi3DShapeRepRefer(pi3DShapeRepRefer);
	pi3DShapeRepRefer->Release();
	pi3DShapeRepRefer = NULL;

	// edit mode is no longer default
	CATIPsiRepresentationLoadMode_var spRepLoadMode = spi3DShapeRepRefer;
	if (NULL_var == spRepLoadMode)
	{
		DisplayMessage("Warning", "(NULL == spRepLoadMode)!", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - spRepLoadMode is NULL!" << endl;
		return E_FAIL;
	}
	rc = spRepLoadMode->ChangeLoadingMode(CATIPsiRepresentationLoadMode::EditMode);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "ChangeLoadingMode is failed!", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ChangeLoadingMode is failed!" << endl;
	}

	//container
	CATIMmiPrtContainer *pIPrtContOnCAAUdfLoft = NULL;
	rc = spi3DShapeRepRefer->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pIPrtContOnCAAUdfLoft);
	if (FAILED(rc) || (NULL_var == pIPrtContOnCAAUdfLoft))
	{
		DisplayMessage("Warning", "(NULL == pIPrtContOnCAAUdf)!", "警告");
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - RetrieveApplicativeContainer is failed!" << endl;
		return E_FAIL;
	}
	opIPrtContOnCAAUdfLoft = pIPrtContOnCAAUdfLoft;
	opIPrtContOnCAAUdfLoft->AddRef();

	// 3-bis Lock the Representation Reference containing the reference to instantiate
	//CATOmbLifeCycleRootsBag Bag ;
	rc = iobag.InsertRoot(opiPLMCompOnFeatRef);
	if (FAILED(rc))
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ibag.InsertRoot is failed!" << endl;
	}

	ULONG iL = pIPrtContOnCAAUdfLoft->Release();
	pIPrtContOnCAAUdfLoft = NULL;

	piNavEntity->Release();
	piNavEntity = NULL;

	return S_OK;
}

//清空所有高亮
void ATOZNWHPowerCCmd::ClearSO()
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL != pFrmEditor)
	{
		CATHSO* pHSO = pFrmEditor->GetHSO();
		pHSO->Empty();
	}
}
//高亮CATPathElement对象
void ATOZNWHPowerCCmd::HighlightPathElemObj(CATBaseUnknown* pObject)
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL != pFrmEditor)
	{
		CATHSO* pHSO = pFrmEditor->GetHSO();
		pHSO->AddElements(pObject);
		pHSO->EndAddElements();
	}
}


HRESULT ATOZNWHPowerCCmd::UDFImpInstantiating(CATBaseUnknown_var &ispBUCurrentPartRef, CATIUdfInstantiate_var &hIUdfInstantiate)
{
	HRESULT rc = E_FAIL;
	
	//输入元素
	//对称 线 后面 前面

	if (NULL == _pPathElemCenterPlane)
	{
		DisplayMessage("Warning", "NULL == pPathInput1", "警告");
		return E_FAIL;
	}
	rc = hIUdfInstantiate->SetNewInput(1, _pPathElemCenterPlane);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "ERROR:SetNewInput1", "警告");
		return E_FAIL;
	}

	if (NULL == _pPathElemLine)
	{
		DisplayMessage("Warning", "NULL == pPathInput2", "警告");
		return E_FAIL;
	}
	rc = hIUdfInstantiate->SetNewInput(2, _pPathElemLine);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "ERROR:SetNewInput2", "警告");
		return E_FAIL;
	}

	if (NULL == _pPathElemBackPlane)
	{
		DisplayMessage("Warning", "NULL == pPathInput3", "警告");
		return E_FAIL;
	}
	rc = hIUdfInstantiate->SetNewInput(4, _pPathElemBackPlane);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "ERROR:SetNewInput4", "警告");
		return E_FAIL;
	}

	if (NULL == _pPathElemFrontPlane)
	{
		DisplayMessage("Warning", "NULL == pPathInput4", "警告");
		return E_FAIL;
	}
	rc = hIUdfInstantiate->SetNewInput(3, _pPathElemFrontPlane);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "ERROR:SetNewInput3", "警告");
		return E_FAIL;
	}

	//修改模板参数
	rc = ModifyPartParams(hIUdfInstantiate);

	//实例化
	rc = hIUdfInstantiate->Instantiate(ispBUCurrentPartRef);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "Instantiate", "警告");
		return E_FAIL;
	}

	rc = hIUdfInstantiate->EndInstantiate();
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "EndInstantiate", "警告");
		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - EndInstantiate() is failed!" << endl;
		return E_FAIL;
	}

	return rc;
}


HRESULT ATOZNWHPowerCCmd::ModifyPartParams(const CATIUdfInstantiate_var &hIUdfInstantiate)
{
	HRESULT rc = E_FAIL;
	CATListValCATBaseUnknown_var * plistParamObj = NULL;
	CATListOfCATUnicodeString    * plistParamName = NULL;
	rc = hIUdfInstantiate->GetParameters(plistParamObj, plistParamName);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "GetParameters Failed", "ERROR");
		return rc;
	}

	for (int i = 1; i <= plistParamObj->Size(); i++)
	{
		CATICkeParm_var spCkeParm = (*plistParamObj)[i];

		CATUnicodeString strParamName = spCkeParm->Name();

		if (CATUnicodeString("阵列个数") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerZLCount->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("屋顶角度") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWDJD->GetValue();
			spCkeParm->Valuate(iValue*3.1415926f / 180.0f);
		}
		else if (CATUnicodeString("头部长度") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWDLength->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("中间段长度") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerZJLength->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("栈桥宽度") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWidth->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("栈桥高度") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerHeight->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("窗户长度") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWinHeight->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("窗户上下定位尺寸") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWinUDloc->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("窗户前后定位尺寸") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWinFBLoc->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("屋顶半宽度") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWDHalfWid->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("窗户宽度") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWinWidth->GetValue();
			spCkeParm->Valuate(iValue);
		}
		else if (CATUnicodeString("壁厚") == strParamName)
		{
			double iValue = _pATOZNWHPowerCDlg->_SpinnerWall->GetValue();
			spCkeParm->Valuate(iValue);
		}

	}


	delete plistParamObj;
	plistParamObj = NULL;

	delete plistParamName;
	plistParamName = NULL;

	return rc;
}

HRESULT ATOZNWHPowerCCmd::PrintOldInputs(CATIUdfInstantiate_var &hIUdfInstantiate)
{
	CATListOfCATUnicodeString * pListOfInputRole = NULL;
	CATListValCATBaseUnknown_var * pListOfInput = NULL;

	HRESULT rc = E_FAIL;
	rc = hIUdfInstantiate->GetOldInputs(pListOfInput, pListOfInputRole);
	if (FAILED(rc) || (NULL == pListOfInput) || (NULL == pListOfInputRole))
	{
		DisplayMessage("Error", "输入元素未获取", "ERROR");
		return E_FAIL;
	}

	for (int j = 1; j <= (*pListOfInput).Size(); j++)
	{
		CATIAlias_var spAlias = (*pListOfInput)[j];
		CATUnicodeString strAlias = spAlias->GetAlias();
		cout << "OldInput Name == " << strAlias << endl;
		//DisplayMessage("Error", strAlias, "ERROR");

		CATUnicodeString strRoleAlias = (*pListOfInputRole)[j];
		cout << "OldInputRole Name == " << strRoleAlias << endl;
		//DisplayMessage("Error", strRoleAlias, "ERROR");
	}

	delete pListOfInputRole;
	pListOfInputRole = NULL;

	delete pListOfInput;
	pListOfInput = NULL;

	return rc;
}