//===================================================================
// COPYRIGHT atoz 2020/12/07
//===================================================================
// CallEngineeringTemplate10Cmd.cpp
// Header definition of class CallEngineeringTemplate10Cmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/12/07 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CallEngineeringTemplate10Cmd_H
#define CallEngineeringTemplate10Cmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CallEngineeringTemplate10Dlg.h"

#include "ClsConfigXMLServices.h"
#include "CATPathElementAgent.h"
//system includes
#include "CATUnicodeString.h"
#include "CATCommand.h"
#include "CATBaseUnknown.h"   
#include "CATGetEnvValue.h"
#include "CATLib.h"   
#include "CATListOfCATUnicodeString.h"
#include "CATError.h" 
#include "CATListOfDouble.h"
#include "CATString.h"
#include "CATBSTRDef.h"
#include "CATAutoConversions.h"

//AfrFoundation includes
#include "CATApplicationFrame.h"
#include "CATFrmEditor.h"
#include "CATFrmLayout.h"
#include "CATFrmWindow.h"
//Dialog includes
#include "CATDlgNotify.h"

//AfrNavigator includes
#include "CATFrmNavigGraphicWindow.h"
#include "CATNavigBox.h"

//CATIAApplicationFrame includes
#include "CATCafCenterGraph.h"
//CATPLMComponentInterfaces includes
#include "CATIPLMNavReference.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavRepInstance.h"
#include "CATPLMComponentInterfacesServices.h"
#include "CATListPtrCATIPLMNavOccurrence.h"

//CATPLMIdentificationAccess includes
#include "CATIPLMComponent.h"
#include "CATIAdpType.h"
#include "CATPLMTypeServices.h"
#include "CATListPtrCATIPLMComponent.h"
#include "CATAdpAttributeSet.h"
#include "CATPLMCoreType.h"

//CAT3DPhysicalRepInterfaces includes
#include "CATIPsiRepresentationLoadMode.h"

//CATMecModLiveUseItf includes
#include "CATIMmiUsePrtPart.h"
#include "CATIMmiPrtContainer.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATIPartRequest.h"
#include "CATIBodyRequest.h"

//CATMecModUseItf inlcudes
#include "CATIMmiUseSetFactory.h"
#include "CATIMmiUseMfBRep.h"
#include "CATIMmiUseGeometricalElement.h"

//DataCommonProtocolUse includes
#include "DataCommonProtocolServices.h"
#include "CATIUseEntity.h"

//VisualizationInterfaces includes
#include "CATPathElement.h"
#include "CATIBuildPath.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATIVisProperties.h"
#include "CATVisPropertiesValues.h"
#include "CATModifyVisProperties.h"
#include "CATI3DGeoVisu.h"
#include "CATNavigation3DViewer.h"
#include "CATViewpoint.h"
#include "CAT3DViewpoint.h"

//VisualizationController includes
#include "CATViewer.h"
#include "CAT3DViewer.h"
//VisualizationFoundation includes
#include "CAT3DManipulator.h"
//ObjectModelerNavigator includes
#include "CATIRedrawEvent.h"

//SGInfra includes
#include "CAT3DViewpoint.h"
#include "CAT3DBoundingSphere.h"
#include "CAT3DViewpoint.h"
#include "CATSupport.h"
#include "CAT3DBagRep.h"
#include "CAT4x4Matrix.h"
#include "CAT3DFixedArrowGP.h"
#include "CAT3DCustomRep.h"
#include "CAT3DPlanRep.h"

//VisualizationCore includes
#include "CATGraphicAttributeSet.h"

//Mathematics includes
#include "CATMathPointf.h"
#include "CATMathDirectionf.h"
#include "CATMathBox.h"
#include "CATMathPlane.h"
#include "CATMathVector.h"
#include "CATMath3x3Matrix.h"
#include "CAT4x4Matrix.h"
#include "CATLISTV_CATMathPlane.h"

//CATMathStream includes
#include "CATSoftwareConfiguration.h"

//SGManager includes
#include "CATHSO.h"
#include "CATVisManager.h"

//ObjectModelerSystem includes
#include "CATIAlias.h"

//KnowledgeInterfaces includes
#include "CATICkeObject.h"
#include "CATIType.h"
#include "CATAttributeInfos.h"
#include "CATListValCATAttributeInfos.h"
#include "CATICkeParm.h"
#include "CATICkeParmFactory.h"
#include "CATListValCATICkeParm.h"
#include "CATCkeObjectAttrWriteServices.h"
#include "CATCkeObjectAttrReadServices.h"
#include "CATIParmPublisher.h"
#include "CATIKweModelServices.h"
#include "CATCkeGlobalFunctions.h"
#include "CATICkeParameterSet.h"
#include "CATParmPublisherAdapter.h"
#include "CATICkeFunction.h"
#include "CATITypeDictionary.h"

//KnowledgeIDLItf includes
#include "CATIAParameterSet.h"
#include "CATIAParameterSets.h"

//GMModelInterfaces includes
#include "CATBody.h"

//GeometricObjects includes
#include "CATGeoFactory.h"
#include "CATPlane.h"

//GMOperatorsInterfaces includes
#include "CATICGMTopSkin.h"
#include "CATCGMCreateTopIntersect.h"
#include "CATICGMHybIntersect.h"
#include "CATICGMHybSplit.h"
#include "CATCGMCreateTopSplit.h"

//CATMecModLiveUseItf includes
#include "CATIMmiMechanicalFeature.h"
#include "CATIMmiUsePrtPart.h"
#include "CATMmiUseServicesFactory.h"
#include "CATIMmiUseCreateImport.h"
#include "CATIPartRequest.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"

//CATMecModUseItf includes
#include "CATIMmiUseDatumFactory.h"
#include "CATIMmiUseSolidInsertion.h"
#include "CATIMmiUseBasicInsertion.h"

//CATPartUseItf includes
#include "CATIPdgUsePrtFactory.h"

//MeasureGeometryInterfaces includes
#include "CATIMeasurablePlane.h"

//PLMModelerBaseInterfaces includes
#include "CATIMovable.h"

//CATGSMUseItf includes
#include "CATIGSMUseFactory.h"
#include "CATIGSMUsePlaneOffset.h"

//ProductStructureInterfaces includes
#include "CATIPLMProducts.h"
#include "CATPrdGetOccurrenceMngt.h"
#include "CATIPrdOccurrenceMngt.h"

//-----------------------------------------------------------------------
// CATPLMIntegrationAccess Framework
#include "CATIAdpEnvironment.h"
#include "CATAdpDictionaryServices.h"
#include "CATAdpAttributeSet.h"
#include "CATAdpQueryServices.h"
#include "CATAdpQueryResult.h"
#include "CATAdpIdentificationSet.h"
#include "CATLISTP_CATAdpQueryResult.h"
#include "CATIAdpPLMIdentificator.h"

// CATPLMIntegrationUse Framework
#include "CATAdpPLMQueryFilter.h"
#include "CATAdpPLMComponentsInfos.h"
#include "CATAdpPLMComponentsInfosIter.h"
#include "CATAdpPLMExtendedQueryServices.h"
#include "CATAdpPLMQueryAttributeSet.h"
#include "CATAdpPLMComponentInfos.h"
#include "CATAdpPLMComponentUniqueKey.h"
#include "CATAdpPLMQueryServices.h"
#include "CATAdpOpenParameters.h"
#include "CATAdpOpener.h"


//ProductStructureUseItf includes
#include "CATPrdFactory.h"
#include "CATIPrdReferenceFactory.h"
#include "CATIPrd3DPartReferenceFactory.h"


//PLMDictionaryNavServices Framework
#include "CATCkePLMNavPublicServices.h"
#include "CATCkePLMNavCustoAccessPublicServices.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATCkePLMNavSpecializationAccessPublicServices.h"

// System
#include "CATString.h"
#include "CATListOfCATString.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"
#include "CATSysBoolean.h"
#include "CATBaseUnknown.h"
#include "CATLISTP_CATBaseUnknown.h"
#include "CATIMf3DAxisSystem.h"

//ObjectModelerBase includes
#include "CATOmbLifeCycleRootsBag.h"
#include "CATTemplatesAccessServices.h"
#include "CATIUdfInstantiate.h"
#include "CATIMmiOrderedGeometricalSet.h"
#include "CATIMmiViewServices.h"
#include "CATIMmiUseBodyContent.h"
#include "CATIUdfFeatureInstance.h"
#include <iostream>
#include <map>
#include <utility>
#include<iomanip>


class CATIndicationAgent;

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class CallEngineeringTemplate10Cmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( CallEngineeringTemplate10Cmd, CATStateCommand )

public:

CallEngineeringTemplate10Cmd();
virtual ~CallEngineeringTemplate10Cmd();
HRESULT InitializeConfigData();
int DisplayMessage(const CATString &istrMsgType,
	const CATUnicodeString &iusMsgToDisplay,
	const CATUnicodeString &iusDlgTitle);
HRESULT InitializeMainDialog();
HRESULT GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart,
	CATIPLMNavOccurrence_var &ospParentOccurr);
/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();
void ExitCmd();
void SelectASObj(void* idata);
void PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName);
void OKAction();
void Compute(void* idata);
HRESULT OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATListOfCATString &listAttrName,
	const CATLISTV(CATUnicodeString) &ListAttrValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll);
HRESULT GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	const CATListOfCATUnicodeString &listOfValues,
	const CATUnicodeString &iStrPLMType,
	CATListPtrCATAdpQueryResult & opQueryResults);
HRESULT RetrievePLMType(const CATUnicodeString & isPLMType,
	CATIType_var & ospType);
HRESULT GetKnowledgeAction(const CATIPLMNavReference_var &ispParentNavRef,
	const CATUnicodeString &istrActionName,
	CATBaseUnknown_var &ospActionBUObj);
HRESULT RetrieveComponentType(const CATBaseUnknown_var &ispPLMObject,
	CATUnicodeString &ostrType);
CATUnicodeString GetRightParamName(const CATUnicodeString &istrfullParamName);
HRESULT GetParamSetByName(const CATICkeParameterSet_var &ispParentSet,
	const CATUnicodeString &istrParmSetName,
	CATICkeParameterSet_var &ospParamSet);
HRESULT CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU);
HRESULT ModifyPartParams(const CATIPLMNavReference_var &ispProdRef);
HRESULT CAAMmrGetPartFromProduct(const CATIPLMNavReference_var &ispPLMNavRef,
	CATIPLMNavRepReference_var &ospPLMRepRef,
	CATIMmiMechanicalFeature_var &ospPartFeature);
HRESULT GetEngineeringTemp(CATIPLMNavReference_var &ospProdRef);
HRESULT GetUDFContainerFromDB(CATOmbLifeCycleRootsBag &iobag,
	const CATIPLMNavReference_var &ispFeatNavRef,
	CATIPLMComponent *&opiPLMCompOnFeatRef,
	CATIMmiPrtContainer *&opIPrtContOnCAAUdfLoft);

private:
	CATUnicodeString     _strTemplateID;//模板文件product的ID
	CATUnicodeString     _strActionName;//action的名称

	CATUnicodeString     _strModelViewID;//模型显示ID
	CATUnicodeString     _strModelViewVersion;//显示模型的版本
	CATOmbLifeCycleRootsBag _ModelBag;

	CATLISTV(CATUnicodeString) _listTemplateInstruction;//模板说明内容

	CallEngineeringTemplate10Dlg* _pCallEngineeringTemplate10Dlg;

	CATIPLMNavOccurrence_var _spParentOcurr;//当前上下文的product节点

	CATPathElementAgent* _pSelASPathElemAgent;
	CATDialogAgent* _pSelASDlgAgent;
	CATIMmiMechanicalFeature_var _spAxisFeature;

	map<string, double> _params;


};

//----------------------------------------------------------------------

#endif
