// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module AtoZDDTZMXACmdShowTurningPt
#======================================================================
#  2021/03/12 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM    \
JS0GROUP \
CATDialogEngine \
DI0PANV2 \
CATAfrItf \
CATAfrFoundation \
VPMEditorInterfaces \
CATPLMComponentInterfaces \
CATMecModLiveUseItf \
CAT3DPhysicalRepItf \
CATSysTS \
CATMecModUseItf \
DataCommonProtocolUse \
CATVisItf \
ObjectModelerSystem \
SceneGraphManager \
CATObjectModelerNavigator \
KnowledgeItf \
CATPLMIdentificationAccess \
PLMDictionaryNavServices \
CATVisController \
SGInfra \
CATMathematics \
CATGMModelInterfaces \
CATAfrNavigator \
CATIAApplicationFrame \
CATGMOperatorsInterfaces \
CATMathStream \
CATGMGeometricInterfaces \
CATPartUseItf \
CATMeasureGeometryInterfaces \
CATVisFoundation \
CATPLMModelerBaseInterfaces \
CATGSMUseItf \
CATProductStructureUseItf \
CATProductStructureInterfaces \
CATPLMIntegrationAccess \
CATPLMIntegrationUse \
CATObjectModelerBase \
KnowledgeIDLItf \
CatXmlItfExt \
CatXmlItfBase \
CATAnnotationUseItf \
CATDraftingUseItf \
CATSketcherUseItf \
CATProductStructureUseItf \
PLMLibraryNavUseItf \
CATSkt2DGeomIntegUseItf \
ATOZDrawingPubFunc \
CATDraftingGenUseItf \
SystemUUID \
CATGeometricObjects \
CATPipeTubeDesignUseItf \
CATHvacDesignUseItf \
CATInteractiveInterfaces         \
DataCommonProtocolUse            \
DraftingProIDL                   \
DraftingPubIDL                   \
CATAnnotationPubIDL              \
CATInfInterfaces                 \
SketcherPubIDL                   \
FeatureModelerExt                \
CATWeightEquivalentUseItf        \
CATOpnsInertiaIDLItf             \
CatXmlItfExt                     \
CATAdvancedMathematics \
# END WIZARD EDITION ZONE
