//===================================================================
// COPYRIGHT ATOZ 2020/06/10
//===================================================================
// CallEngineeringTemplate2Cmd.cpp
// Header definition of class CallEngineeringTemplate2Cmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/06/10 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CallEngineeringTemplate2Cmd.h"
#include "CATCreateExternalObject.h"
CATCreateClass( CallEngineeringTemplate2Cmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CallEngineeringTemplate2Cmd::CallEngineeringTemplate2Cmd() :
CATStateCommand ("CallEngineeringTemplate2Cmd", CATDlgEngOneShot, CATCommandModeShared)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, _pCallEngineeringTemplate2Dlg(NULL)
, _pSelAxisSystemPathElemAgent(NULL)
, _pSelPtPathElemAgent(NULL)
, _pSelSupportSurfPathElemAgent(NULL)
, _pSelAxisSystemDlgAgent(NULL)
, _pSelMidInfPtDlgAgent(NULL)
, _pSelSupportPlaneDlgAgent(NULL)
, _pSelCenterPointDlgAgent(NULL)
, _spAxisSystemFeature(NULL_var)
, _spMidInflectionPointFeature(NULL_var)
, _spCenterPointFeature(NULL_var)
, _spSupportPlaneFeature(NULL_var)
, _spParentOcurr(NULL_var)
, _listTemplateInstruction(NULL)
, _strTemplateID("")
, _strActionName("")
, _strModelViewID("")
, _strModelViewVersion("")
{
	HRESULT rc = InitializeConfigData();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}

	rc = InitializeMainDialog();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}
	for (int i = 1; i <= _listTemplateInstruction.Size(); i++)
	{
		_pCallEngineeringTemplate2Dlg->_EditorUseSteps->SetLine(_listTemplateInstruction[i]);
	}

	CATIMmiUsePrtPart_var spCurrentPart = NULL_var;
	GetCurrentPart(spCurrentPart, _spParentOcurr);
	if (NULL_var == _spParentOcurr)
	{
		DisplayMessage("Error", "Please work in product context!", "ERROR");
		this->RequestDelayedDestruction();
		return;
	}

	DisplayTemplateView();
}
//获取当前part节点和上下文product节点
HRESULT CallEngineeringTemplate2Cmd::GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart,
	                                                CATIPLMNavOccurrence_var &ospParentOccurr)
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL == pFrmEditor) return E_FAIL;

	CATPathElement& CurrentElemPath = pFrmEditor->GetUIActiveObject();
	CATBaseUnknown* pCurrentObject = CurrentElemPath.FindElement(IID_CATIMmiUsePrtPart);
	if (NULL != pCurrentObject)
	{
		ospPrtPart = pCurrentObject;
	}

	CATBaseUnknown* pOccurrObj = CurrentElemPath.FindElement(IID_CATIPLMNavOccurrence);
	if (NULL != pOccurrObj)
	{
		CATIPLMNavOccurrence_var spCurrentOccurr = pOccurrObj;
		if (NULL_var != spCurrentOccurr)
		{
			CATIPLMNavOccurrence* piParentOccurr = NULL;
			spCurrentOccurr->GetFather(piParentOccurr);
			if (NULL != piParentOccurr)
			{
				ospParentOccurr = piParentOccurr;
				piParentOccurr->Release(); piParentOccurr = NULL;
			}
		}

		//CATIPLMNavOccurrence_var spCurrentOccurr = pOccurrObj;
		//CATIAlias_var spAliasName = spCurrentOccurr;
		//cout << "pCurrentObject == " << spAliasName->GetAlias() << endl;
	}
	return S_OK;
}
HRESULT CallEngineeringTemplate2Cmd::InitializeConfigData()
{
	CATUnicodeString strInstallPath("");
	ClsConfigXMLServices::Get_ComputeDataExePath(strInstallPath);
	if (CATUnicodeString("") == strInstallPath) return E_FAIL;

	CATUnicodeString strProjectConfigPath = strInstallPath + "bin\\\ATOZ\\CAAEKLConfig";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		DisplayMessage("Error", "找不到CAAEKLConfig配置文件夹!", "ERROR");
		return E_FAIL;
	}

	const char* pxmlfilePath = CATFindPath("CAAEKLConfig.xml", strProjectConfigPath);
	if (NULL == pxmlfilePath)
	{
		DisplayMessage("Error", "找不到CAAEKLConfig.xml配置文件!", "ERROR");
		return E_FAIL;
	}

	CATUnicodeString strXMLFilePath = pxmlfilePath;
	HRESULT rc = ClsConfigXMLServices::GetCUPSConfigData(strXMLFilePath, "运输机", _strTemplateID,
		_strActionName, _strModelViewID, _strModelViewVersion);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "读取CAAEKLConfig.xml配置文件失败!", "ERROR");
		return E_FAIL;
	}

	strProjectConfigPath = strInstallPath + "bin\\\ATOZ";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		DisplayMessage("Error", "找不到ATOZ配置文件夹!", "ERROR");
		return E_FAIL;
	}
	else
	{
		const char* pfilePath = CATFindPath("TemplateInstruction_2.ini", strProjectConfigPath);
		if (NULL != pfilePath)
		{
			ClsConfigXMLServices::ReadTemplateText(pfilePath, _listTemplateInstruction);
			//for (int i = 1; i <= _listTemplateInstruction.Size(); i++)
			//{
			//	cout << "_listTemplateInstruction["<<i<<"] == "<< _listTemplateInstruction[i] << endl;
			//}
		}
	}

	return S_OK;
}
//显示视图
HRESULT CallEngineeringTemplate2Cmd::DisplayTemplateView()
{
	//判断项目中是否存在物料
	CATLISTV(CATString)        listAttrName;
	CATLISTV(CATUnicodeString) listAttrValue;
	listAttrName.Append("PLM_ExternalID");
	listAttrName.Append("revision");

	listAttrValue.Append(_strModelViewID);
	listAttrValue.Append(_strModelViewVersion);
	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	GetPLMObjectsFromAttrAndFromType(listAttrName, listAttrValue, "VPMReference", listQueryResult);
	if (listQueryResult.Size() > 0)
	{
		CATBoolean authoringMode = TRUE;
		CATIPLMNavReference* piProductRef = NULL;
		OpenPLMComponent("VPMReference", listAttrName, listAttrValue,
			IID_CATIPLMNavReference, (void**)&piProductRef, _ModelBag, authoringMode);
		if (NULL != piProductRef)
		{
			//CATIPLMComponent_var spPLMComponent = piProductRef;
			//if (NULL_var != spPLMComponent)
			//{
			//	PrintComponentAttrs(spPLMComponent);
			//}
			CATIPrdOccurrenceMngt* piOccurrMngt = NULL;
			if (SUCCEEDED(CATPrdGetOccurrenceMngt(piOccurrMngt)) && piOccurrMngt)
			{
				CATIPLMNavOccurrence_var spPrdOccurr = NULL_var;
				piOccurrMngt->GetOrCreateRootOccurrence(piProductRef, spPrdOccurr);
				if (NULL_var != spPrdOccurr)
				{
					CATFrmEditor * pEditor = CATFrmEditor::GetCurrentEditor();
					CATVisManager * pVisuManager = CATVisManager::GetVisManager();
					CATCommand * pCommandSelector = (CATCommand*)pEditor->GetCommandSelector();
					list<IID> ListIVisu3d;
					IID visu3d = IID_CATI3DGeoVisu;
					ListIVisu3d.fastadd(&visu3d);
					CATPathElement*  pRootObjectPath = new CATPathElement(spPrdOccurr);
					CATViewpoint*  pModelViewPoint = (CATViewpoint*)&(_pCallEngineeringTemplate2Dlg->_Navigation3DViewerModel->GetMain3DViewpoint());
					HRESULT rc = pVisuManager->AttachTo(pRootObjectPath, pModelViewPoint, ListIVisu3d, pCommandSelector);

					_pCallEngineeringTemplate2Dlg->_Navigation3DViewerModel->Draw();
					_pCallEngineeringTemplate2Dlg->_Navigation3DViewerModel->Reframe();
				}

				piOccurrMngt->Release(); piOccurrMngt = NULL;
			}
			piProductRef->Release(); piProductRef = NULL;
		}
	}

	return S_OK;
}
HRESULT CallEngineeringTemplate2Cmd::GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	const CATListOfCATUnicodeString &listOfValues,
	const CATUnicodeString &iStrPLMType,
	CATListPtrCATAdpQueryResult & opQueryResults)
{
	HRESULT hr = S_OK;
	//cout << "   GetPLMObjectsFromAttrAndFromType " << endl;

	if ((0 == listOfAttribute.Size()) || (0 == listOfValues.Size())) return E_INVALIDARG;
	if (listOfAttribute.Size() != listOfValues.Size()) return E_INVALIDARG;
	if (0 < opQueryResults.Size())return E_INVALIDARG;


	int iListSize = listOfAttribute.Size();

	CATAdpAttributeSet iAttributeSet;
	//cout << "   Build an Attribute set with inputs from user, for query into db" << endl;
	int i = 1;
	while ((i <= iListSize) && (SUCCEEDED(hr)))
	{
		CATUnicodeString Name = listOfAttribute[i].CastToCharPtr();
		const CATString AttributeINPUT = CATCkePLMNavPublicServices::RetrieveBasicAttributeNameFromPreviousOne(NULL_var, Name).CastToCharPtr();
		CATUnicodeString AttrValue = listOfValues[i];

		hr = iAttributeSet.AddAttribute(AttributeINPUT, AttrValue);
		i++;
	}

	CATIType_var spTypeObj = NULL_var;
	hr = RetrievePLMType(iStrPLMType, spTypeObj);
	if (FAILED(hr) || (NULL_var == spTypeObj))
	{
		cout << "ERROR:ClsPLMUtilities::GetPLMObjectsFromAttrAndFromType()-NULL_var == spTypeObj" << endl;
		return E_FAIL;
	}


	hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spTypeObj,
		iAttributeSet,
		opQueryResults);

	return hr;
}

//-------------------------------------------------------------------------
// RetrievePLMType (for DS Types and Specialization Types)
//-------------------------------------------------------------------------
HRESULT CallEngineeringTemplate2Cmd::RetrievePLMType(const CATUnicodeString & isPLMType,
	CATIType_var & ospType)
{
	HRESULT rc = E_INVALIDARG;
	if (isPLMType != "")
	{
		// For DS type
		rc = CATCkePLMNavPublicServices::RetrieveKnowledgeType(isPLMType, ospType);
		// For Specialization Type
		if (FAILED(rc))  rc = CATCkePLMNavSpecializationAccessPublicServices::RetrieveSpecializationType(isPLMType, ospType);
	}
	return rc;
}


HRESULT CallEngineeringTemplate2Cmd::OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATListOfCATString &listAttrName,
	const CATLISTV(CATUnicodeString) &ListAttrValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll)
{
	HRESULT hr = S_OK;
	if (CATUnicodeString("") == istrPLMType) return E_FAIL;
	if (0 == listAttrName.Size()) return E_FAIL;
	if (0 == ListAttrValue.Size()) return E_FAIL;

	int iListSize = listAttrName.Size();

	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	hr = GetPLMObjectsFromAttrAndFromType(listAttrName, ListAttrValue, istrPLMType, listQueryResult);
	if (FAILED(hr) || (0 == listQueryResult.Size()))
	{

		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-0 == listQueryResult.Size()" << endl;
		return hr;
	}

	CATIAdpPLMIdentificator* piAdpPLMIdentificator = NULL;
	listQueryResult[1]->GetIdentifier(piAdpPLMIdentificator);
	if (NULL == piAdpPLMIdentificator)
	{
		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-NULL == piAdpPLMIdentificator" << endl;
		return E_FAIL;
	}

	if (TRUE == iExpandAll)
	{
		CATAdpOpenParameters params_Auth(CATAdpExpandParameters::Authoring);
		CATAdpOpener opener_Auth(iBag, params_Auth);
		// 5.2. Open the Retrieved Component by using CATAdpOpener
		hr = opener_Auth.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	else
	{
		CATAdpOpenParameters params_Nav(CATAdpExpandParameters::OneLevelRepresentations);
		CATAdpOpener opener_Nav(iBag, params_Nav);
		hr = opener_Nav.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	piAdpPLMIdentificator->Release();
	piAdpPLMIdentificator = NULL;

	return S_OK;
}
HRESULT CallEngineeringTemplate2Cmd::InitializeMainDialog()
{
	_pCallEngineeringTemplate2Dlg = new CallEngineeringTemplate2Dlg((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
		                                                          "CallEngineeringTemplateDlg");
	_pCallEngineeringTemplate2Dlg->Build();
	CATNavigation3DViewer* p3DViewer = _pCallEngineeringTemplate2Dlg->_Navigation3DViewerModel;
	if (NULL != p3DViewer)
	{
		p3DViewer->SetBackgroundColor(0.235294f, 0.4f, 0.501961f);
	}

	CATDlgSelectorList* pDlgSelList = _pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem;
	if (NULL != pDlgSelList)
	{
		int ArraySel[1] = { 0 };
		pDlgSelList->SetSelect(ArraySel, 1);
	}
	
	_pCallEngineeringTemplate2Dlg->_LabelLog->SetIconName("I_ZMXALog");
	_pCallEngineeringTemplate2Dlg->SetVisibility(CATDlgShow);
	return S_OK;
}
//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CallEngineeringTemplate2Cmd::~CallEngineeringTemplate2Cmd()
{
	if (NULL != _pCallEngineeringTemplate2Dlg)
	{
		_pCallEngineeringTemplate2Dlg->RequestDelayedDestruction();
		_pCallEngineeringTemplate2Dlg = NULL;
	}
	if (NULL != _pSelAxisSystemPathElemAgent)
	{
		_pSelAxisSystemPathElemAgent->RequestDelayedDestruction();
		_pSelAxisSystemPathElemAgent = NULL;
	}
	if (NULL != _pSelPtPathElemAgent)
	{
		_pSelPtPathElemAgent->RequestDelayedDestruction();
		_pSelPtPathElemAgent = NULL;
	}
	if (NULL != _pSelSupportSurfPathElemAgent)
	{
		_pSelSupportSurfPathElemAgent->RequestDelayedDestruction();
		_pSelSupportSurfPathElemAgent = NULL;
	}
	if (NULL != _pSelAxisSystemDlgAgent)
	{
		_pSelAxisSystemDlgAgent->RequestDelayedDestruction();
		_pSelAxisSystemDlgAgent = NULL;
	}
	if (NULL != _pSelCenterPointDlgAgent)
	{
		_pSelCenterPointDlgAgent->RequestDelayedDestruction();
		_pSelCenterPointDlgAgent = NULL;
	}
	if (NULL != _pSelSupportPlaneDlgAgent)
	{
		_pSelSupportPlaneDlgAgent->RequestDelayedDestruction();
		_pSelSupportPlaneDlgAgent = NULL;
	}
	if (NULL != _pSelCenterPointDlgAgent)
	{
		_pSelCenterPointDlgAgent->RequestDelayedDestruction();
		_pSelCenterPointDlgAgent = NULL;
	}
	_ModelBag.RemoveAll();
}


//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void CallEngineeringTemplate2Cmd::BuildGraph()
{
	_pSelAxisSystemPathElemAgent = new CATPathElementAgent("SelectSpline");
	_pSelAxisSystemPathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelAxisSystemPathElemAgent->SetOrderedElementType("CATIMf3DAxisSystem");

	_pSelPtPathElemAgent = new CATPathElementAgent("SelectPoint");
	_pSelPtPathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelPtPathElemAgent->SetOrderedElementType("CATIMfZeroDimResult");

	_pSelSupportSurfPathElemAgent = new CATPathElementAgent("SelectSurf");
	_pSelSupportSurfPathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelSupportSurfPathElemAgent->SetOrderedElementType("CATIMfBiDimResult");

	//选择中心轴系
	_pSelAxisSystemDlgAgent = new CATDialogAgent("AxisSystemDlg");
	_pSelAxisSystemDlgAgent->AcceptOnNotify(_pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem,
		                                    _pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem->GetListSelectNotification());

	//选择中间拐点
	_pSelMidInfPtDlgAgent = new CATDialogAgent("SelMidPlaneDlg");
	_pSelMidInfPtDlgAgent->AcceptOnNotify(_pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt,
		                         _pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt->GetListSelectNotification());

	//选择滚筒中心点
	_pSelCenterPointDlgAgent = new CATDialogAgent("SelMidPlaneDlg");
	_pSelCenterPointDlgAgent->AcceptOnNotify(_pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt,
		                _pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt->GetListSelectNotification());

	//选择地面支持面
	_pSelSupportPlaneDlgAgent = new CATDialogAgent("SelSupportPlaneDlg");
	_pSelSupportPlaneDlgAgent->AcceptOnNotify(_pCallEngineeringTemplate2Dlg->_SelectorListSupportFace,
		                    _pCallEngineeringTemplate2Dlg->_SelectorListSupportFace->GetListSelectNotification());

	CATDialogState * SelectAxisSystemState = GetInitialState("请选择滚筒中心轴系");
	SelectAxisSystemState->AddDialogAgent(_pSelAxisSystemPathElemAgent);
	SelectAxisSystemState->AddDialogAgent(_pSelMidInfPtDlgAgent);
	SelectAxisSystemState->AddDialogAgent(_pSelCenterPointDlgAgent);
	SelectAxisSystemState->AddDialogAgent(_pSelSupportPlaneDlgAgent);

	CATDialogState * SelectMidInfPointState = AddDialogState("请选择中间拐点");
	SelectMidInfPointState->AddDialogAgent(_pSelPtPathElemAgent);
	SelectMidInfPointState->AddDialogAgent(_pSelAxisSystemDlgAgent);
	SelectMidInfPointState->AddDialogAgent(_pSelCenterPointDlgAgent);
	SelectMidInfPointState->AddDialogAgent(_pSelSupportPlaneDlgAgent);

	CATDialogState * SelectCenterPtState = AddDialogState("请选择滚筒中心点");
	SelectCenterPtState->AddDialogAgent(_pSelPtPathElemAgent);
	SelectCenterPtState->AddDialogAgent(_pSelAxisSystemDlgAgent);
	SelectCenterPtState->AddDialogAgent(_pSelMidInfPtDlgAgent);
	SelectCenterPtState->AddDialogAgent(_pSelSupportPlaneDlgAgent);

	CATDialogState * SelectSupportSurfState = AddDialogState("请选择地面支持面");
	SelectSupportSurfState->AddDialogAgent(_pSelSupportSurfPathElemAgent);
	SelectSupportSurfState->AddDialogAgent(_pSelAxisSystemDlgAgent);
	SelectSupportSurfState->AddDialogAgent(_pSelMidInfPtDlgAgent);
	SelectSupportSurfState->AddDialogAgent(_pSelCenterPointDlgAgent);

	//SelectAxisSystemState 选择中心轴系
	AddTransition(SelectAxisSystemState, SelectAxisSystemState,
		         IsOutputSetCondition(_pSelAxisSystemPathElemAgent),
		        Action((ActionMethod)&CallEngineeringTemplate2Cmd::SelectAxisSytemObj));

	AddTransition(SelectAxisSystemState, SelectMidInfPointState,
		          IsOutputSetCondition(_pSelMidInfPtDlgAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	AddTransition(SelectAxisSystemState, SelectCenterPtState,
		          IsOutputSetCondition(_pSelCenterPointDlgAgent),
		        Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	AddTransition(SelectAxisSystemState, SelectSupportSurfState,
		          IsOutputSetCondition(_pSelSupportPlaneDlgAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	//SelectMidInfPointState 选择中间拐点
	AddTransition(SelectMidInfPointState, SelectMidInfPointState,
		          IsOutputSetCondition(_pSelPtPathElemAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::SelectMidInfPtObj));

	AddTransition(SelectMidInfPointState, SelectAxisSystemState,
		          IsOutputSetCondition(_pSelAxisSystemDlgAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	AddTransition(SelectMidInfPointState, SelectCenterPtState,
		          IsOutputSetCondition(_pSelCenterPointDlgAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	AddTransition(SelectMidInfPointState, SelectSupportSurfState,
		          IsOutputSetCondition(_pSelSupportPlaneDlgAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	//SelectCenterPtState 选择滚筒中心点
	AddTransition(SelectCenterPtState, SelectCenterPtState,
		         IsOutputSetCondition(_pSelPtPathElemAgent),
		         Action((ActionMethod)&CallEngineeringTemplate2Cmd::SelectCenterPtObj));

	AddTransition(SelectCenterPtState, SelectAxisSystemState,
		          IsOutputSetCondition(_pSelAxisSystemDlgAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	AddTransition(SelectCenterPtState, SelectMidInfPointState,
		          IsOutputSetCondition(_pSelMidInfPtDlgAgent),
	 	         Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	AddTransition(SelectCenterPtState, SelectSupportSurfState,
		         IsOutputSetCondition(_pSelSupportPlaneDlgAgent),
		         Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	//SelectSupportSurfState 选择地面支持面
	AddTransition(SelectSupportSurfState, SelectSupportSurfState,
		          IsOutputSetCondition(_pSelSupportSurfPathElemAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::SelectSupportPlaneObj));

	AddTransition(SelectSupportSurfState, SelectAxisSystemState,
		          IsOutputSetCondition(_pSelAxisSystemDlgAgent),
		          Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	AddTransition(SelectSupportSurfState, SelectMidInfPointState,
		         IsOutputSetCondition(_pSelMidInfPtDlgAgent),
		         Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	AddTransition(SelectSupportSurfState, SelectCenterPtState,
		          IsOutputSetCondition(_pSelCenterPointDlgAgent),
		         Action((ActionMethod)&CallEngineeringTemplate2Cmd::CleanDialogAgent));

	//click Wndclose buttion
	AddAnalyseNotificationCB(_pCallEngineeringTemplate2Dlg, 
		                     _pCallEngineeringTemplate2Dlg->GetWindCloseNotification(),
		                   (CATCommandMethod)&CallEngineeringTemplate2Cmd::ExitCmd, NULL);
	//click cancel button
	AddAnalyseNotificationCB(_pCallEngineeringTemplate2Dlg, 
		                     _pCallEngineeringTemplate2Dlg->GetDiaCANCELNotification(),
		                     (CATCommandMethod)&CallEngineeringTemplate2Cmd::ExitCmd, NULL);

	//click OK button
	AddAnalyseNotificationCB(_pCallEngineeringTemplate2Dlg, 
		                     _pCallEngineeringTemplate2Dlg->GetDiaOKNotification(),
		                      (CATCommandMethod)&CallEngineeringTemplate2Cmd::OKAction, NULL);
}
//清除对话框代理
void CallEngineeringTemplate2Cmd::CleanDialogAgent()
{
	if (_pSelAxisSystemDlgAgent->IsOutputSet())
	{
		_pSelAxisSystemDlgAgent->InitializeAcquisition();
		_pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt->ClearSelect();
		_pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt->ClearSelect();
		_pCallEngineeringTemplate2Dlg->_SelectorListSupportFace->ClearSelect();
	}
	if (_pSelMidInfPtDlgAgent->IsOutputSet())
	{
		_pSelMidInfPtDlgAgent->InitializeAcquisition();
		_pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem->ClearSelect();
		_pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt->ClearSelect();
		_pCallEngineeringTemplate2Dlg->_SelectorListSupportFace->ClearSelect();
	}
	if (_pSelCenterPointDlgAgent->IsOutputSet())
	{
		_pSelCenterPointDlgAgent->InitializeAcquisition();
		_pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem->ClearSelect();
		_pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt->ClearSelect();
		_pCallEngineeringTemplate2Dlg->_SelectorListSupportFace->ClearSelect();
	}
	if (_pSelSupportPlaneDlgAgent->IsOutputSet())
	{
		_pSelSupportPlaneDlgAgent->InitializeAcquisition();
		_pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem->ClearSelect();
		_pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt->ClearSelect();
		_pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt->ClearSelect();
	}
}
void CallEngineeringTemplate2Cmd::ExitCmd()
{
	this->RequestDelayedDestruction();
	return;
}
//选择中心轴系
void CallEngineeringTemplate2Cmd::SelectAxisSytemObj(void* idata)
{
	CATPathElement* pPathElem = _pSelAxisSystemPathElemAgent->GetValue();
	CATBaseUnknown* pBaseUnknown = _pSelAxisSystemPathElemAgent->GetElementValue();
	_pSelAxisSystemPathElemAgent->InitializeAcquisition();

	_spAxisSystemFeature = pBaseUnknown;

	CATUnicodeString strFullPath("");
	PathElementString(pPathElem, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL_var == _spMidInflectionPointFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spCenterPointFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt->SetSelect(ArraySel, 1);
	}else if (NULL_var == _spSupportPlaneFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListSupportFace->SetSelect(ArraySel, 1);
	}

}
void CallEngineeringTemplate2Cmd::SelectMidInfPtObj(void* idata)
{
	CATPathElement* pPathElem = _pSelPtPathElemAgent->GetValue();
	CATBaseUnknown* pBaseUnknown = _pSelPtPathElemAgent->GetElementValue();
	_pSelPtPathElemAgent->InitializeAcquisition();

	_spMidInflectionPointFeature = pBaseUnknown;
	CATUnicodeString strFullPath("");
	PathElementString(pPathElem, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL_var == _spAxisSystemFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spCenterPointFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spSupportPlaneFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListSupportFace->SetSelect(ArraySel, 1);
	}
}
void CallEngineeringTemplate2Cmd::SelectCenterPtObj(void* idata)
{
	CATPathElement* pPathElem = _pSelPtPathElemAgent->GetValue();
	CATBaseUnknown* pBaseUnknown = _pSelPtPathElemAgent->GetElementValue();
	_pSelPtPathElemAgent->InitializeAcquisition();

	_spCenterPointFeature = pBaseUnknown;
	CATUnicodeString strFullPath("");
	PathElementString(pPathElem, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL_var == _spAxisSystemFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spMidInflectionPointFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spSupportPlaneFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListSupportFace->SetSelect(ArraySel, 1);
	}
}
void CallEngineeringTemplate2Cmd::SelectSupportPlaneObj(void* idata)
{
	CATPathElement* pPathElem = _pSelSupportSurfPathElemAgent->GetValue();
	CATBaseUnknown* pBaseUnknown = _pSelSupportSurfPathElemAgent->GetElementValue();
	_pSelSupportSurfPathElemAgent->InitializeAcquisition();

	_spSupportPlaneFeature = pBaseUnknown;
	CATUnicodeString strFullPath("");
	PathElementString(pPathElem, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallEngineeringTemplate2Dlg->_SelectorListSupportFace;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

	if (NULL_var == _spAxisSystemFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListAxisSystem->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spMidInflectionPointFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListMidInfPt->SetSelect(ArraySel, 1);
	}
	else if (NULL_var == _spCenterPointFeature)
	{
		int ArraySel[1] = { 0 };
		_pCallEngineeringTemplate2Dlg->_SelectorListGunTong2CenterPt->SetSelect(ArraySel, 1);
	}
}
//printf object fullpath
void CallEngineeringTemplate2Cmd::PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName)
{

	oPathName = "";
	if (NULL != ipPath)
	{
		int sizeOfThePath = ipPath->GetSize();

		for (int i = sizeOfThePath - 1; i >= 0; i--)
		{
			CATBaseUnknown * pElt = (*ipPath)[i];
			if (NULL != pElt)
			{
				CATIAlias * pIAliasOnElt = NULL;
				HRESULT rc = pElt->QueryInterface(IID_CATIAlias, (void**)&pIAliasOnElt);
				if (SUCCEEDED(rc))
				{
					CATUnicodeString Name = pIAliasOnElt->GetAlias();
					oPathName.Append(Name);

					if (i > 0)
					{
						oPathName.Append("/"); ;
					}

					pIAliasOnElt->Release();
					pIAliasOnElt = NULL;
				}
			}
		}
	}
}
//ok action
void CallEngineeringTemplate2Cmd::OKAction()
{
	if (NULL_var == _spAxisSystemFeature)
	{
		DisplayMessage("Warning", "请选择滚筒1中心轴系!", "警告");
		return;
	}
	if (NULL_var == _spMidInflectionPointFeature)
	{
		DisplayMessage("Warning", "请选择中间拐点!", "警告");
		return;
	}
	if (NULL_var == _spCenterPointFeature)
	{
		DisplayMessage("Warning", "请选择滚筒2中心点!", "警告");
		return;
	}
	if (NULL_var == _spSupportPlaneFeature)
	{
		DisplayMessage("Warning", "请选择地形面!", "警告");
		return;
	}

	if (NULL_var == _spParentOcurr)
	{
		DisplayMessage("Warning", "获取父节点occurence对象失败!", "警告");
		return;
	}

	CATIPLMNavReference* piProdRef = NULL;
	_spParentOcurr->GetRelatedReference(piProdRef);
	if (NULL == piProdRef)
	{
		DisplayMessage("Error", "Get parent reference product failed!", "Error");
		return;
	}
	CATIPLMNavReference_var spProdRef = piProdRef;
	piProdRef->Release(); piProdRef = NULL;

	//1:打开EKL模板
	CATLISTV(CATString)        listAttrName;
	CATLISTV(CATUnicodeString) listAttrValue;
	listAttrName.Append("PLM_ExternalID");
	listAttrValue.Append(_strTemplateID);

	CATOmbLifeCycleRootsBag Bag;
	CATBoolean authoringMode = TRUE;
	CATIPLMNavReference* piProductRef = NULL;
	OpenPLMComponent("VPMReference", listAttrName, listAttrValue,
		IID_CATIPLMNavReference, (void**)&piProductRef, Bag, authoringMode);
	if (NULL == piProductRef)
	{
		DisplayMessage("Error", "打开EKL模板失败,请检查配置文件!", "ERROR");
		return;
	}
	//调用EKL action
	CATBaseUnknown_var spActionBUObj = NULL_var;
	GetKnowledgeAction(piProductRef, _strActionName, spActionBUObj);
	if (NULL_var == spActionBUObj)
	{
		DisplayMessage("Error", "获取EKL模板中的Action失败!", "ERROR");
		return;
	}

	CATICkeFunction_var spCkeActionFunc = spActionBUObj;
	if (NULL_var == spCkeActionFunc)
	{
		cout << "ERROR:PSTCUPSCmd::OKAction()-NULL_var == spCkeActionFunc" << endl;
		return;
	}

	CATICkeParmFactory_var spCkeParmFactory = CATCkeGlobalFunctions::GetVolatileFactory();
	if (NULL_var == spCkeParmFactory)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spCkeParmFactory" << endl;
		return;
	}
	CATLISTV(CATBaseUnknown_var) listCkeParamObj = NULL;
	CATICkeParm_var spParentRefCkeParam = spCkeParmFactory->CreateObjectReference(spProdRef);
	if (NULL_var == spParentRefCkeParam)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spParentRefCkeParam" << endl;
		return;
	}
	CATICkeParm_var spAxisSystemCkeParam = spCkeParmFactory->CreateObjectReference(_spAxisSystemFeature);
	if (NULL_var == spAxisSystemCkeParam)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spAxisSystemCkeParam" << endl;
		return;
	}
	CATICkeParm_var spMidInfPtCkeParam = spCkeParmFactory->CreateObjectReference(_spMidInflectionPointFeature);
	if (NULL_var == spMidInfPtCkeParam)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spMidInfPtCkeParam" << endl;
		return;
	}
	CATICkeParm_var spCenterPtCkeParam = spCkeParmFactory->CreateObjectReference(_spCenterPointFeature);
	if (NULL_var == spCenterPtCkeParam)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spCenterPtCkeParam" << endl;
		return;
	}
	CATICkeParm_var spSupportSurfCkeParam = spCkeParmFactory->CreateObjectReference(_spSupportPlaneFeature);
	if (NULL_var == spSupportSurfCkeParam)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spSupportSurfCkeParam" << endl;
		return;
	}
	listCkeParamObj.Append(spParentRefCkeParam);
	listCkeParamObj.Append(spAxisSystemCkeParam);
	listCkeParamObj.Append(spMidInfPtCkeParam);
	listCkeParamObj.Append(spCenterPtCkeParam);
	listCkeParamObj.Append(spSupportSurfCkeParam);

	CATIType_var hProductType = NULL_var;
	CATITypeDictionary_var hTypeDictionary = CATGlobalFunctions::GetTypeDictionary();
	if (NULL_var != hTypeDictionary)
	{
		CATUnicodeString TypeName = "VPMReference";
		hTypeDictionary->FindType(TypeName, hProductType);
	}

	CATICkeParm_var spResultParam = NULL_var;
	if (NULL_var != hProductType)
	{
		spResultParam = spCkeParmFactory->CreateObjectReference(hProductType, "VPMReference");
	}

	listCkeParamObj.Append(spResultParam);


	CATICkeParm_var spReturnedParm = NULL_var;
	spCkeActionFunc->Run(&listCkeParamObj, spReturnedParm, NULL);

	spResultParam = listCkeParamObj[listCkeParamObj.Size()];
	if (NULL_var != spResultParam)
	{
		CATICkeInst_var spCkeInstance = spResultParam->Value();
		if (NULL_var != spCkeInstance)
		{
			CATBaseUnknown_var spResultObject = spCkeInstance->AsObject();
			if (NULL_var != spResultObject)
			{
				ModifyPartParams(spResultObject);
			}
		}
	}

	this->RequestDelayedDestruction();
	return;
}
//修改零件参数
HRESULT CallEngineeringTemplate2Cmd::ModifyPartParams(const CATIPLMNavReference_var &ispProdRef)
{
	if (NULL_var == ispProdRef) return E_FAIL;

	CATIPLMNavRepReference_var spPLMRepRef = NULL_var;
	CATIMmiMechanicalFeature_var spPartObject = NULL_var;
	HRESULT rc = CAAMmrGetPartFromProduct(ispProdRef, spPLMRepRef, spPartObject);
	if (FAILED(rc) || (NULL_var == spPartObject)) return E_FAIL;
	if (NULL_var == spPLMRepRef) return E_FAIL;

	CATIParmPublisher_var spParamPublisher = spPLMRepRef;
	if (NULL_var == spParamPublisher)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::GetPartParams()-NULL_var == spParamPublisher" << endl;
		return E_FAIL;
	}

	CATIKweModelServices_var spKweModelServices = CATCkeGlobalFunctions::GetModelServices();
	if (NULL_var == spKweModelServices)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::GetPartParams()-NULL_var == spKweModelServices" << endl;
		return E_FAIL;
	}

	CATBaseUnknown_var spRootParamSetObj = NULL_var;
	spRootParamSetObj = spKweModelServices->GetCurrentSet(CATIKweModelServices::Parameter, spParamPublisher);
	if (NULL_var == spRootParamSetObj) return E_FAIL;


	CATICkeParameterSet_var spPiDaiParamSet = NULL_var;
	GetParamSetByName(spRootParamSetObj,"皮带",spPiDaiParamSet);
	if (NULL_var != spPiDaiParamSet)
	{
		CATLISTV(CATBaseUnknown_var)* plistPDParamObj = spPiDaiParamSet->Parameters();//皮带参数
		if (NULL != plistPDParamObj)
		{
			for (int i = 1; i <= plistPDParamObj->Size(); i++)
			{
				CATICkeParm_var spCkeParam = (*plistPDParamObj)[i];
				CATUnicodeString strParamName = spCkeParam->Name();

				strParamName = GetRightParamName(strParamName);
				if (CATUnicodeString("皮带宽度") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerPDKD->GetCurrentValue();
					cout << "ivalue == " << iValue << endl;
					spCkeParam->Valuate(iValue/1000.0f);
				}
				else if (CATUnicodeString("皮带厚度") == strParamName)
				{
					double iValue =  _pCallEngineeringTemplate2Dlg->_SpinnerPDHD->GetCurrentValue();
					cout << "ivalue == " << iValue << endl;
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("皮带槽角") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerPDCJ->GetCurrentValue();
					cout << "ivalue == " << iValue << endl;
					spCkeParam->Valuate(iValue*3.1415926f / 180.0f);
				}
				else if (CATUnicodeString("上部皮带离中心线距离") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerSPDJZXXJL->GetCurrentValue();
					cout << "ivalue == " << iValue << endl;
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("下部皮带离中心线距离") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerXPDJZXXJL->GetCurrentValue();
					cout << "ivalue == " << iValue << endl;
					spCkeParam->Valuate(iValue / 1000.0f);
				}
			}

			delete[] plistPDParamObj; plistPDParamObj = NULL;
		}
	}

	CATICkeParameterSet_var spZhiJiaParamSet = NULL_var;
	GetParamSetByName(spRootParamSetObj, "支架", spZhiJiaParamSet);
	if (NULL_var != spZhiJiaParamSet)
	{
		CATLISTV(CATBaseUnknown_var)* plistZJParamObj = spZhiJiaParamSet->Parameters();//支架参数
		if (NULL != plistZJParamObj)
		{
			for (int i = 1; i <= plistZJParamObj->Size(); i++)
			{
				CATICkeParm_var spCkeParam = (*plistZJParamObj)[i];
				CATUnicodeString strParamName = spCkeParam->Name();

				strParamName = GetRightParamName(strParamName);
				if (CATUnicodeString("机头支架长") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerJTZJC->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("机头支架宽") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerJTZJK->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("机尾支架长") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerJWZJC->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("机尾支架宽") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerJWZJK->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
			}

			delete[] plistZJParamObj; plistZJParamObj = NULL;
		}
	}

	CATICkeParameterSet_var spDJ1ParamSet = NULL_var;
	GetParamSetByName(spRootParamSetObj, "电机类型1垂直轴", spDJ1ParamSet);
	if (NULL_var != spDJ1ParamSet)
	{
		CATLISTV(CATBaseUnknown_var)* plistDJParamObj = spDJ1ParamSet->Parameters();//垂直轴
		if (NULL != plistDJParamObj)
		{
			for (int i = 1; i <= plistDJParamObj->Size(); i++)
			{
				CATICkeParm_var spCkeParam = (*plistDJParamObj)[i];
				CATUnicodeString strParamName = spCkeParam->Name();

				strParamName = GetRightParamName(strParamName);
				if (CATUnicodeString("电机整体长度1") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerDJZTCD->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("电机直径1") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerDJZJ->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("电机长1") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerDJC->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("减速机1（宽）") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerJSJKD->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("电机轴线到皮带中心面距离1") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerJPDZXMJL->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
			}

			delete[] plistDJParamObj; plistDJParamObj = NULL;
		}
	}

	CATICkeParameterSet_var spDJ2ParamSet = NULL_var;
	GetParamSetByName(spRootParamSetObj, "电机类型2平行轴", spDJ2ParamSet);
	if (NULL_var != spDJ2ParamSet)
	{
		CATLISTV(CATBaseUnknown_var)* plistDJParamObj = spDJ2ParamSet->Parameters();//垂直轴
		if (NULL != plistDJParamObj)
		{
			for (int i = 1; i <= plistDJParamObj->Size(); i++)
			{
				CATICkeParm_var spCkeParam = (*plistDJParamObj)[i];
				CATUnicodeString strParamName = spCkeParam->Name();

				strParamName = GetRightParamName(strParamName);
				if (CATUnicodeString("电机整体长度2") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerDJZTCD2->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("电机直径2") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerDJZJ2->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("电机长2") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerDJC2->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("减速机2（宽）") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerJSJKD2->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
				else if (CATUnicodeString("减速机轴线到皮带中心面距离2") == strParamName)
				{
					double iValue = _pCallEngineeringTemplate2Dlg->_SpinnerJPDZXJL2->GetCurrentValue();
					spCkeParam->Valuate(iValue / 1000.0f);
				}
			}

			delete[] plistDJParamObj; plistDJParamObj = NULL;
		}
	}

	CATICkeParameterSet_var spDJ3ParamSet = NULL_var;
	GetParamSetByName(spRootParamSetObj, "电机", spDJ3ParamSet);//其它参数
	if (NULL_var != spDJ3ParamSet)
	{
		CATLISTV(CATBaseUnknown_var)* plistDJParamObj = spDJ3ParamSet->Parameters();//垂直轴
		if (NULL != plistDJParamObj)
		{
			for (int i = 1; i <= plistDJParamObj->Size(); i++)
			{
				CATICkeParm_var spCkeParam = (*plistDJParamObj)[i];
				CATUnicodeString strParamName = spCkeParam->Name();

				strParamName = GetRightParamName(strParamName);
				if (CATUnicodeString("电机布置") == strParamName)
				{
					CATUnicodeString istrText("");
					_pCallEngineeringTemplate2Dlg->_ComboDJBZ->GetField(istrText);
					spCkeParam->Valuate(istrText);
				}
				else if (CATUnicodeString("电机单双") == strParamName)
				{
					CATUnicodeString istrText("");
					_pCallEngineeringTemplate2Dlg->_ComboDJDS->GetField(istrText);
					spCkeParam->Valuate(istrText);
				}
				else if (CATUnicodeString("电机位置") == strParamName)
				{
					CATUnicodeString istrText("");
					_pCallEngineeringTemplate2Dlg->_ComboDJWZ->GetField(istrText);
					spCkeParam->Valuate(istrText);
				}
				else if (CATUnicodeString("电机左右侧") == strParamName)
				{
					CATUnicodeString istrText("");
					_pCallEngineeringTemplate2Dlg->_ComboDJZYC->GetField(istrText);
					spCkeParam->Valuate(istrText);
				}
			}

			delete[] plistDJParamObj; plistDJParamObj = NULL;
		}
	}

	CAAUpdateObject(spPartObject);
	return S_OK;
}
//更新特征
HRESULT CallEngineeringTemplate2Cmd::CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU)
{
	if (NULL_var == spUpdateObjectBU)
	{
		cout << "ERROR:CAAUpdateObject() - spUpdateObjectBU is NULL!" << endl;
		return E_FAIL;
	}

	CATIUseEntity *piUseEntity = NULL;
	HRESULT rc = spUpdateObjectBU->QueryInterface(IID_CATIUseEntity, (void**)&piUseEntity);
	if (SUCCEEDED(rc))
	{
		rc = DataCommonProtocolServices::Update(piUseEntity);
		if (FAILED(rc))
		{
			CATError * pError = CATError::CATGetLastError(rc);
			if (NULL != pError)
			{
				cerr << "Error message is " << pError->GetNLSMessage() << endl;
				pError->Release();
				pError = NULL;
			}
		}
		piUseEntity->Release();
		piUseEntity = NULL;
	}

	return rc;
}
//获取正确的参数名称
CATUnicodeString CallEngineeringTemplate2Cmd::GetRightParamName(const CATUnicodeString &istrfullParamName)
{
	int iLength = istrfullParamName.GetLengthInChar();
	if (0 == iLength) return "";

	int iStartPos = 0;
	for (int i = iLength - 1; i >= 0; i--)
	{
		CATUnicodeChar iCurrentChar = istrfullParamName[i];
		if (iCurrentChar == CATUnicodeChar('\\'))
		{
			iStartPos = i + 1;
			break;
		}
	}

	CATUnicodeString strValue("");
	strValue = istrfullParamName.SubString(iStartPos, iLength - iStartPos);
	return strValue;
}
//获取参数集下的参数集
HRESULT CallEngineeringTemplate2Cmd::GetParamSetByName(const CATICkeParameterSet_var &ispParentSet,
	                                                   const CATUnicodeString &istrParmSetName,
	                                                   CATICkeParameterSet_var &ospParamSet)
{
	if (NULL_var == ispParentSet) return E_FAIL;

	CATIAParameterSet* piCATIAParamSet = NULL;
	HRESULT rc = ispParentSet->QueryInterface(IID_CATIAParameterSet, (void**)&piCATIAParamSet);
	if (FAILED(rc) && (NULL != piCATIAParamSet)) return E_FAIL;

	CATIAParameterSets* piParamsSets = NULL;
	piCATIAParamSet->get_ParameterSets(piParamsSets);
	if (NULL == piParamsSets) return E_FAIL;

	piCATIAParamSet->Release(); piCATIAParamSet = NULL;

	CATBoolean IsFind = FALSE;
	CATLong iCount = 0;
	piParamsSets->get_Count(iCount);
	for (long i = 1; i <= iCount; i++)
	{
		//Item
		CATVariant IndexVar;
		::BuildVariant(i, IndexVar);
		CATIAParameterSet* piCurrentParmSet = NULL;
		piParamsSets->Item(IndexVar, piCurrentParmSet);
		if (NULL != piCurrentParmSet)
		{
			CATBSTR bstrSetName;
			piCurrentParmSet->get_Name(bstrSetName);
			CATUnicodeString strSetName("");
			strSetName.BuildFromBSTR(bstrSetName);
			
			if (strSetName == istrParmSetName)
			{
				ospParamSet = piCurrentParmSet;
				IsFind = TRUE;
				break;
			}
			else
			{
				CATICkeParameterSet_var spCurrentParamSet = piCurrentParmSet;
				GetParamSetByName(spCurrentParamSet, istrParmSetName, ospParamSet);
			}
				
		}
	}
	piParamsSets->Release(); piParamsSets = NULL;

	return S_OK;
}
//返回Part节点
HRESULT CallEngineeringTemplate2Cmd::CAAMmrGetPartFromProduct(const CATIPLMNavReference_var &ispPLMNavRef,
	                                                          CATIPLMNavRepReference_var &ospPLMRepRef,
	                                                          CATIMmiMechanicalFeature_var &ospPartFeature)

{
	HRESULT rc = E_FAIL;

	if (NULL_var == ispPLMNavRef) return E_FAIL;
	// Retrieve the first inst rep ref
	CATIPLMNavRepInstance * pNavRepInst = NULL;

	CATListPtrCATIPLMNavEntity ListNavEntity = NULL;
	CATPLMCoreType TypeRepInstance = PLMCoreRepInstance;
	ispPLMNavRef->ListChildren(ListNavEntity, 1, &TypeRepInstance);

	if (ListNavEntity.Size() >= 1)
	{
		CATIPLMNavEntity *pCurrent = ListNavEntity[1];
		rc = pCurrent->QueryInterface(IID_CATIPLMNavRepInstance, (void**)& pNavRepInst);
	}

	// Retrieve the reference of the first inst rep ref
	CATIPLMNavRepReference *pNavRepRef = NULL;
	if (NULL != pNavRepInst)
	{
		rc = pNavRepInst->GetRepReferenceInstanceOf(pNavRepRef);
		pNavRepInst->Release(); pNavRepInst = NULL;
	}

	// change the loading mode
	if (NULL != pNavRepRef)
	{
		CATIPsiRepresentationLoadMode *piRepLoadMode = NULL;
		rc = pNavRepRef->QueryInterface(IID_CATIPsiRepresentationLoadMode, (void **)&piRepLoadMode);
		if (SUCCEEDED(rc) && NULL != piRepLoadMode)
		{
			rc = piRepLoadMode->ChangeLoadingMode(CATIPsiRepresentationLoadMode::EditMode);
			piRepLoadMode->Release();
			piRepLoadMode = NULL;
		}
	}

	//Retrieve the applicative container
	CATIMmiPrtContainer * pContainer = NULL;
	if (SUCCEEDED(rc) && (NULL != pNavRepRef))
	{
		ospPLMRepRef = pNavRepRef;
		rc = pNavRepRef->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pContainer);
		pNavRepRef->Release();
		pNavRepRef = NULL;
	}

	if (SUCCEEDED(rc) && (NULL != pContainer))
	{
		pContainer->GetMechanicalPart(ospPartFeature);
		pContainer->Release();
		pContainer = NULL;
	}
	return rc;
}
//获取EKL中的Action
HRESULT CallEngineeringTemplate2Cmd::GetKnowledgeAction(const CATIPLMNavReference_var &ispParentNavRef,
	                                                    const CATUnicodeString &istrActionName,
	                                                    CATBaseUnknown_var &ospActionBUObj)
{
	if (NULL_var == ispParentNavRef) return E_FAIL;

	CATIPLMNavRepReference_var spKnowledgeRepRef = NULL_var;

	CATPLMCoreType  FilterPLMType = PLMCoreRepInstance;
	CATLISTP(CATIPLMNavEntity)  listRepInsChild = NULL;
	ispParentNavRef->ListChildren(listRepInsChild, 1, &FilterPLMType);
	for (int i = 1; i <= listRepInsChild.Size(); i++)
	{
		CATIPLMNavRepInstance_var spRepInstance = listRepInsChild[i];
		if (NULL_var == spRepInstance) continue;

		CATIPLMNavRepReference* piRepReference = NULL;
		spRepInstance->GetRepReferenceInstanceOf(piRepReference);
		if (NULL != piRepReference)
		{
			CATIPLMComponent_var spPLMComponent = piRepReference;

			CATUnicodeString strPLMType("");
			RetrieveComponentType(spPLMComponent, strPLMType);
			if (CATUnicodeString("Knowledgeware") == strPLMType)
			{
				spKnowledgeRepRef = piRepReference;
			}
			piRepReference->Release(); piRepReference = NULL;
		}

		if (NULL_var != spKnowledgeRepRef) break;
	}

	if (NULL_var == spKnowledgeRepRef) return E_FAIL;

	CATIKweModelServices_var spKweModelServices = CATCkeGlobalFunctions::GetModelServices();
	if (NULL_var == spKweModelServices) return E_FAIL;

	HRESULT rc = E_FAIL;
	CATIParmPublisher_var spParmPublisher = spKnowledgeRepRef;
	if (NULL_var != spParmPublisher)
	{
		CATLISTV(CATBaseUnknown_var) listCkeFuncObjs = NULL;
		spKweModelServices->VisibleRelations(spParmPublisher, listCkeFuncObjs, 1);
		for (int i = 1; i <= listCkeFuncObjs.Size(); i++)
		{
			CATBaseUnknown_var spActionBUObj = listCkeFuncObjs[i];
			CATIAlias_var spAliasName = spActionBUObj;
			CATUnicodeString strAliasName = spAliasName->GetAlias();
			if (istrActionName == strAliasName)
			{
				rc = S_OK;
				ospActionBUObj = spActionBUObj;
				break;
			}
		}
	}

	return rc;
}
//get PLMComponent type
HRESULT CallEngineeringTemplate2Cmd::RetrieveComponentType(const CATBaseUnknown_var &ispPLMObject,
	CATUnicodeString &ostrType)
{
	if (NULL_var == ispPLMObject)
	{
		cout << "ERROR:RetrieveComponentType()-NULL_var == ispPLMObject" << endl;
		return E_FAIL;
	}

	CATIPLMComponent_var spPLMComponent = ispPLMObject;
	if (NULL_var == spPLMComponent)
	{
		cout << "ERROR:RetrieveComponentType()-NULL_var == spPLMComponent" << endl;
		return E_FAIL;
	}
	//Type
	CATIAdpType *piAdpType = NULL;
	HRESULT rc = spPLMComponent->GetAdpType(piAdpType);
	if (FAILED(rc) || NULL == piAdpType)
	{
		cout << "ERROR:RetrieveComponentType()-NULL == piAdpType" << endl;
		return E_FAIL;
	}
	CATUnicodeString strProductTypeValue("");
	CATIType *piCkeType = NULL;
	rc = CATPLMTypeServices::GetKweTypeFromAdpType(piAdpType, piCkeType);
	if (SUCCEEDED(rc))
	{
		CATUnicodeString CurrentCustoName = piCkeType->Name();
		//cout << "Current Type Name is :" << CurrentCustoName.ConvertToChar() << endl;

		//CATUnicodeString CurrentUserName = piCkeType->UserName();
		//cout << "Current User Name is :" << CurrentUserName.ConvertToChar() << endl;
		ostrType = CurrentCustoName;

		piAdpType->Release();
		piAdpType = NULL;

		piCkeType->Release();
		piCkeType = NULL;
	}

	return rc;
}
HRESULT CallEngineeringTemplate2Cmd::AddChldProduct(const CATIPLMNavReference_var &ispParentProRef,
	const CATIPLMNavReference_var &ispChildProRef,
	CATBaseUnknown_var &ospProdInstanceObj)
{
	if (NULL_var == ispParentProRef) return E_FAIL;
	if (NULL_var == ispChildProRef) return E_FAIL;

	CATIPLMProducts * piRefPLMProducts = NULL;
	HRESULT rc = ispChildProRef->QueryInterface(IID_CATIPLMProducts, (void**)&piRefPLMProducts);
	if (FAILED(rc) || (NULL == piRefPLMProducts))
	{
		cout << "ERROR:ClsPLMUtilities::AddChldProduct()-NULL == piRefPLMProducts" << endl;
		return rc;
	}

	CATBaseUnknown* piProductInstanceObj = NULL;
	CATIPLMProducts * piPLMProductsRoot = NULL;
	rc = ispParentProRef->QueryInterface(IID_CATIPLMProducts, (void**)&piPLMProductsRoot);
	if (SUCCEEDED(rc) && (NULL != piPLMProductsRoot))
	{
		rc = piPLMProductsRoot->AddProduct(piRefPLMProducts, piProductInstanceObj);
		piPLMProductsRoot->Release();
		piPLMProductsRoot = NULL;
	}

	if (NULL != piProductInstanceObj)
	{
		ospProdInstanceObj = piProductInstanceObj;
		piProductInstanceObj->Release(); piProductInstanceObj = NULL;
	}
	piRefPLMProducts->Release(); piRefPLMProducts = NULL;
	return rc;
}
//消息类型：Error、Information、Warning
int CallEngineeringTemplate2Cmd::DisplayMessage(const CATString &istrMsgType,
	                                            const CATUnicodeString &iusMsgToDisplay,
	                                            const CATUnicodeString &iusDlgTitle)
{

	int RetUserReply = 0;

	CATDlgStyle Dlgstyle;
	CATUnicodeString usDlgTitle = "";

	if (istrMsgType == "Error")
	{
		Dlgstyle = CATDlgNfyError | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Error";
	}
	else if (istrMsgType == "Information")
	{
		Dlgstyle = CATDlgNfyInformation | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Information";
	}
	else if (istrMsgType == "Warning")
	{
		Dlgstyle = CATDlgNfyWarning | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Warning";
	}

	if (iusDlgTitle != "")usDlgTitle = iusDlgTitle;

	CATDlgNotify* pDlgNotify = new CATDlgNotify((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(), istrMsgType, Dlgstyle);
	if (!pDlgNotify) return 0;

	RetUserReply = pDlgNotify->DisplayBlocked(iusMsgToDisplay, usDlgTitle); // Get the User selected button
	return RetUserReply;
}