//===================================================================
// COPYRIGHT ATOZ 2020/05/28
//===================================================================
// ClsConfigXMLServices.cpp
// Header definition of class ClsConfigXMLServices
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/05/28 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef ClsConfigXMLServices_H
#define ClsConfigXMLServices_H

//XMLParserItf includes
#include "CATIXMLDOMDocumentBuilder.h"
#include "CATIDOMImplementation.h"
#include "CATIDOMDocument.h"
#include "CATIDOMElement.h"
#include "CATIDOMDocumentType.h"
#include "CATIDOMText.h"
#include "CATIXMLSAX2Factory.h"
#include "CATISAXEntityResolver.h"
#include "CATIDOMNodeList.h"

//SystemTS includes
#include "CATToken.h"

#include "iostream.h"
#include "fstream.h"
#include <vector>
using namespace std;
//-----------------------------------------------------------------------

class ClsConfigXMLServices
{
public:
// Standard constructors and destructors
// -------------------------------------
ClsConfigXMLServices ();
virtual ~ClsConfigXMLServices ();

//get dllPath
static HRESULT Get_ComputeDataExePath(CATUnicodeString &strExePath);

//open xml 
static HRESULT OpenXMLByfullName(CATUnicodeString istrXMLPath,
	CATIDOMDocument_var &ospDOMDocument);

//获取配置的CUPS 名称
static HRESULT GetCUPSConfigData(const CATUnicodeString &istrXMLPath,
	const CATUnicodeString &istrType,
	CATUnicodeString &ostrFeatID,
	CATUnicodeString &ostrFeatVersion);

//读取模板说明文件
static HRESULT ReadTemplateText(CATUnicodeString strfilePath,
	                            CATLISTV(CATUnicodeString) &olistTextContent);

private:
// Copy constructor and equal operator
// -----------------------------------
ClsConfigXMLServices (ClsConfigXMLServices &);
ClsConfigXMLServices& operator=(ClsConfigXMLServices&);

};

//-----------------------------------------------------------------------

#endif
