//===================================================================
// COPYRIGHT atoz 2020/12/07
//===================================================================
// CallEngineeringTemplate10Cmd.cpp
// Header definition of class CallEngineeringTemplate10Cmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/12/07 Creation: Code generated by the 3DS wizard
//===================================================================

#include "CallEngineeringTemplate10Cmd.h"
#include "CATIndicationAgent.h"
#include "CATMathPlane.h"

#include "CATCreateExternalObject.h"
CATCreateClass( CallEngineeringTemplate10Cmd);


//-------------------------------------------------------------------------
// Constructor
//-------------------------------------------------------------------------
CallEngineeringTemplate10Cmd::CallEngineeringTemplate10Cmd() :
CATStateCommand ("CallEngineeringTemplate10Cmd", CATDlgEngOneShot, CATCommandModeExclusive)
//  Valid states are CATDlgEngOneShot and CATDlgEngRepeat
, _strTemplateID("")
, _strActionName("")
, _strModelViewID("")
, _strModelViewVersion("")
, _listTemplateInstruction(NULL)
, _pCallEngineeringTemplate10Dlg(NULL)
, _spParentOcurr(NULL_var)
, _pSelASPathElemAgent(NULL)
, _pSelASDlgAgent(NULL)
, _spAxisFeature(NULL_var)
, _ModelBag()
{
	HRESULT rc = InitializeConfigData();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}

	rc = InitializeMainDialog();
	if (FAILED(rc))
	{
		this->RequestDelayedDestruction();
		return;
	}
	for (int i = 1; i <= _listTemplateInstruction.Size(); i++)
	{
		_pCallEngineeringTemplate10Dlg->_EditorUseSteps->SetLine(_listTemplateInstruction[i]);
	}

	CATIMmiUsePrtPart_var spCurrentPart = NULL_var;
	GetCurrentPart(spCurrentPart, _spParentOcurr);
	if (NULL_var == _spParentOcurr)
	{
		DisplayMessage("Error", "Please work in product context!", "ERROR");
		this->RequestDelayedDestruction();
		return;
	}
}

HRESULT CallEngineeringTemplate10Cmd::InitializeMainDialog()
{
	_pCallEngineeringTemplate10Dlg = new CallEngineeringTemplate10Dlg((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(),
		"CallEngineeringTemplateDlg");
	_pCallEngineeringTemplate10Dlg->Build();
	
	/*CATNavigation3DViewer* p3DViewer = _pCallEngineeringTemplate10Dlg->_Navigation3DViewerModel;
	if (NULL != p3DViewer)
	{
		p3DViewer->SetBackgroundColor(0.235294f, 0.4f, 0.501961f);
	}*/

	_pCallEngineeringTemplate10Dlg->_SelectorListAxis->SetLine("No Selection");

	CATDlgSelectorList* pDlgSelList = _pCallEngineeringTemplate10Dlg->_SelectorListAxis;
	if (NULL != pDlgSelList)
	{
		int ArraySel[1] = { 0 };
		pDlgSelList->SetSelect(ArraySel, 1);
	}

	_pCallEngineeringTemplate10Dlg->_SpinnerD1->SetValue(2.5f);
	_pCallEngineeringTemplate10Dlg->_SpinnerD2->SetValue(5.5f);

	_pCallEngineeringTemplate10Dlg->_SpinnerD3->SetValue(0.1f);
	_pCallEngineeringTemplate10Dlg->_SpinnerT1->SetValue(0.02f);
	_pCallEngineeringTemplate10Dlg->_SpinnerT3->SetValue(0.2f);
	_pCallEngineeringTemplate10Dlg->_SpinnerH->SetValue(4.5f);

	_pCallEngineeringTemplate10Dlg->_SpinnerA->SetFormat("%g deg");
	_pCallEngineeringTemplate10Dlg->_SpinnerA->SetValue((float)60);

	_pCallEngineeringTemplate10Dlg->_SpinnerX->SetValue(2.18f);
	_pCallEngineeringTemplate10Dlg->_SpinnerT2->SetValue(0.012f);
	_pCallEngineeringTemplate10Dlg->_SpinnerR->SetValue(1.5f);

	_pCallEngineeringTemplate10Dlg->_EditorV->SetLine("70.185");
	_pCallEngineeringTemplate10Dlg->_Editorx->SetLine("2511.473379");


	_pCallEngineeringTemplate10Dlg->_LabelView->SetIconName("TONG");
	_pCallEngineeringTemplate10Dlg->_LabelLog->SetIconName("I_ZMXALog");
	_pCallEngineeringTemplate10Dlg->SetVisibility(CATDlgShow);
	return S_OK;
}

HRESULT CallEngineeringTemplate10Cmd::GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart,
	CATIPLMNavOccurrence_var &ospParentOccurr)
{
	CATFrmEditor* pFrmEditor = CATFrmEditor::GetCurrentEditor();
	if (NULL == pFrmEditor) return E_FAIL;

	CATPathElement& CurrentElemPath = pFrmEditor->GetUIActiveObject();
	CATBaseUnknown* pCurrentObject = CurrentElemPath.FindElement(IID_CATIMmiUsePrtPart);
	if (NULL != pCurrentObject)
	{
		ospPrtPart = pCurrentObject;
	}

	CATBaseUnknown* pOccurrObj = CurrentElemPath.FindElement(IID_CATIPLMNavOccurrence);
	if (NULL != pOccurrObj)
	{
		CATIPLMNavOccurrence_var spCurrentOccurr = pOccurrObj;
		if (NULL_var != spCurrentOccurr)
		{
			CATIPLMNavOccurrence* piParentOccurr = NULL;
			spCurrentOccurr->GetFather(piParentOccurr);
			if (NULL != piParentOccurr)
			{
				ospParentOccurr = piParentOccurr;
				piParentOccurr->Release(); piParentOccurr = NULL;
			}
		}

		//CATIPLMNavOccurrence_var spCurrentOccurr = pOccurrObj;
		//CATIAlias_var spAliasName = spCurrentOccurr;
		//cout << "pCurrentObject == " << spAliasName->GetAlias() << endl;
	}
	return S_OK;
}

//-------------------------------------------------------------------------
// Destructor
//-------------------------------------------------------------------------
CallEngineeringTemplate10Cmd::~CallEngineeringTemplate10Cmd()
{
	if (NULL != _pSelASDlgAgent)
	{
		_pSelASDlgAgent->RequestDelayedDestruction();
		_pSelASDlgAgent = NULL;
	}

	if (NULL != _pSelASPathElemAgent)
	{
		_pSelASPathElemAgent->RequestDelayedDestruction();
		_pSelASPathElemAgent = NULL;
	}

	if (NULL != _pCallEngineeringTemplate10Dlg)
	{
		_pCallEngineeringTemplate10Dlg->RequestDelayedDestruction();
		_pCallEngineeringTemplate10Dlg = NULL;
	}

	_ModelBag.RemoveAll();

}

HRESULT CallEngineeringTemplate10Cmd::InitializeConfigData()
{
	CATUnicodeString strInstallPath("");
	ClsConfigXMLServices::Get_ComputeDataExePath(strInstallPath);
	if (CATUnicodeString("") == strInstallPath) return E_FAIL;

	CATUnicodeString strProjectConfigPath = strInstallPath + "bin\\\ATOZ\\CAAEKLConfig";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		DisplayMessage("Error", "找不到CAAEKLConfig配置文件夹!", "ERROR");
		return E_FAIL;
	}

	const char* pxmlfilePath = CATFindPath("CAAEKLConfig.xml", strProjectConfigPath);
	if (NULL == pxmlfilePath)
	{
		DisplayMessage("Error", "找不到CAAEKLConfig.xml配置文件!", "ERROR");
		return E_FAIL;
	}

	CATUnicodeString strXMLFilePath = pxmlfilePath;
	HRESULT rc = ClsConfigXMLServices::GetCUPSConfigData(strXMLFilePath, "桶", _strTemplateID,
		_strActionName, _strModelViewID, _strModelViewVersion);
	if (FAILED(rc))
	{
		DisplayMessage("Error", "读取CAAEKLConfig.xml配置文件失败!", "ERROR");
		return E_FAIL;
	}

	strProjectConfigPath = strInstallPath + "bin\\\ATOZ";
	if (0 != ::access(strProjectConfigPath.ConvertToChar(), 0))
	{
		DisplayMessage("Error", "找不到ATOZ配置文件夹!", "ERROR");
		return E_FAIL;
	}
	else
	{
		const char* pfilePath = CATFindPath("TemplateInstruction_7.ini", strProjectConfigPath);
		if (NULL != pfilePath)
		{
			ClsConfigXMLServices::ReadTemplateText(pfilePath, _listTemplateInstruction);
			//for (int i = 1; i <= _listTemplateInstruction.Size(); i++)
			//{
			//	cout << "_listTemplateInstruction["<<i<<"] == "<< _listTemplateInstruction[i] << endl;
			//}
		}
	}

	return S_OK;
}

int CallEngineeringTemplate10Cmd::DisplayMessage(const CATString &istrMsgType,
	const CATUnicodeString &iusMsgToDisplay,
	const CATUnicodeString &iusDlgTitle)
{

	int RetUserReply = 0;

	CATDlgStyle Dlgstyle;
	CATUnicodeString usDlgTitle = "";

	if (istrMsgType == "Error")
	{
		Dlgstyle = CATDlgNfyError | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Error";
	}
	else if (istrMsgType == "Information")
	{
		Dlgstyle = CATDlgNfyInformation | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Information";
	}
	else if (istrMsgType == "Warning")
	{
		Dlgstyle = CATDlgNfyWarning | CATDlgNfyOK | CATDlgWndModal;
		usDlgTitle = "Warning";
	}

	if (iusDlgTitle != "")usDlgTitle = iusDlgTitle;

	CATDlgNotify* pDlgNotify = new CATDlgNotify((CATApplicationFrame::GetApplicationFrame())->GetMainWindow(), istrMsgType, Dlgstyle);
	if (!pDlgNotify) return 0;

	RetUserReply = pDlgNotify->DisplayBlocked(iusMsgToDisplay, usDlgTitle); // Get the User selected button
	return RetUserReply;
}

//-------------------------------------------------------------------------
// BuildGraph()
//-------------------------------------------------------------------------
void CallEngineeringTemplate10Cmd::BuildGraph()
{
	_pSelASPathElemAgent = new CATPathElementAgent("SelectAxisSystem");
	_pSelASPathElemAgent->SetBehavior(CATDlgEngWithPSOHSO | CATDlgEngWithPrevaluation | CATDlgEngOneShot | CATDlgEngWithTooltip);
	_pSelASPathElemAgent->AddElementType(IID_CATIMf3DAxisSystem);

	_pSelASDlgAgent = new CATDialogAgent("SelASDlg");
	_pSelASDlgAgent->AcceptOnNotify(_pCallEngineeringTemplate10Dlg->_SelectorListAxis,
		_pCallEngineeringTemplate10Dlg->_SelectorListAxis->GetListSelectNotification());

	CATDialogState * SelectASState = GetInitialState("Please select Axis System");
	SelectASState->AddDialogAgent(_pSelASPathElemAgent);

	AddTransition(SelectASState, SelectASState,
		IsOutputSetCondition(_pSelASPathElemAgent),
		Action((ActionMethod)&CallEngineeringTemplate10Cmd::SelectASObj));

	//click Wndclose buttion
	AddAnalyseNotificationCB(_pCallEngineeringTemplate10Dlg,
		_pCallEngineeringTemplate10Dlg->GetWindCloseNotification(),
		(CATCommandMethod)&CallEngineeringTemplate10Cmd::ExitCmd, NULL);
	//click cancel button
	AddAnalyseNotificationCB(_pCallEngineeringTemplate10Dlg,
		_pCallEngineeringTemplate10Dlg->GetDiaCANCELNotification(),
		(CATCommandMethod)&CallEngineeringTemplate10Cmd::ExitCmd, NULL);

	//click OK button
	AddAnalyseNotificationCB(_pCallEngineeringTemplate10Dlg,
		_pCallEngineeringTemplate10Dlg->GetDiaOKNotification(),
		(CATCommandMethod)&CallEngineeringTemplate10Cmd::OKAction, NULL);

	AddAnalyseNotificationCB(_pCallEngineeringTemplate10Dlg->_PushButton,
		_pCallEngineeringTemplate10Dlg->_PushButton->GetPushBActivateNotification(),
		(CATCommandMethod)&CallEngineeringTemplate10Cmd::Compute, NULL);

}

void CallEngineeringTemplate10Cmd::SelectASObj(void* idata)
{
	CATPathElement* pPathElem = _pSelASPathElemAgent->GetValue();
	CATBaseUnknown* pBaseUnknown = _pSelASPathElemAgent->GetElementValue();
	_pSelASPathElemAgent->InitializeAcquisition();

	_spAxisFeature = pBaseUnknown;

	CATUnicodeString strFullPath("");
	PathElementString(pPathElem, strFullPath);

	CATDlgSelectorList* pDlgSelList = _pCallEngineeringTemplate10Dlg->_SelectorListAxis;
	if (NULL != pDlgSelList)
	{
		pDlgSelList->ClearLine();
		pDlgSelList->SetLine(strFullPath);
	}

}

void CallEngineeringTemplate10Cmd::Compute(void* idata)
{
	_params.clear();
	HRESULT rc = S_OK;
	CATIPLMNavReference_var spProdRef(NULL_var);
	rc = GetEngineeringTemp(spProdRef);
	if (FAILED(rc))
	{
		DisplayMessage("Warning", "未能找到实例化模板!", "警告");
		return;
	}

	//获取container
	CATIMmiPrtContainer *pIPrtContOnPC(NULL);
	CATIPLMComponent *piPLMCompOnFeatRef(NULL);
	rc = GetUDFContainerFromDB(_ModelBag, spProdRef, piPLMCompOnFeatRef, pIPrtContOnPC);
	if (FAILED(rc) || NULL == pIPrtContOnPC || NULL == piPLMCompOnFeatRef)
	{

		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - GetUDFContainerFormDB is failed!" << endl;
		return;
	}
	//DisplayAttributes(piPLMCompOnFeatRef);

	CATIMmiMechanicalFeature_var spMechFeatOnPart;
	rc = pIPrtContOnPC->GetMechanicalPart(spMechFeatOnPart);
	CATIPartRequest_var spPartRequest = spMechFeatOnPart;
	if (NULL_var == spPartRequest)
	{
		cout << "未获取spPartRequest" << endl;
		return;
	}

	CATIPLMComponent_var spiPLMCompOnFeatRef(NULL_var);
	spiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;

	CATBaseUnknown_var spMainBody = NULL_var;
	rc = spPartRequest->GetMainBody("", spMainBody);

	CATIMmiUseBodyContent_var spBodyContent = spMainBody;
	CATListValCATBaseUnknown_var listFeat;
	if(NULL_var != spBodyContent)
		rc = spBodyContent->GetMechanicalFeatures(listFeat);

	if (0 == listFeat.Size())
		return;
	
	CATBaseUnknown_var spBUOnFeat{ listFeat[1] };
	cout << spBUOnFeat->GetImpl()->IsA() << endl;

	CATIUdfFeatureInstance_var spUdfObject = listFeat[1];
	if (NULL_var == spUdfObject)
	{
		cout << "NULL_var == spUdfObject" << endl;
		return;
	}

	CATListValCATBaseUnknown_var * pListParam = NULL;
	rc = spUdfObject->GetParameters(pListParam);

	if (SUCCEEDED(rc) && (NULL != pListParam))
	{
		for (int i = 1; i <= pListParam->Size(); i++)
		{
			CATICkeParm_var spCkeParm = (*pListParam)[i];

			CATUnicodeString strParamName = spCkeParm->Name();
			strParamName = GetRightParamName(strParamName);
			cout << "ParamName: " << strParamName << endl;

			if (CATUnicodeString("D1") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerD1->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("D1", iValue));
			}
			else if (CATUnicodeString("D2") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerD2->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("D2", iValue));
			}
			else if (CATUnicodeString("D3") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerD3->GetValue();
				spCkeParm->Valuate(iValue);
				
			}
			else if (CATUnicodeString("T1") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerT1->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("T1", iValue));
			}
			else if (CATUnicodeString("T3") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerT3->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("T3", iValue));
			}
			else if (CATUnicodeString("H") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerH->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("H", iValue));
			}
			else if (CATUnicodeString("A") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerA->GetValue();
				spCkeParm->Valuate(iValue*3.1415926f / 180.0f);
			}
			else if (CATUnicodeString("V") == strParamName)
			{

			}
			else if (CATUnicodeString("x") == strParamName)
			{

			}
			else
			{
				cout << "参数错误" << endl;
			}
		}

		CAAUpdateObject(spUdfObject);

		for (int i = 1; i <= pListParam->Size(); i++)
		{
			CATICkeParm_var spCkeParm = (*pListParam)[i];

			CATUnicodeString strParamName = spCkeParm->Name();
			strParamName = GetRightParamName(strParamName);

			if (CATUnicodeString("V") == strParamName)
			{
				CATUnicodeString value = spCkeParm->Show();
				_pCallEngineeringTemplate10Dlg->_EditorV->SetLine(value);
			}
			else if (CATUnicodeString("x") == strParamName)
			{
				CATUnicodeString value = spCkeParm->Show();
				_pCallEngineeringTemplate10Dlg->_Editorx->SetLine(value);
			}
		}

		delete pListParam;
		pListParam = NULL;

	}

	
}

HRESULT CallEngineeringTemplate10Cmd::GetUDFContainerFromDB(CATOmbLifeCycleRootsBag &iobag,
	const CATIPLMNavReference_var &ispFeatNavRef,
	CATIPLMComponent *&opiPLMCompOnFeatRef,
	CATIMmiPrtContainer *&opIPrtContOnCAAUdfLoft)
{
	HRESULT rc = S_OK;

	//QI
	CATIPLMComponent_var spiPLMCompOnFeatRef = NULL_var;
	CATIPLMNavReference* pFeatNavRef = NULL;
	pFeatNavRef = (CATIPLMNavReference*)ispFeatNavRef;
	if (NULL == pFeatNavRef)
	{
		DisplayMessage("Warning", "(NULL == pFeatNavRef)!", "警告");
		return E_FAIL;
	}

	CATIPLMComponent* piPLMCompOnFeatRef = NULL;
	rc = pFeatNavRef->QueryInterface(IID_CATIPLMComponent, (void**)&piPLMCompOnFeatRef);
	if (FAILED(rc) || NULL == piPLMCompOnFeatRef)
	{
		DisplayMessage("Warning", "(NULL == opiPLMCompOnFeatRef)!", "警告");
		return E_FAIL;
	}


	opiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	opiPLMCompOnFeatRef->AddRef();

	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;

	/////////////////////////////////////////////////////////////////////////////////////

	//3DShape

	CATPLMCoreType coreType = CATPLMCoreType::PLMCoreRepInstance;
	CATListPtrCATIPLMNavEntity ChildrenList;

	rc = pFeatNavRef->ListChildren(ChildrenList, 1, &coreType);
	if (ChildrenList.Size() == 0)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ChildrenList.Size() == 0" << endl;
		return E_FAIL;
	}


	CATIPLMNavEntity *piNavEntity = ChildrenList[1];
	if (NULL == piNavEntity)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piNavEntity is NULL!" << endl;
		return E_FAIL;
	}

	CATIPLMNavRepInstance * piPrdObjOnRepInst = NULL;
	rc = piNavEntity->QueryInterface(IID_CATIPLMNavRepInstance, (void**)&piPrdObjOnRepInst);
	if (FAILED(rc) || NULL == piPrdObjOnRepInst)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piPrdObjOnRepInst is NULL!" << endl;
		return E_FAIL;
	}


	CATIPLMNavRepReference* pi3DShapeRepRefer = NULL;
	rc = piPrdObjOnRepInst->GetRepReferenceInstanceOf(pi3DShapeRepRefer);
	if (FAILED(rc) || NULL == pi3DShapeRepRefer)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - piFirst3DShapeRepRefer is NULL!" << endl;
		return E_FAIL;
	}
	piPrdObjOnRepInst->Release();
	piPrdObjOnRepInst = NULL;


	CATIPLMNavRepReference_var spi3DShapeRepRefer(pi3DShapeRepRefer);
	pi3DShapeRepRefer->Release();
	pi3DShapeRepRefer = NULL;

	// edit mode is no longer default
	CATIPsiRepresentationLoadMode_var spRepLoadMode = spi3DShapeRepRefer;
	if (NULL_var == spRepLoadMode)
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - spRepLoadMode is NULL!" << endl;
		return E_FAIL;
	}
	rc = spRepLoadMode->ChangeLoadingMode(CATIPsiRepresentationLoadMode::EditMode);
	if (FAILED(rc))
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ChangeLoadingMode is failed!" << endl;
	}

	//container
	CATIMmiPrtContainer *pIPrtContOnCAAUdfLoft = NULL;
	rc = spi3DShapeRepRefer->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pIPrtContOnCAAUdfLoft);
	if (FAILED(rc) || (NULL_var == pIPrtContOnCAAUdfLoft))
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - RetrieveApplicativeContainer is failed!" << endl;
		return E_FAIL;
	}
	opIPrtContOnCAAUdfLoft = pIPrtContOnCAAUdfLoft;
	opIPrtContOnCAAUdfLoft->AddRef();

	// 3-bis Lock the Representation Reference containing the reference to instantiate
	//CATOmbLifeCycleRootsBag Bag ;
	rc = iobag.InsertRoot(opiPLMCompOnFeatRef);
	if (FAILED(rc))
	{
		cout << "Error:OutRibUDFImportCmd::GetUDFContainerFromDB() - ibag.InsertRoot is failed!" << endl;
	}

	ULONG iL = pIPrtContOnCAAUdfLoft->Release();
	pIPrtContOnCAAUdfLoft = NULL;

	piNavEntity->Release();
	piNavEntity = NULL;

	return S_OK;
}


HRESULT CallEngineeringTemplate10Cmd::GetEngineeringTemp(CATIPLMNavReference_var &ospProdRef)
{
	HRESULT rc = S_OK;
	//判断项目中是否存在物料
	CATLISTV(CATString)        listAttrName;
	CATLISTV(CATUnicodeString) listAttrValue;
	listAttrName.Append("PLM_ExternalID");
	listAttrName.Append("revision");

	listAttrValue.Append(_strModelViewID);
	listAttrValue.Append(_strModelViewVersion);
	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	GetPLMObjectsFromAttrAndFromType(listAttrName, listAttrValue, "VPMReference", listQueryResult);
	if (listQueryResult.Size() > 0)
	{
		CATBoolean authoringMode = TRUE;
		CATIPLMNavReference* piProductRef = NULL;
		OpenPLMComponent("VPMReference", listAttrName, listAttrValue,
			IID_CATIPLMNavReference, (void**)&piProductRef, _ModelBag, authoringMode);
		if (NULL != piProductRef)
		{
			ospProdRef = piProductRef;
			piProductRef->Release(); piProductRef = NULL;
		}
	}
	if (NULL_var != ospProdRef)
		cout << "获取CATIPLMNavReference_var成功" << endl;
	else
		rc = E_FAIL;

	return rc;
}


void CallEngineeringTemplate10Cmd::OKAction()
{

	if (NULL_var == _spAxisFeature)
	{
		DisplayMessage("Warning", "请选择轴系!", "警告");
		return;
	}

	if (NULL_var == _spParentOcurr)
	{
		DisplayMessage("Warning", "获取父节点occurence对象失败!", "警告");
		return;
	}

	CATIPLMNavReference* piProdRef = NULL;
	_spParentOcurr->GetRelatedReference(piProdRef);
	if (NULL == piProdRef)
	{
		DisplayMessage("Error", "Get parent reference product failed!", "Error");
		return;
	}
	CATIPLMNavReference_var spProdRef = piProdRef;
	piProdRef->Release(); piProdRef = NULL;

	//1:打开EKL模板
	CATLISTV(CATString)        listAttrName;
	CATLISTV(CATUnicodeString) listAttrValue;
	listAttrName.Append("PLM_ExternalID");
	listAttrValue.Append(_strTemplateID);

	CATOmbLifeCycleRootsBag Bag;
	CATBoolean authoringMode = TRUE;
	CATIPLMNavReference* piProductRef = NULL;
	OpenPLMComponent("VPMReference", listAttrName, listAttrValue,
		IID_CATIPLMNavReference, (void**)&piProductRef, Bag, authoringMode);
	if (NULL == piProductRef)
	{
		DisplayMessage("Error", "打开EKL模板失败,请检查配置文件!", "ERROR");
		return;
	}

	cout << "打开EKL模板成功" << endl;

	//调用EKL action
	CATBaseUnknown_var spActionBUObj = NULL_var;
	GetKnowledgeAction(piProductRef, _strActionName, spActionBUObj);
	if (NULL_var == spActionBUObj)
	{
		DisplayMessage("Error", "获取EKL模板中的Action失败!", "ERROR");
		return;
	}

	CATICkeFunction_var spCkeActionFunc = spActionBUObj;
	if (NULL_var == spCkeActionFunc)
	{
		cout << "ERROR:PSTCUPSCmd::OKAction()-NULL_var == spCkeActionFunc" << endl;
		return;
	}

	CATICkeParmFactory_var spCkeParmFactory = CATCkeGlobalFunctions::GetVolatileFactory();
	if (NULL_var == spCkeParmFactory)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spCkeParmFactory" << endl;
		return;
	}

	CATLISTV(CATBaseUnknown_var) listCkeParamObj = NULL;
	CATICkeParm_var spParentRefCkeParam = spCkeParmFactory->CreateObjectReference(spProdRef);
	if (NULL_var == spParentRefCkeParam)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spParentRefCkeParam" << endl;
		return;
	}

	/////
	CATICkeParm_var spAxisCkeParam = spCkeParmFactory->CreateObjectReference(_spAxisFeature);
	if (NULL_var == spAxisCkeParam)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::OKAction()-NULL_var == spAxisCkeParam" << endl;
		return;
	}
	listCkeParamObj.Append(spParentRefCkeParam);
	listCkeParamObj.Append(spAxisCkeParam);

	CATIType_var hProductType = NULL_var;
	CATITypeDictionary_var hTypeDictionary = CATGlobalFunctions::GetTypeDictionary();
	if (NULL_var != hTypeDictionary)
	{
		CATUnicodeString TypeName = "VPMReference";
		hTypeDictionary->FindType(TypeName, hProductType);
	}

	CATICkeParm_var spResultParam = NULL_var;
	if (NULL_var != hProductType)
	{
		spResultParam = spCkeParmFactory->CreateObjectReference(hProductType, "VPMReference");
	}

	listCkeParamObj.Append(spResultParam);


	CATICkeParm_var spReturnedParm = NULL_var;
	spCkeActionFunc->Run(&listCkeParamObj, spReturnedParm, NULL);

	HRESULT rc = E_FAIL;
	spResultParam = listCkeParamObj[listCkeParamObj.Size()];
	if (NULL_var != spResultParam)
	{
		CATICkeInst_var spCkeInstance = spResultParam->Value();
		if (NULL_var != spCkeInstance)
		{
			CATBaseUnknown_var spResultObject = spCkeInstance->AsObject();
			if (NULL_var != spResultObject)
			{
				rc = ModifyPartParams(spResultObject);
				if (FAILED(rc))
				{
					cout << "ModifyPartParams failed " << endl;
				}
			}
		}
	}

	this->RequestDelayedDestruction();
	return;
}

HRESULT CallEngineeringTemplate10Cmd::ModifyPartParams(const CATIPLMNavReference_var &ispProdRef)
{
	if (NULL_var == ispProdRef) return E_FAIL;

	CATIPLMNavRepReference_var spPLMRepRef = NULL_var;
	CATIMmiMechanicalFeature_var spPartObject = NULL_var;
	HRESULT rc = CAAMmrGetPartFromProduct(ispProdRef, spPLMRepRef, spPartObject);
	if (FAILED(rc) || (NULL_var == spPartObject)) return E_FAIL;
	if (NULL_var == spPLMRepRef) return E_FAIL;
	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

	//获取container
	CATIMmiPrtContainer *pIPrtContOnPC(NULL);
	CATIPLMComponent *piPLMCompOnFeatRef(NULL);
	rc = GetUDFContainerFromDB(_ModelBag, ispProdRef, piPLMCompOnFeatRef, pIPrtContOnPC);
	if (FAILED(rc) || NULL == pIPrtContOnPC || NULL == piPLMCompOnFeatRef)
	{

		cout << "Error:OutRibUDFImportCmd::OutRibUDFImp() - GetUDFContainerFormDB is failed!" << endl;
		return E_FAIL;
	}

	CATIMmiMechanicalFeature_var spMechFeatOnPart;
	rc = pIPrtContOnPC->GetMechanicalPart(spMechFeatOnPart);
	CATIPartRequest_var spPartRequest = spMechFeatOnPart;
	if (NULL_var == spPartRequest)
	{
		cout << "未获取spPartRequest" << endl;
		return E_FAIL;
	}

	CATIPLMComponent_var spiPLMCompOnFeatRef(NULL_var);
	spiPLMCompOnFeatRef = piPLMCompOnFeatRef;
	piPLMCompOnFeatRef->Release();
	piPLMCompOnFeatRef = NULL;

	CATBaseUnknown_var spMainBody = NULL_var;
	rc = spPartRequest->GetMainBody("", spMainBody);

	CATIMmiUseBodyContent_var spBodyContent = spMainBody;
	CATListValCATBaseUnknown_var listFeat;
	if (NULL_var != spBodyContent)
		rc = spBodyContent->GetMechanicalFeatures(listFeat);

	if (0 == listFeat.Size())
		return E_FAIL;

	CATBaseUnknown_var spBUOnFeat{ listFeat[1] };
	cout << spBUOnFeat->GetImpl()->IsA() << endl;

	CATIUdfFeatureInstance_var spUdfObject = listFeat[1];
	if (NULL_var == spUdfObject)
	{
		cout << "NULL_var == spUdfObject" << endl;
		return E_FAIL;
	}

	CATListValCATBaseUnknown_var * pListParam = NULL;
	rc = spUdfObject->GetParameters(pListParam);

	if (SUCCEEDED(rc) && (NULL != pListParam))
	{
		for (int i = 1; i <= pListParam->Size(); i++)
		{
			CATICkeParm_var spCkeParm = (*pListParam)[i];

			CATUnicodeString strParamName = spCkeParm->Name();
			strParamName = GetRightParamName(strParamName);
			cout << "ParamName: " << strParamName << endl;

			if (CATUnicodeString("D1") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerD1->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("D1", iValue));
			}
			else if (CATUnicodeString("D2") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerD2->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("D2", iValue));
			}
			else if (CATUnicodeString("D3") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerD3->GetValue();
				spCkeParm->Valuate(iValue);

			}
			else if (CATUnicodeString("T1") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerT1->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("T1", iValue));
				cout << "T1值为：" << fixed << setprecision(10) << iValue << endl;
			}
			else if (CATUnicodeString("T3") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerT3->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("T3", iValue));
				cout << "T3值为：" << fixed << setprecision(10) << iValue << endl;
			}
			else if (CATUnicodeString("H") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerH->GetValue();
				spCkeParm->Valuate(iValue);
				//_params.insert(make_pair("H", iValue));
				cout << "H值为：" << fixed << setprecision(10) << iValue << endl;
			}
			else if (CATUnicodeString("A") == strParamName)
			{
				double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerA->GetValue();
				spCkeParm->Valuate(iValue*3.1415926f / 180.0f);
			}
		}
	}

	//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	CATIParmPublisher_var spParamPublisher = spPLMRepRef;
	if (NULL_var == spParamPublisher)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::GetPartParams()-NULL_var == spParamPublisher" << endl;
		return E_FAIL;
	}

	CATIKweModelServices_var spKweModelServices = CATCkeGlobalFunctions::GetModelServices();
	if (NULL_var == spKweModelServices)
	{
		cout << "ERROR:CallEngineeringTemplateCmd::GetPartParams()-NULL_var == spKweModelServices" << endl;
		return E_FAIL;
	}

	CATBaseUnknown_var spParamSetObj = NULL_var;
	spParamSetObj = spKweModelServices->GetCurrentSet(CATIKweModelServices::Parameter, spParamPublisher);
	if (NULL_var == spParamSetObj) return E_FAIL;

	CATIParmPublisher_var spFristParmPublisher = spParamSetObj;
	CATLISTV(CATBaseUnknown_var) listParamObj = NULL;
	spKweModelServices->VisibleParms(spFristParmPublisher, listParamObj, 0);
	for (int i = 1; i <= listParamObj.Size(); i++)
	{
		CATICkeParm_var spCkeParam = listParamObj[i];
		CATUnicodeString strParamName = spCkeParam->Name();
		
		//cout << "spCkeParam == " << spCkeParam->Content() << endl;

		strParamName = GetRightParamName(strParamName);
		cout << "strParamName == " << strParamName << endl;
		//cout << "spCkeParam == " << spCkeParam->Content() << endl;

		if (CATUnicodeString("X") == strParamName)
		{
			double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerX->GetValue();
			spCkeParam->Valuate(iValue);
		}
		else if (CATUnicodeString("T2") == strParamName)
		{
			double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerT2->GetValue();
			spCkeParam->Valuate(iValue);
		}
		else if (CATUnicodeString("R") == strParamName)
		{
			double iValue = _pCallEngineeringTemplate10Dlg->_SpinnerR->GetValue();
			spCkeParam->Valuate(iValue);
		}
		
	}

	CAAUpdateObject(spPartObject);
	return S_OK;
}

CATUnicodeString CallEngineeringTemplate10Cmd::GetRightParamName(const CATUnicodeString &istrfullParamName)
{
	int iLength = istrfullParamName.GetLengthInChar();
	if (0 == iLength) return "";

	int iStartPos = 0;
	for (int i = iLength - 1; i >= 0; i--)
	{
		CATUnicodeChar iCurrentChar = istrfullParamName[i];
		if (iCurrentChar == CATUnicodeChar('\\'))
		{
			iStartPos = i + 1;
			break;
		}
	}

	CATUnicodeString strValue("");
	strValue = istrfullParamName.SubString(iStartPos, iLength - iStartPos);
	return strValue;
}

HRESULT CallEngineeringTemplate10Cmd::CAAMmrGetPartFromProduct(const CATIPLMNavReference_var &ispPLMNavRef,
	CATIPLMNavRepReference_var &ospPLMRepRef,
	CATIMmiMechanicalFeature_var &ospPartFeature)

{
	HRESULT rc = E_FAIL;

	if (NULL_var == ispPLMNavRef) return E_FAIL;
	// Retrieve the first inst rep ref
	CATIPLMNavRepInstance * pNavRepInst = NULL;

	CATListPtrCATIPLMNavEntity ListNavEntity = NULL;
	CATPLMCoreType TypeRepInstance = PLMCoreRepInstance;
	ispPLMNavRef->ListChildren(ListNavEntity, 1, &TypeRepInstance);

	if (ListNavEntity.Size() >= 1)
	{
		CATIPLMNavEntity *pCurrent = ListNavEntity[1];
		rc = pCurrent->QueryInterface(IID_CATIPLMNavRepInstance, (void**)& pNavRepInst);
	}

	// Retrieve the reference of the first inst rep ref
	CATIPLMNavRepReference *pNavRepRef = NULL;
	if (NULL != pNavRepInst)
	{
		rc = pNavRepInst->GetRepReferenceInstanceOf(pNavRepRef);
		pNavRepInst->Release(); pNavRepInst = NULL;
	}

	// change the loading mode
	if (NULL != pNavRepRef)
	{
		CATIPsiRepresentationLoadMode *piRepLoadMode = NULL;
		rc = pNavRepRef->QueryInterface(IID_CATIPsiRepresentationLoadMode, (void **)&piRepLoadMode);
		if (SUCCEEDED(rc) && NULL != piRepLoadMode)
		{
			rc = piRepLoadMode->ChangeLoadingMode(CATIPsiRepresentationLoadMode::EditMode);
			piRepLoadMode->Release();
			piRepLoadMode = NULL;
		}
	}

	//Retrieve the applicative container
	CATIMmiPrtContainer * pContainer = NULL;
	if (SUCCEEDED(rc) && (NULL != pNavRepRef))
	{
		ospPLMRepRef = pNavRepRef;
		rc = pNavRepRef->RetrieveApplicativeContainer("CATPrtCont", IID_CATIMmiPrtContainer, (void **)&pContainer);
		pNavRepRef->Release();
		pNavRepRef = NULL;
	}

	if (SUCCEEDED(rc) && (NULL != pContainer))
	{
		pContainer->GetMechanicalPart(ospPartFeature);
		pContainer->Release();
		pContainer = NULL;
	}
	return rc;
}

HRESULT CallEngineeringTemplate10Cmd::GetParamSetByName(const CATICkeParameterSet_var &ispParentSet,
	const CATUnicodeString &istrParmSetName,
	CATICkeParameterSet_var &ospParamSet)
{
	if (NULL_var == ispParentSet) return E_FAIL;

	CATIAParameterSet* piCATIAParamSet = NULL;
	HRESULT rc = ispParentSet->QueryInterface(IID_CATIAParameterSet, (void**)&piCATIAParamSet);
	if (FAILED(rc) && (NULL != piCATIAParamSet)) return E_FAIL;

	CATIAParameterSets* piParamsSets = NULL;
	piCATIAParamSet->get_ParameterSets(piParamsSets);
	if (NULL == piParamsSets) return E_FAIL;

	piCATIAParamSet->Release(); piCATIAParamSet = NULL;

	CATBoolean IsFind = FALSE;
	CATLong iCount = 0;
	piParamsSets->get_Count(iCount);
	for (long i = 1; i <= iCount; i++)
	{
		//Item
		CATVariant IndexVar;
		::BuildVariant(i, IndexVar);
		CATIAParameterSet* piCurrentParmSet = NULL;
		piParamsSets->Item(IndexVar, piCurrentParmSet);
		if (NULL != piCurrentParmSet)
		{
			CATBSTR bstrSetName;
			piCurrentParmSet->get_Name(bstrSetName);
			CATUnicodeString strSetName("");
			strSetName.BuildFromBSTR(bstrSetName);

			if (strSetName == istrParmSetName)
			{
				ospParamSet = piCurrentParmSet;
				IsFind = TRUE;
				break;
			}
			else
			{
				CATICkeParameterSet_var spCurrentParamSet = piCurrentParmSet;
				GetParamSetByName(spCurrentParamSet, istrParmSetName, ospParamSet);
			}

		}
	}
	piParamsSets->Release(); piParamsSets = NULL;

	return S_OK;
}

HRESULT CallEngineeringTemplate10Cmd::CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU)
{
	if (NULL_var == spUpdateObjectBU)
	{
		cout << "ERROR:CAAUpdateObject() - spUpdateObjectBU is NULL!" << endl;
		return E_FAIL;
	}

	CATIUseEntity *piUseEntity = NULL;
	HRESULT rc = spUpdateObjectBU->QueryInterface(IID_CATIUseEntity, (void**)&piUseEntity);
	if (SUCCEEDED(rc))
	{
		rc = DataCommonProtocolServices::Update(piUseEntity);
		if (FAILED(rc))
		{
			CATError * pError = CATError::CATGetLastError(rc);
			if (NULL != pError)
			{
				cerr << "Error message is " << pError->GetNLSMessage() << endl;
				pError->Release();
				pError = NULL;
			}
		}
		piUseEntity->Release();
		piUseEntity = NULL;
	}

	return rc;
}


HRESULT CallEngineeringTemplate10Cmd::GetKnowledgeAction(const CATIPLMNavReference_var &ispParentNavRef,
	const CATUnicodeString &istrActionName,
	CATBaseUnknown_var &ospActionBUObj)
{
	if (NULL_var == ispParentNavRef) return E_FAIL;

	CATIPLMNavRepReference_var spKnowledgeRepRef = NULL_var;

	CATPLMCoreType  FilterPLMType = PLMCoreRepInstance;
	CATLISTP(CATIPLMNavEntity)  listRepInsChild = NULL;
	ispParentNavRef->ListChildren(listRepInsChild, 1, &FilterPLMType);
	for (int i = 1; i <= listRepInsChild.Size(); i++)
	{
		CATIPLMNavRepInstance_var spRepInstance = listRepInsChild[i];
		if (NULL_var == spRepInstance) continue;

		CATIPLMNavRepReference* piRepReference = NULL;
		spRepInstance->GetRepReferenceInstanceOf(piRepReference);
		if (NULL != piRepReference)
		{
			CATIPLMComponent_var spPLMComponent = piRepReference;

			CATUnicodeString strPLMType("");
			RetrieveComponentType(spPLMComponent, strPLMType);
			if (CATUnicodeString("Knowledgeware") == strPLMType)
			{
				spKnowledgeRepRef = piRepReference;
			}
			piRepReference->Release(); piRepReference = NULL;
		}

		if (NULL_var != spKnowledgeRepRef) break;
	}

	if (NULL_var == spKnowledgeRepRef) return E_FAIL;

	CATIKweModelServices_var spKweModelServices = CATCkeGlobalFunctions::GetModelServices();
	if (NULL_var == spKweModelServices) return E_FAIL;

	HRESULT rc = E_FAIL;
	CATIParmPublisher_var spParmPublisher = spKnowledgeRepRef;
	if (NULL_var != spParmPublisher)
	{
		CATLISTV(CATBaseUnknown_var) listCkeFuncObjs = NULL;
		spKweModelServices->VisibleRelations(spParmPublisher, listCkeFuncObjs, 1);
		for (int i = 1; i <= listCkeFuncObjs.Size(); i++)
		{
			CATBaseUnknown_var spActionBUObj = listCkeFuncObjs[i];
			CATIAlias_var spAliasName = spActionBUObj;
			CATUnicodeString strAliasName = spAliasName->GetAlias();
			if (istrActionName == strAliasName)
			{
				rc = S_OK;
				ospActionBUObj = spActionBUObj;
				break;
			}
		}
	}

	return rc;
}
HRESULT CallEngineeringTemplate10Cmd::RetrieveComponentType(const CATBaseUnknown_var &ispPLMObject,
	CATUnicodeString &ostrType)
{
	if (NULL_var == ispPLMObject)
	{
		cout << "ERROR:RetrieveComponentType()-NULL_var == ispPLMObject" << endl;
		return E_FAIL;
	}

	CATIPLMComponent_var spPLMComponent = ispPLMObject;
	if (NULL_var == spPLMComponent)
	{
		cout << "ERROR:RetrieveComponentType()-NULL_var == spPLMComponent" << endl;
		return E_FAIL;
	}
	//Type
	CATIAdpType *piAdpType = NULL;
	HRESULT rc = spPLMComponent->GetAdpType(piAdpType);
	if (FAILED(rc) || NULL == piAdpType)
	{
		cout << "ERROR:RetrieveComponentType()-NULL == piAdpType" << endl;
		return E_FAIL;
	}
	CATUnicodeString strProductTypeValue("");
	CATIType *piCkeType = NULL;
	rc = CATPLMTypeServices::GetKweTypeFromAdpType(piAdpType, piCkeType);
	if (SUCCEEDED(rc))
	{
		CATUnicodeString CurrentCustoName = piCkeType->Name();
		cout << "Current Type Name is :" << CurrentCustoName.ConvertToChar() << endl;

		CATUnicodeString CurrentUserName = piCkeType->UserName();
		cout << "Current User Name is :" << CurrentUserName.ConvertToChar() << endl;
		ostrType = CurrentCustoName;

		piAdpType->Release();
		piAdpType = NULL;

		piCkeType->Release();
		piCkeType = NULL;
	}

	return rc;
}

HRESULT CallEngineeringTemplate10Cmd::OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATListOfCATString &listAttrName,
	const CATLISTV(CATUnicodeString) &ListAttrValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll)
{
	HRESULT hr = S_OK;
	if (CATUnicodeString("") == istrPLMType) return E_FAIL;
	if (0 == listAttrName.Size()) return E_FAIL;
	if (0 == ListAttrValue.Size()) return E_FAIL;

	int iListSize = listAttrName.Size();

	CATListPtrCATAdpQueryResult listQueryResult = NULL;
	hr = GetPLMObjectsFromAttrAndFromType(listAttrName, ListAttrValue, istrPLMType, listQueryResult);
	if (FAILED(hr) || (0 == listQueryResult.Size()))
	{

		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-0 == listQueryResult.Size()" << endl;
		return hr;
	}

	CATIAdpPLMIdentificator* piAdpPLMIdentificator = NULL;
	listQueryResult[1]->GetIdentifier(piAdpPLMIdentificator);
	if (NULL == piAdpPLMIdentificator)
	{
		cout << "ERROR:ClsPLMUtilities::OpenPLMComponent()-NULL == piAdpPLMIdentificator" << endl;
		return E_FAIL;
	}

	if (TRUE == iExpandAll)
	{
		CATAdpOpenParameters params_Auth(CATAdpExpandParameters::Authoring);
		CATAdpOpener opener_Auth(iBag, params_Auth);
		// 5.2. Open the Retrieved Component by using CATAdpOpener
		hr = opener_Auth.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	else
	{
		CATAdpOpenParameters params_Nav(CATAdpExpandParameters::OneLevelRepresentations);
		CATAdpOpener opener_Nav(iBag, params_Nav);
		hr = opener_Nav.CompleteAndOpen(piAdpPLMIdentificator, iIID, opiPLMComp);
	}
	piAdpPLMIdentificator->Release();
	piAdpPLMIdentificator = NULL;

	return S_OK;
}

HRESULT CallEngineeringTemplate10Cmd::GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	const CATListOfCATUnicodeString &listOfValues,
	const CATUnicodeString &iStrPLMType,
	CATListPtrCATAdpQueryResult & opQueryResults)
{
	HRESULT hr = S_OK;
	//cout << "   GetPLMObjectsFromAttrAndFromType " << endl;

	if ((0 == listOfAttribute.Size()) || (0 == listOfValues.Size())) return E_INVALIDARG;
	if (listOfAttribute.Size() != listOfValues.Size()) return E_INVALIDARG;
	if (0 < opQueryResults.Size())return E_INVALIDARG;


	int iListSize = listOfAttribute.Size();

	CATAdpAttributeSet iAttributeSet;
	//cout << "   Build an Attribute set with inputs from user, for query into db" << endl;
	int i = 1;
	while ((i <= iListSize) && (SUCCEEDED(hr)))
	{
		CATUnicodeString Name = listOfAttribute[i].CastToCharPtr();
		const CATString AttributeINPUT = CATCkePLMNavPublicServices::RetrieveBasicAttributeNameFromPreviousOne(NULL_var, Name).CastToCharPtr();
		CATUnicodeString AttrValue = listOfValues[i];

		hr = iAttributeSet.AddAttribute(AttributeINPUT, AttrValue);
		i++;
	}

	CATIType_var spTypeObj = NULL_var;
	hr = RetrievePLMType(iStrPLMType, spTypeObj);
	if (FAILED(hr) || (NULL_var == spTypeObj))
	{
		cout << "ERROR:ClsPLMUtilities::GetPLMObjectsFromAttrAndFromType()-NULL_var == spTypeObj" << endl;
		return E_FAIL;
	}


	hr = CATAdpPLMQueryServices::GetElementsFromAttributes(spTypeObj,
		iAttributeSet,
		opQueryResults);

	return hr;
}

HRESULT CallEngineeringTemplate10Cmd::RetrievePLMType(const CATUnicodeString & isPLMType,
	CATIType_var & ospType)
{
	HRESULT rc = E_INVALIDARG;
	if (isPLMType != "")
	{
		// For DS type
		rc = CATCkePLMNavPublicServices::RetrieveKnowledgeType(isPLMType, ospType);
		// For Specialization Type
		if (FAILED(rc))  rc = CATCkePLMNavSpecializationAccessPublicServices::RetrieveSpecializationType(isPLMType, ospType);
	}
	return rc;
}

void CallEngineeringTemplate10Cmd::ExitCmd()
{
	this->RequestDelayedDestruction();
	return;
}

void CallEngineeringTemplate10Cmd::PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName)
{

	oPathName = "";
	if (NULL != ipPath)
	{
		int sizeOfThePath = ipPath->GetSize();

		for (int i = sizeOfThePath - 1; i >= 0; i--)
		{
			CATBaseUnknown * pElt = (*ipPath)[i];
			if (NULL != pElt)
			{
				CATIAlias * pIAliasOnElt = NULL;
				HRESULT rc = pElt->QueryInterface(IID_CATIAlias, (void**)&pIAliasOnElt);
				if (SUCCEEDED(rc))
				{
					CATUnicodeString Name = pIAliasOnElt->GetAlias();
					oPathName.Append(Name);

					if (i > 0)
					{
						oPathName.Append("/"); ;
					}

					pIAliasOnElt->Release();
					pIAliasOnElt = NULL;
				}
			}
		}
	}
}
