//===================================================================
// COPYRIGHT atoz 2020/12/28
//===================================================================
// ClsEKLUtilities.cpp
// Header definition of class ClsEKLUtilities
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/12/28 Creation: Code generated by the 3DS wizard
//===================================================================

#include "ClsEKLUtilities.h"

//-----------------------------------------------------------------------------
// ClsEKLUtilities : constructor
//-----------------------------------------------------------------------------
ClsEKLUtilities::ClsEKLUtilities()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// ClsEKLUtilities : destructor
//-----------------------------------------------------------------------------

ClsEKLUtilities::~ClsEKLUtilities()
{
//
// TODO: Place code here.
//
}

HRESULT ClsEKLUtilities::GetKnowledgeAction(const CATIPLMNavReference_var &ispParentNavRef,
	const CATUnicodeString &istrActionName,
	CATBaseUnknown_var &ospActionBUObj)
{
	if (NULL_var == ispParentNavRef) return E_FAIL;

	CATIPLMNavRepReference_var spKnowledgeRepRef = NULL_var;

	CATPLMCoreType  FilterPLMType = PLMCoreRepInstance;
	CATLISTP(CATIPLMNavEntity)  listRepInsChild = NULL;
	ispParentNavRef->ListChildren(listRepInsChild, 1, &FilterPLMType);
	for (int i = 1; i <= listRepInsChild.Size(); i++)
	{
		CATIPLMNavRepInstance_var spRepInstance = listRepInsChild[i];
		if (NULL_var == spRepInstance) continue;

		CATIPLMNavRepReference* piRepReference = NULL;
		spRepInstance->GetRepReferenceInstanceOf(piRepReference);
		if (NULL != piRepReference)
		{
			CATIPLMComponent_var spPLMComponent = piRepReference;

			CATUnicodeString strPLMType("");
			RetrieveComponentType(spPLMComponent, strPLMType);
			if (CATUnicodeString("Knowledgeware") == strPLMType)
			{
				spKnowledgeRepRef = piRepReference;
			}
			piRepReference->Release(); piRepReference = NULL;
		}

		if (NULL_var != spKnowledgeRepRef) break;
	}

	if (NULL_var == spKnowledgeRepRef) return E_FAIL;

	CATIKweModelServices_var spKweModelServices = CATCkeGlobalFunctions::GetModelServices();
	if (NULL_var == spKweModelServices) return E_FAIL;

	HRESULT rc = E_FAIL;
	CATIParmPublisher_var spParmPublisher = spKnowledgeRepRef;
	if (NULL_var != spParmPublisher)
	{
		CATLISTV(CATBaseUnknown_var) listCkeFuncObjs = NULL;
		spKweModelServices->VisibleRelations(spParmPublisher, listCkeFuncObjs, 1);
		for (int i = 1; i <= listCkeFuncObjs.Size(); i++)
		{
			CATBaseUnknown_var spActionBUObj = listCkeFuncObjs[i];
			CATIAlias_var spAliasName = spActionBUObj;
			CATUnicodeString strAliasName = spAliasName->GetAlias();
			if (istrActionName == strAliasName)
			{
				rc = S_OK;
				ospActionBUObj = spActionBUObj;
				break;
			}
		}
	}

	return rc;
}

HRESULT ClsEKLUtilities::RetrieveComponentType(const CATBaseUnknown_var &ispPLMObject,
	CATUnicodeString &ostrType)
{
	if (NULL_var == ispPLMObject)
	{
		cout << "ERROR:RetrieveComponentType()-NULL_var == ispPLMObject" << endl;
		return E_FAIL;
	}

	CATIPLMComponent_var spPLMComponent = ispPLMObject;
	if (NULL_var == spPLMComponent)
	{
		cout << "ERROR:RetrieveComponentType()-NULL_var == spPLMComponent" << endl;
		return E_FAIL;
	}
	//Type
	CATIAdpType *piAdpType = NULL;
	HRESULT rc = spPLMComponent->GetAdpType(piAdpType);
	if (FAILED(rc) || NULL == piAdpType)
	{
		cout << "ERROR:RetrieveComponentType()-NULL == piAdpType" << endl;
		return E_FAIL;
	}
	CATUnicodeString strProductTypeValue("");
	CATIType *piCkeType = NULL;
	rc = CATPLMTypeServices::GetKweTypeFromAdpType(piAdpType, piCkeType);
	if (SUCCEEDED(rc))
	{
		CATUnicodeString CurrentCustoName = piCkeType->Name();
		//cout << "Current Type Name is :" << CurrentCustoName.ConvertToChar() << endl;

		//CATUnicodeString CurrentUserName = piCkeType->UserName();
		//cout << "Current User Name is :" << CurrentUserName.ConvertToChar() << endl;
		ostrType = CurrentCustoName;

		piAdpType->Release();
		piAdpType = NULL;

		piCkeType->Release();
		piCkeType = NULL;
	}

	return rc;
}

//传入输入
HRESULT ClsEKLUtilities::CallEKLfunction(CATIPLMNavReference_var ispProdRef,
										CATICkeFunction_var ispCkeActionFunc,
										CATLISTV(CATBaseUnknown_var) &iParamObjs, //输入参数
	                                    CATBaseUnknown_var& ospResultObject)
{
	HRESULT rc = S_OK;
	if (NULL_var == ispCkeActionFunc)
	{
		cout << "NULL_var == spCkeActionFunc" << endl;
		return E_FAIL;
	}

	CATICkeParmFactory_var spCkeParmFactory = CATCkeGlobalFunctions::GetVolatileFactory();
	if (NULL_var == spCkeParmFactory)
	{
		cout << "ERROR:CallEKLfunction-NULL_var == spCkeParmFactory" << endl;
		return E_FAIL;
	}


	CATICkeParm_var spParentRefCkeParam = spCkeParmFactory->CreateObjectReference(ispProdRef);
	if (NULL_var == spParentRefCkeParam)
	{
		cout << "ERROR:CallEKLfunction-NULL_var == spParentRefCkeParam" << endl;
		return E_FAIL;
	}

	CATLISTV(CATBaseUnknown_var) listCkeParamObj;
	listCkeParamObj.Append(spParentRefCkeParam);

	const int SIZE = iParamObjs.Size();
	CATBaseUnknown_var spCurParam(NULL_var);
	for (int i = 1; i <= SIZE; i++)
	{
		spCurParam = iParamObjs[i];
		CATICkeParm_var spCkeParam = spCkeParmFactory->CreateObjectReference(spCurParam);
		if (NULL_var == spCkeParam)
		{
			CATIAlias_var spAliasOnParam = spCurParam;
			cout << "ERROR:NULL_var == " << spAliasOnParam->GetAlias() << endl;
			return E_FAIL;
		}
		listCkeParamObj.Append(spCkeParam);
	}

	CATIType_var hProductType = NULL_var;
	CATITypeDictionary_var hTypeDictionary = CATGlobalFunctions::GetTypeDictionary();
	if (NULL_var != hTypeDictionary)
	{
		CATUnicodeString TypeName = "VPMReference";
		hTypeDictionary->FindType(TypeName, hProductType);
	}

	CATICkeParm_var spResultParam = NULL_var;
	if (NULL_var != hProductType)
	{
		spResultParam = spCkeParmFactory->CreateObjectReference(hProductType, "VPMReference");
	}


	listCkeParamObj.Append(spResultParam);


	CATICkeParm_var spReturnedParm = NULL_var;
	ispCkeActionFunc->Run(&listCkeParamObj, spReturnedParm, NULL);

	spResultParam = listCkeParamObj[SIZE];
	if (NULL_var != spResultParam)
	{
		CATICkeInst_var spCkeInstance = spResultParam->Value();
		if (NULL_var != spCkeInstance)
		{
			CATBaseUnknown_var spResultObject = spCkeInstance->AsObject();
			if (NULL_var == spResultObject)
				return E_FAIL;
		}
	}

	return rc;
	

}

