//===================================================================
// COPYRIGHT atoz 2021/03/18
//===================================================================
// ATOZAddFakeValueCmd.cpp
// Header definition of class ATOZAddFakeValueCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/03/18 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef ATOZAddFakeValueCmd_H
#define ATOZAddFakeValueCmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "ATOZAddFakeValueDlg.h"
#include "CATIDftDrawing.h"
#include "CATPathElementAgent.h"
//system includes
#include "CATUnicodeString.h"
#include "CATCommand.h"
#include "CATBaseUnknown.h"   
#include "CATGetEnvValue.h"
#include "CATLib.h"   
#include "CATListOfCATUnicodeString.h"
#include "CATError.h" 
#include "CATListOfDouble.h"
#include "CATString.h"
#include "CATAutoConversions.h"
#include "CATUnicodeChar.h"
#include "CATIDftView.h"

//AfrFoundation includes
#include "CATApplicationFrame.h"
#include "CATFrmEditor.h"
#include "CATFrmLayout.h"
#include "CATFrmWindow.h"
//Dialog includes
#include "CATDlgNotify.h"

//AfrNavigator includes
#include "CATFrmNavigGraphicWindow.h"
#include "CATNavigBox.h"

//CATIAApplicationFrame includes
#include "CATCafCenterGraph.h"
//CATPLMComponentInterfaces includes
#include "CATIPLMNavReference.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavRepInstance.h"
#include "CATPLMComponentInterfacesServices.h"
#include "CATListPtrCATIPLMNavOccurrence.h"

//CATPLMIdentificationAccess includes
#include "CATIPLMComponent.h"
#include "CATIAdpType.h"
#include "CATPLMTypeServices.h"
#include "CATListPtrCATIPLMComponent.h"
#include "CATAdpAttributeSet.h"
#include "CATPLMCoreType.h"

//CAT3DPhysicalRepInterfaces includes
#include "CATIPsiRepresentationLoadMode.h"

//CATMecModLiveUseItf includes
#include "CATIMmiPrtContainer.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATIPartRequest.h"
#include "CATIBodyRequest.h"

//CATMecModUseItf inlcudes
#include "CATIMmiUseSetFactory.h"
#include "CATIMmiUseMfBRep.h"
#include "CATIMmiUseGeometricalElement.h"

//DataCommonProtocolUse includes
#include "DataCommonProtocolServices.h"
#include "CATIUseEntity.h"

//VisualizationInterfaces includes
#include "CATPathElement.h"
#include "CATIBuildPath.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATIVisProperties.h"
#include "CATVisPropertiesValues.h"
#include "CATModifyVisProperties.h"
#include "CATI3DGeoVisu.h"
#include "CATNavigation3DViewer.h"
#include "CATViewpoint.h"
#include "CAT3DViewpoint.h"

//VisualizationController includes
#include "CATViewer.h"
#include "CAT3DViewer.h"
//VisualizationFoundation includes
#include "CAT3DManipulator.h"
//ObjectModelerNavigator includes
#include "CATIRedrawEvent.h"

//SGInfra includes
#include "CAT3DViewpoint.h"
#include "CAT3DBoundingSphere.h"
#include "CAT3DViewpoint.h"
#include "CATSupport.h"
#include "CAT3DBagRep.h"
#include "CAT4x4Matrix.h"
#include "CAT3DFixedArrowGP.h"
#include "CAT3DCustomRep.h"
#include "CAT3DPlanRep.h"

//VisualizationCore includes
#include "CATGraphicAttributeSet.h"

//Mathematics includes
#include "CATMathPointf.h"
#include "CATMathDirectionf.h"
#include "CATMathBox.h"
#include "CATMathPlane.h"
#include "CATMathVector.h"
#include "CATMath3x3Matrix.h"
#include "CAT4x4Matrix.h"
#include "CATLISTV_CATMathPlane.h"

//CATMathStream includes
#include "CATSoftwareConfiguration.h"

//SGManager includes
#include "CATHSO.h"
#include "CATVisManager.h"

//ObjectModelerSystem includes
#include "CATIAlias.h"

//KnowledgeInterfaces includes
#include "CATICkeObject.h"
#include "CATIType.h"
#include "CATAttributeInfos.h"
#include "CATListValCATAttributeInfos.h"
#include "CATICkeParm.h"
#include "CATICkeParmFactory.h"
#include "CATListValCATICkeParm.h"
#include "CATCkeObjectAttrWriteServices.h"
#include "CATCkeObjectAttrReadServices.h"
#include "CATIParmPublisher.h"
#include "CATIKweModelServices.h"
#include "CATCkeGlobalFunctions.h"
#include "CATICkeParameterSet.h"
#include "CATParmPublisherAdapter.h"
#include "CATICkeFunction.h"
#include "CATITypeDictionary.h"
#include "CATICkeInst.h"

//KnowledgeIDLItf includes
#include "CATIAParameterSet.h"
#include "CATIAParameterSets.h"

//GMModelInterfaces includes
#include "CATBody.h"

//GeometricObjects includes
#include "CATGeoFactory.h"
#include "CATPlane.h"

//GMOperatorsInterfaces includes
#include "CATICGMTopSkin.h"
#include "CATCGMCreateTopIntersect.h"
#include "CATICGMHybIntersect.h"
#include "CATICGMHybSplit.h"
#include "CATCGMCreateTopSplit.h"

//CATMecModLiveUseItf includes
#include "CATIMmiMechanicalFeature.h"
#include "CATIMmiUsePrtPart.h"
#include "CATMmiUseServicesFactory.h"
#include "CATIMmiUseCreateImport.h"
#include "CATIPartRequest.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"

//CATMecModUseItf includes
#include "CATIMmiUseDatumFactory.h"
#include "CATIMmiUseSolidInsertion.h"
#include "CATIMmiUseBasicInsertion.h"

//CATPartUseItf includes
#include "CATIPdgUsePrtFactory.h"

//MeasureGeometryInterfaces includes
#include "CATIMeasurablePlane.h"

//PLMModelerBaseInterfaces includes
#include "CATIMovable.h"

//CATGSMUseItf includes
#include "CATIGSMUseFactory.h"
#include "CATIGSMUsePlaneOffset.h"

//ProductStructureInterfaces includes
#include "CATIPLMProducts.h"
#include "CATPrdGetOccurrenceMngt.h"
#include "CATIPrdOccurrenceMngt.h"

//-----------------------------------------------------------------------
// CATPLMIntegrationAccess Framework
#include "CATIAdpEnvironment.h"
#include "CATAdpDictionaryServices.h"
#include "CATAdpAttributeSet.h"
#include "CATAdpQueryServices.h"
#include "CATAdpQueryResult.h"
#include "CATAdpIdentificationSet.h"
#include "CATLISTP_CATAdpQueryResult.h"
#include "CATIAdpPLMIdentificator.h"

// CATPLMIntegrationUse Framework
#include "CATAdpPLMQueryFilter.h"
#include "CATAdpPLMComponentsInfos.h"
#include "CATAdpPLMComponentsInfosIter.h"
#include "CATAdpPLMExtendedQueryServices.h"
#include "CATAdpPLMQueryAttributeSet.h"
#include "CATAdpPLMComponentInfos.h"
#include "CATAdpPLMComponentUniqueKey.h"
#include "CATAdpPLMQueryServices.h"
#include "CATAdpOpenParameters.h"
#include "CATAdpOpener.h"


//ProductStructureUseItf includes
#include "CATPrdFactory.h"
#include "CATIPrdReferenceFactory.h"
#include "CATIPrd3DPartReferenceFactory.h"


//PLMDictionaryNavServices Framework
#include "CATCkePLMNavPublicServices.h"
#include "CATCkePLMNavCustoAccessPublicServices.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATCkePLMNavSpecializationAccessPublicServices.h"

// System
#include "CATString.h"
#include "CATListOfCATString.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"
#include "CATSysBoolean.h"
#include "CATBaseUnknown.h"
#include "CATLISTP_CATBaseUnknown.h"

//ObjectModelerBase includes
#include "CATOmbLifeCycleRootsBag.h"
#include "CATIDrwDimDimension.h"
#include "CATIDrwDimFakeComponent.h"
#include "CATIDrwDimValue.h"
#include "CATIPsiRepresentationReference.h"
#include "CATIDftSheet.h"
#include "CATIUnknownList.h"
#include "CATISktUseSketch.h"
#include <iostream>
using namespace std;

#include "CATISktUse2DWFFactory.h"
#include "CATDlgUtility.h"
#include "CATIStrUseSketchBasedDMSMngt.h"
#include "CATIMmiUsePrtPart.h"
#include "CATMmiUseServicesFactory.h"
#include "CATISktUse2DWFGeometry.h"
#include "CATIMfPoint.h"
#include "CATIMfZeroDimResult.h"
#include "CATIMfMonoDimResult.h"
#include "CATIGSMUsePointCoord.h"
#include "CATPoint.h"
#include "CATCGMAttribute.h"
#include "CATICGMUnknown.h"
#include "CATISktUse2DProperties.h"
#include <vector>
#include <utility>
#include "DataCommonProtocolServices.h"
#include "CATIDftCoordDimension.h"
#include <math.h>
#include<iomanip>
#include<map>
#include "CATIPLMNavRepReference.h"
#include "CATISktUseSketchFactory.h"
#include "CATISktUse2DLine.h"
#include "CATIUdfInstantiate.h"
#include "CATISktUse2DCurve.h"
#include "CATISktUse2DConstraintFactory.h"
#include "CATIDrwTextProperties.h"

class CATIndicationAgent;

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class ATOZAddFakeValueCmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( ATOZAddFakeValueCmd, CATStateCommand )

public:

ATOZAddFakeValueCmd();
virtual ~ATOZAddFakeValueCmd();
HRESULT InitializeMainDialog();


/**
* Defines the command automata.
* <br>
* <i>(states, transitions and agents)</i>
*/
virtual void     BuildGraph();
void ExitCmd();
void OKAction();
HRESULT GetRootDrawing(CATIDftDrawing_var &ospDrawing);
HRESULT CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU);
HRESULT RetrieveCurrentDftSheet(CATIDftSheet_var &ospDftSheet);
HRESULT GetCurrentDrawing(CATIDftDrawing * &piDftDrawing);
HRESULT GetAllDims();
HRESULT RetrieveOtherViews(const CATIDftSheet_var &spDftSheet,
	CATLISTV(CATBaseUnknown_var) &olistOtherViews);
HRESULT GetViewAllDimElems(const CATIDftView_var &ispDftView,
	CATLISTV(CATBaseUnknown_var) &olistDimElems);
HRESULT ManageAllDims(CATLISTV(CATBaseUnknown_var) &ilistDimElems);
HRESULT GetAllSheets(const CATIDftDrawing_var &ispDftDrawing,
	CATLISTV(CATBaseUnknown_var) &olistSheets);



private:
	ATOZAddFakeValueDlg* _pATOZAddFakeValueDlg;

	CATIDftDrawing_var _spDrawing;

};

//----------------------------------------------------------------------

#endif
