//===================================================================
// COPYRIGHT ATOZ 2020/06/10
//===================================================================
// CallEngineeringTemplate2Cmd.cpp
// Header definition of class CallEngineeringTemplate2Cmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/06/10 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CallEngineeringTemplate2Cmd_H
#define CallEngineeringTemplate2Cmd_H

#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CallEngineeringTemplate2Dlg.h"

#include "ClsConfigXMLServices.h"
#include "CATPathElementAgent.h"
//system includes
#include "CATUnicodeString.h"
#include "CATCommand.h"
#include "CATBaseUnknown.h"   
#include "CATGetEnvValue.h"
#include "CATLib.h"   
#include "CATListOfCATUnicodeString.h"
#include "CATError.h" 
#include "CATListOfDouble.h"
#include "CATString.h"
#include "CATBSTRDef.h"
#include "CATAutoConversions.h"

//AfrFoundation includes
#include "CATApplicationFrame.h"
#include "CATFrmEditor.h"
#include "CATFrmLayout.h"
#include "CATFrmWindow.h"
//Dialog includes
#include "CATDlgNotify.h"

//AfrNavigator includes
#include "CATFrmNavigGraphicWindow.h"
#include "CATNavigBox.h"

//CATIAApplicationFrame includes
#include "CATCafCenterGraph.h"
//CATPLMComponentInterfaces includes
#include "CATIPLMNavReference.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavRepInstance.h"
#include "CATPLMComponentInterfacesServices.h"
#include "CATListPtrCATIPLMNavOccurrence.h"

//CATPLMIdentificationAccess includes
#include "CATIPLMComponent.h"
#include "CATIAdpType.h"
#include "CATPLMTypeServices.h"
#include "CATListPtrCATIPLMComponent.h"
#include "CATAdpAttributeSet.h"
#include "CATPLMCoreType.h"

//CAT3DPhysicalRepInterfaces includes
#include "CATIPsiRepresentationLoadMode.h"

//CATMecModLiveUseItf includes
#include "CATIMmiUsePrtPart.h"
#include "CATIMmiPrtContainer.h"
#include "CATIMmiMechanicalFeature.h"
#include "CATIPartRequest.h"
#include "CATIBodyRequest.h"

//CATMecModUseItf inlcudes
#include "CATIMmiUseSetFactory.h"
#include "CATIMmiUseMfBRep.h"
#include "CATIMmiUseGeometricalElement.h"

//DataCommonProtocolUse includes
#include "DataCommonProtocolServices.h"
#include "CATIUseEntity.h"

//VisualizationInterfaces includes
#include "CATPathElement.h"
#include "CATIBuildPath.h"
#include "CATIModelEvents.h"
#include "CATModify.h"
#include "CATIVisProperties.h"
#include "CATVisPropertiesValues.h"
#include "CATModifyVisProperties.h"
#include "CATI3DGeoVisu.h"
#include "CATNavigation3DViewer.h"
#include "CATViewpoint.h"
#include "CAT3DViewpoint.h"

//VisualizationController includes
#include "CATViewer.h"
#include "CAT3DViewer.h"
//VisualizationFoundation includes
#include "CAT3DManipulator.h"
//ObjectModelerNavigator includes
#include "CATIRedrawEvent.h"

//SGInfra includes
#include "CAT3DViewpoint.h"
#include "CAT3DBoundingSphere.h"
#include "CAT3DViewpoint.h"
#include "CATSupport.h"
#include "CAT3DBagRep.h"
#include "CAT4x4Matrix.h"
#include "CAT3DFixedArrowGP.h"
#include "CAT3DCustomRep.h"
#include "CAT3DPlanRep.h"

//VisualizationCore includes
#include "CATGraphicAttributeSet.h"

//Mathematics includes
#include "CATMathPointf.h"
#include "CATMathDirectionf.h"
#include "CATMathBox.h"
#include "CATMathPlane.h"
#include "CATMathVector.h"
#include "CATMath3x3Matrix.h"
#include "CAT4x4Matrix.h"
#include "CATLISTV_CATMathPlane.h"

//CATMathStream includes
#include "CATSoftwareConfiguration.h"

//SGManager includes
#include "CATHSO.h"
#include "CATVisManager.h"

//ObjectModelerSystem includes
#include "CATIAlias.h"

//KnowledgeInterfaces includes
#include "CATICkeObject.h"
#include "CATIType.h"
#include "CATAttributeInfos.h"
#include "CATListValCATAttributeInfos.h"
#include "CATICkeParm.h"
#include "CATICkeParmFactory.h"
#include "CATListValCATICkeParm.h"
#include "CATCkeObjectAttrWriteServices.h"
#include "CATCkeObjectAttrReadServices.h"
#include "CATIParmPublisher.h"
#include "CATIKweModelServices.h"
#include "CATCkeGlobalFunctions.h"
#include "CATICkeParameterSet.h"
#include "CATParmPublisherAdapter.h"
#include "CATICkeFunction.h"
#include "CATITypeDictionary.h"

//KnowledgeIDLItf includes
#include "CATIAParameterSet.h"
#include "CATIAParameterSets.h"

//GMModelInterfaces includes
#include "CATBody.h"

//GeometricObjects includes
#include "CATGeoFactory.h"
#include "CATPlane.h"

//GMOperatorsInterfaces includes
#include "CATICGMTopSkin.h"
#include "CATCGMCreateTopIntersect.h"
#include "CATICGMHybIntersect.h"
#include "CATICGMHybSplit.h"
#include "CATCGMCreateTopSplit.h"

//CATMecModLiveUseItf includes
#include "CATIMmiMechanicalFeature.h"
#include "CATIMmiUsePrtPart.h"
#include "CATMmiUseServicesFactory.h"
#include "CATIMmiUseCreateImport.h"
#include "CATIPartRequest.h"
#include "CATLISTV_CATIMmiMechanicalFeature.h"

//CATMecModUseItf includes
#include "CATIMmiUseDatumFactory.h"
#include "CATIMmiUseSolidInsertion.h"
#include "CATIMmiUseBasicInsertion.h"

//CATPartUseItf includes
#include "CATIPdgUsePrtFactory.h"

//MeasureGeometryInterfaces includes
#include "CATIMeasurablePlane.h"

//PLMModelerBaseInterfaces includes
#include "CATIMovable.h"

//CATGSMUseItf includes
#include "CATIGSMUseFactory.h"
#include "CATIGSMUsePlaneOffset.h"

//ProductStructureInterfaces includes
#include "CATIPLMProducts.h"
#include "CATPrdGetOccurrenceMngt.h"
#include "CATIPrdOccurrenceMngt.h"

//-----------------------------------------------------------------------
// CATPLMIntegrationAccess Framework
#include "CATIAdpEnvironment.h"
#include "CATAdpDictionaryServices.h"
#include "CATAdpAttributeSet.h"
#include "CATAdpQueryServices.h"
#include "CATAdpQueryResult.h"
#include "CATAdpIdentificationSet.h"
#include "CATLISTP_CATAdpQueryResult.h"
#include "CATIAdpPLMIdentificator.h"

// CATPLMIntegrationUse Framework
#include "CATAdpPLMQueryFilter.h"
#include "CATAdpPLMComponentsInfos.h"
#include "CATAdpPLMComponentsInfosIter.h"
#include "CATAdpPLMExtendedQueryServices.h"
#include "CATAdpPLMQueryAttributeSet.h"
#include "CATAdpPLMComponentInfos.h"
#include "CATAdpPLMComponentUniqueKey.h"
#include "CATAdpPLMQueryServices.h"
#include "CATAdpOpenParameters.h"
#include "CATAdpOpener.h"


//ProductStructureUseItf includes
#include "CATPrdFactory.h"
#include "CATIPrdReferenceFactory.h"
#include "CATIPrd3DPartReferenceFactory.h"


//PLMDictionaryNavServices Framework
#include "CATCkePLMNavPublicServices.h"
#include "CATCkePLMNavCustoAccessPublicServices.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATCkePLMNavSpecializationAccessPublicServices.h"

// System
#include "CATString.h"
#include "CATListOfCATString.h"
#include "CATUnicodeString.h"
#include "CATListOfCATUnicodeString.h"
#include "CATSysBoolean.h"
#include "CATBaseUnknown.h"
#include "CATLISTP_CATBaseUnknown.h"

//ObjectModelerBase includes
#include "CATOmbLifeCycleRootsBag.h"

#include <iostream>
using namespace std;
//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of Dialog engine framework.
* (consult base class description).
*/
class CallEngineeringTemplate2Cmd: public CATStateCommand
{
// Allows customization/internationalization of command's messages
// ---------------------------------------------------------------
DeclareResource( CallEngineeringTemplate2Cmd, CATStateCommand )

public:

CallEngineeringTemplate2Cmd();
virtual ~CallEngineeringTemplate2Cmd();

virtual void     BuildGraph();

HRESULT InitializeMainDialog();

//选择中心轴系
void SelectAxisSytemObj(void* idata);

//printf object fullpath
void PathElementString(CATPathElement * ipPath, CATUnicodeString & oPathName);

void SelectMidInfPtObj(void* idata);

void SelectSupportPlaneObj(void* idata);

void ExitCmd();

//ok action
void OKAction();

HRESULT RetrievePLMType(const CATUnicodeString & isPLMType, CATIType_var & ospType);

HRESULT GetPLMObjectsFromAttrAndFromType(const CATListOfCATString &listOfAttribute,
	const CATListOfCATUnicodeString &listOfValues,
	const CATUnicodeString &iStrPLMType,
	CATListPtrCATAdpQueryResult & opQueryResults);


HRESULT OpenPLMComponent(const CATUnicodeString &istrPLMType,
	const CATListOfCATString &listAttrName,
	const CATLISTV(CATUnicodeString) &ListAttrValue,
	const IID& iIID,
	void **opiPLMComp,
	CATOmbLifeCycleRootsBag &iBag,
	CATBoolean iExpandAll);

//显示视图
HRESULT DisplayTemplateView();


HRESULT AddChldProduct(const CATIPLMNavReference_var &ispParentProRef,
	const CATIPLMNavReference_var &ispChildProRef,
	CATBaseUnknown_var &ospProdInstanceObj);

//清除对话框代理
void CleanDialogAgent();

HRESULT InitializeConfigData();

//消息类型：Error、Information、Warning
int DisplayMessage(const CATString &istrMsgType,
	const CATUnicodeString &iusMsgToDisplay,
	const CATUnicodeString &iusDlgTitle);

//获取当前part节点和上下文product节点
HRESULT GetCurrentPart(CATIMmiUsePrtPart_var &ospPrtPart,
	                   CATIPLMNavOccurrence_var &ospParentOccurr);

void CallEngineeringTemplate2Cmd::SelectCenterPtObj(void* idata);

//获取EKL中的Action
HRESULT GetKnowledgeAction(const CATIPLMNavReference_var &ispParentNavRef,
	const CATUnicodeString &istrActionName,
	CATBaseUnknown_var &ospActionBUObj);

	//get PLMComponent type
	HRESULT RetrieveComponentType(const CATBaseUnknown_var &ispPLMObject,
		                          CATUnicodeString &ostrType);

	//修改零件参数
	HRESULT ModifyPartParams(const CATIPLMNavReference_var &ispProdRef);

	//返回Part节点
	HRESULT CAAMmrGetPartFromProduct(const CATIPLMNavReference_var &ispPLMNavRef,
		CATIPLMNavRepReference_var &ospPLMRepRef,
		CATIMmiMechanicalFeature_var &ospPartFeature);

	//获取参数集下的参数集
	HRESULT GetParamSetByName(const CATICkeParameterSet_var &ispParentSet,
		                      const CATUnicodeString &istrParmSetName,
		                      CATICkeParameterSet_var &ospParamSet);

	//获取正确的参数名称
	CATUnicodeString GetRightParamName(const CATUnicodeString &istrfullParamName);

	//更新特征
	HRESULT CAAUpdateObject(CATBaseUnknown_var spUpdateObjectBU);
private:

	CallEngineeringTemplate2Dlg*   _pCallEngineeringTemplate2Dlg;

	CATPathElementAgent*      _pSelAxisSystemPathElemAgent;//选择中心轴系代理
	CATPathElementAgent*      _pSelPtPathElemAgent;//选择点代理
	CATPathElementAgent*      _pSelSupportSurfPathElemAgent;//选择支持面代理

	CATDialogAgent*        _pSelAxisSystemDlgAgent;//中心轴系对话框代理
	CATDialogAgent*        _pSelMidInfPtDlgAgent;//中间拐点
	CATDialogAgent*        _pSelCenterPointDlgAgent;//滚筒2中心点
	CATDialogAgent*        _pSelSupportPlaneDlgAgent;//选择支持面对话框代理

	CATOmbLifeCycleRootsBag     _ModelBag;

	CATIMmiMechanicalFeature_var   _spAxisSystemFeature;//中心轴系
	CATIMmiMechanicalFeature_var   _spMidInflectionPointFeature;//中间拐点
	CATIMmiMechanicalFeature_var   _spCenterPointFeature;//滚筒2中心点
	CATIMmiMechanicalFeature_var   _spSupportPlaneFeature;//SupportPlane

	CATIPLMNavOccurrence_var       _spParentOcurr;//当前上下文的product节点

	CATLISTV(CATUnicodeString) _listTemplateInstruction;//模板说明内容

	CATUnicodeString     _strTemplateID;//模板文件product的ID
	CATUnicodeString     _strActionName;//action的名称

	CATUnicodeString     _strModelViewID;//模型显示ID
	CATUnicodeString     _strModelViewVersion;//显示模型的版本
};

//----------------------------------------------------------------------

#endif
