//===================================================================
// COPYRIGHT 3DS 2016/02/09
//===================================================================
// TSTAppD.cpp
// Header definition of class TSTAppD
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2016/02/09 Creation: Code generated by the 3DS wizard
//===================================================================
#ifdef  _WINDOWS_SOURCE
#ifdef  __TSTAppD
#define ExportedByTSTAppD     __declspec(dllexport)
#else
#define ExportedByTSTAppD     __declspec(dllimport)
#endif
#else
#define ExportedByTSTAppD
#endif
